### ISSUE TITLE
Heartbeat SIGSEGV when using an IP in URL for http monitor 

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#10066]
**Version:** 6.6.0 BC3 
**Operating System:** Ubuntu
**Steps to Reproduce:** 
1. Install ES, Kibana and Heartbeat 
2. Change the URL to an IP in heartbeat.yml, then start heartbeat 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xd82315]

goroutine 79 [running]:
github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).readResponse(0xc42047c390, 0x176a2c0, 0xc4200b44e8, 0xc420147600, 0x0, 0xc420042240, 0xc5f1dc, 0x1)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:187 +0x105
github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).RoundTrip.func2(0xc42047c390, 0x176a2c0, 0xc4200b44e8, 0xc420147600, 0xc420147600, 0xc420143c80)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:111 +0x5c
created by github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).RoundTrip
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:110 +0x257

**Comment by liza-mae** [comment]
# Configure monitors
heartbeat.monitors:
- type: http
  urls:
    - "http://10.0.2.15:9200"
  schedule: '@every 10s'

If I run the same steps in 6.5.4 there is no issue,
Also if I change the URL to localhost or another string it works.
