### ISSUE TITLE
Kibana metricbeat module test

### ISSUE THREAD

**Issue by ph** [elastic/beats#10705]
## Flaky Test

* **Test Name:**Kibana metricbeat module test
* **Link:** https://github.com/elastic/beats/blob/master/metricbeat/module/kibana/stats/stats_integration_test.go#L39
* **Branch:** master
* **Notes:** 

Not sure if it's a timeout, a problem with the test itself or with the docker-compose framework.

### Stack Trace

```
14:25:25 Successfully tagged metricbeat965e7019d71f52c0703b8fbdc8ee01b71444d4f1_kibana:latest
14:25:25 Creating metricbeat965e7019d71f52c0703b8fbdc8ee01b71444d4f1_kibana_1 ... 
14:25:25 
14:25:25 Creating metricbeat965e7019d71f52c0703b8fbdc8ee01b71444d4f1_kibana_1 ... done
14:25:25 SIGQUIT: quit
14:25:25 PC=0x489ad1 m=0 sigcode=0
14:25:25 
14:25:25 goroutine 0 [idle]:
14:25:25 runtime.futex(0xe29ea8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffc031818e8, ...)
14:25:25 	/usr/local/go/src/runtime/sys_linux_amd64.s:530 +0x21
14:25:25 runtime.futexsleep(0xe29ea8, 0x0, 0xffffffffffffffff)
14:25:25 	/usr/local/go/src/runtime/os_linux.go:45 +0x4b
14:25:25 runtime.notesleep(0xe29ea8)
14:25:25 	/usr/local/go/src/runtime/lock_futex.go:151 +0xc7
14:25:25 runtime.stopm()
14:25:25 	/usr/local/go/src/runtime/proc.go:1952 +0xe5
14:25:25 runtime.findrunnable(0xc420034f00, 0x0)
14:25:25 	/usr/local/go/src/runtime/proc.go:2415 +0x2c8
14:25:25 runtime.schedule()
14:25:25 	/usr/local/go/src/runtime/proc.go:2541 +0x151
14:25:25 runtime.park_m(0xc420725800)
14:25:25 	/usr/local/go/src/runtime/proc.go:2604 +0x81
14:25:25 runtime.mcall(0x0)
14:25:25 	/usr/local/go/src/runtime/asm_amd64.s:351 +0x5b
14:25:25 
14:25:25 goroutine 1 [chan receive, 9 minutes]:
14:25:25 testing.(*T).Run(0xc42034a000, 0xb13f78, 0x9, 0xb2f720, 0xc420215c00)
14:25:25 	/usr/local/go/src/testing/testing.go:825 +0x597
14:25:25 testing.runTests.func1(0xc42034a000)
14:25:25 	/usr/local/go/src/testing/testing.go:1063 +0xa5
14:25:25 testing.tRunner(0xc42034a000, 0xc420215d48)
14:25:25 	/usr/local/go/src/testing/testing.go:777 +0x16e
14:25:25 testing.runTests(0xc4202935a0, 0xe1dba0, 0x2, 0x2, 0xc42015db80)
14:25:25 	/usr/local/go/src/testing/testing.go:1061 +0x4e2
14:25:25 testing.(*M).Run(0xc42015db80, 0x0)
14:25:25 	/usr/local/go/src/testing/testing.go:978 +0x2ce
14:25:25 main.main()
14:25:25 	_testmain.go:94 +0x325
14:25:25 
14:25:25 goroutine 4 [sleep]:
14:25:25 time.Sleep(0x3b9aca00)
14:25:25 	/usr/local/go/src/runtime/time.go:102 +0x146
14:25:25 github.com/elastic/beats/libbeat/tests/compose.(*Project).Wait(0xc420316c60, 0x258, 0xc4202935c0, 0x2, 0x2, 0x0, 0xe29d60)
14:25:25 	/go/src/github.com/elastic/beats/libbeat/tests/compose/project.go:143 +0x117
14:25:25 github.com/elastic/beats/libbeat/tests/compose.EnsureUpWithTimeout(0xc42034a0f0, 0x258, 0xc4202935c0, 0x2, 0x2)
14:25:25 	/go/src/github.com/elastic/beats/libbeat/tests/compose/compose.go:62 +0x362
14:25:25 github.com/elastic/beats/metricbeat/module/kibana/stats.TestFetch(0xc42034a0f0)
14:25:25 	/go/src/github.com/elastic/beats/metricbeat/module/kibana/stats/stats_integration_test.go:39 +0xdb
14:25:25 testing.tRunner(0xc42034a0f0, 0xb2f720)
14:25:25 	/usr/local/go/src/testing/testing.go:777 +0x16e
14:25:25 created by testing.(*T).Run
14:25:25 	/usr/local/go/src/testing/testing.go:824 +0x565
14:25:25 
14:25:25 goroutine 180 [IO wait, 9 minutes]:
14:25:25 internal/poll.runtime_pollWait(0x7fd544759910, 0x72, 0xdec5e8)
14:25:25 	/usr/local/go/src/runtime/netpoll.go:173 +0x5e
14:25:25 internal/poll.(*pollDesc).wait(0xc4200eac98, 0x72, 0xb84000, 0xdec5e8, 0xffffffffffffffff)
14:25:25 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xe5
14:25:25 internal/poll.(*pollDesc).waitRead(0xc4200eac98, 0xc420552000, 0x1000, 0x1000)
14:25:25 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x4b
14:25:25 internal/poll.(*FD).Read(0xc4200eac80, 0xc420552000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
14:25:25 	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x22a
14:25:25 net.(*netFD).Read(0xc4200eac80, 0xc420552000, 0x1000, 0x1000, 0x0, 0x1, 0x1)
14:25:25 	/usr/local/go/src/net/fd_unix.go:202 +0x66
14:25:25 net.(*conn).Read(0xc42000e5f0, 0xc420552000, 0x1000, 0x1000, 0x439d4c, 0xc42053d910, 0x43a4a2)
14:25:25 	/usr/local/go/src/net/net.go:176 +0x85
14:25:25 net/http.(*persistConn).Read(0xc4203b9440, 0xc420552000, 0x1000, 0x1000, 0x0, 0x838, 0x1)
14:25:25 	/usr/local/go/src/net/http/transport.go:1453 +0x21b
14:25:25 bufio.(*Reader).fill(0xc42019f2c0)
14:25:25 	/usr/local/go/src/bufio/bufio.go:100 +0x1a0
14:25:25 bufio.(*Reader).Peek(0xc42019f2c0, 0x1, 0x0, 0x0, 0x0, 0xc42052c480, 0x0)
14:25:25 	/usr/local/go/src/bufio/bufio.go:132 +0x51
14:25:25 net/http.(*persistConn).readLoop(0xc4203b9440)
14:25:25 	/usr/local/go/src/net/http/transport.go:1601 +0x29b
14:25:25 created by net/http.(*Transport).dialConn
14:25:25 	/usr/local/go/src/net/http/transport.go:1237 +0xb26
14:25:25 
14:25:25 goroutine 7 [IO wait, 9 minutes]:
14:25:25 internal/poll.runtime_pollWait(0x7fd544794f00, 0x72, 0xdec5e8)
14:25:25 	/usr/local/go/src/runtime/netpoll.go:173 +0x5e
14:25:25 internal/poll.(*pollDesc).wait(0xc42015de98, 0x72, 0xb84000, 0xdec5e8, 0xffffffffffffffff)
14:25:25 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xe5
14:25:25 internal/poll.(*pollDesc).waitRead(0xc42015de98, 0xc420352000, 0x1000, 0x1000)
14:25:25 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x4b
14:25:25 internal/poll.(*FD).Read(0xc42015de80, 0xc420352000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
14:25:25 	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x22a
14:25:25 net.(*netFD).Read(0xc42015de80, 0xc420352000, 0x1000, 0x1000, 0x0, 0x1, 0x1)
14:25:25 	/usr/local/go/src/net/fd_unix.go:202 +0x66
14:25:25 net.(*conn).Read(0xc42000e508, 0xc420352000, 0x1000, 0x1000, 0x439d4c, 0xc42004e910, 0x43a4a2)
14:25:25 	/usr/local/go/src/net/net.go:176 +0x85
14:25:25 net/http.(*persistConn).Read(0xc420342360, 0xc420352000, 0x1000, 0x1000, 0x0, 0xff9, 0x1)
14:25:25 	/usr/local/go/src/net/http/transport.go:1453 +0x21b
14:25:25 bufio.(*Reader).fill(0xc4202b0a80)
14:25:25 	/usr/local/go/src/bufio/bufio.go:100 +0x1a0
14:25:25 bufio.(*Reader).Peek(0xc4202b0a80, 0x1, 0x0, 0x0, 0x0, 0xc42017c7e0, 0x0)
14:25:25 	/usr/local/go/src/bufio/bufio.go:132 +0x51
14:25:25 net/http.(*persistConn).readLoop(0xc420342360)
14:25:25 	/usr/local/go/src/net/http/transport.go:1601 +0x29b
14:25:25 created by net/http.(*Transport).dialConn
14:25:25 	/usr/local/go/src/net/http/transport.go:1237 +0xb26
14:25:25 
14:25:25 goroutine 8 [select, 9 minutes]:
14:25:25 net/http.(*persistConn).writeLoop(0xc420342360)
14:25:25 	/usr/local/go/src/net/http/transport.go:1822 +0x1a7
14:25:25 created by net/http.(*Transport).dialConn
14:25:25 	/usr/local/go/src/net/http/transport.go:1238 +0xb4b
14:25:25 
14:25:25 goroutine 33 [IO wait, 9 minutes]:
14:25:25 internal/poll.runtime_pollWait(0x7fd5447943a0, 0x72, 0xdec5e8)
14:25:25 	/usr/local/go/src/runtime/netpoll.go:173 +0x5e
14:25:25 internal/poll.(*pollDesc).wait(0xc420151418, 0x72, 0xb84000, 0xdec5e8, 0xffffffffffffffff)
14:25:25 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xe5
14:25:25 internal/poll.(*pollDesc).waitRead(0xc420151418, 0xc4204ba000, 0x1000, 0x1000)
14:25:25 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x4b
14:25:25 internal/poll.(*FD).Read(0xc420151400, 0xc4204ba000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
14:25:25 	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x22a
14:25:25 net.(*netFD).Read(0xc420151400, 0xc4204ba000, 0x1000, 0x1000, 0x0, 0x1, 0x1)
14:25:25 	/usr/local/go/src/net/fd_unix.go:202 +0x66
14:25:25 net.(*conn).Read(0xc42009c280, 0xc4204ba000, 0x1000, 0x1000, 0x439d4c, 0xc42044e910, 0x43a4a2)
14:25:25 	/usr/local/go/src/net/net.go:176 +0x85
14:25:25 net/http.(*persistConn).Read(0xc4204b8000, 0xc4204ba000, 0x1000, 0x1000, 0x0, 0x83c, 0x1)
14:25:25 	/usr/local/go/src/net/http/transport.go:1453 +0x21b
14:25:25 bufio.(*Reader).fill(0xc4200abc80)
14:25:25 	/usr/local/go/src/bufio/bufio.go:100 +0x1a0
14:25:25 bufio.(*Reader).Peek(0xc4200abc80, 0x1, 0x0, 0x0, 0x0, 0xc42017d500, 0x0)
14:25:25 	/usr/local/go/src/bufio/bufio.go:132 +0x51
14:25:25 net/http.(*persistConn).readLoop(0xc4204b8000)
14:25:25 	/usr/local/go/src/net/http/transport.go:1601 +0x29b
14:25:25 created by net/http.(*Transport).dialConn
14:25:25 	/usr/local/go/src/net/http/transport.go:1237 +0xb26
```

**Comment by ycombinator** [comment]
I haven't seen this failure in a while and looking through the test code in https://github.com/elastic/beats/blob/master/metricbeat/module/kibana/stats/stats_integration_test.go it looks like no tests are currently skipped due to flakiness. So I'm going to close this issue as it appears to be resolved.
