### ISSUE TITLE
[Filebeat] Flaky test test_reload_inputs.Test.test_reload_same_config

### ISSUE THREAD

**Issue by kvch** [elastic/beats#10751]
## Flaky Test

* **Test Name:** test_reload_inputs.Test.test_reload_same_config
* **Link:** Link to file/line number in github
* **Branch:** https://github.com/elastic/beats/pull/10593
* **Notes:** After restarting the job on Travis, it has disappeared.

### Stack Trace

```
======================================================================
ERROR: Test reload same config with same file but different config. Makes sure reloading also works on conflicts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_inputs.py", line 284, in test_reload_same_config
    max_timeout=15)
  File "/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 348, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 15 seconds.
-------------------- >> begin captured stdout << ---------------------
render config
--------------------- >> end captured stdout << ----------------------
```

**Comment by ph** [comment]
We can close this, doesn't appear in any of our most failed test weekly emails and the test is not skipped.
