### ISSUE TITLE
filebeat: Flaky file rotation test

### ISSUE THREAD

**Issue by urso** [elastic/beats#1083]
system test `test_rotating_ignore_older_larger_write_rate` seems to be flaky due to filebeat not quiting with exit code 0. Sometimes fails on jenkins with

```
======================================================================
FAIL: test_rotating_ignore_older_larger_write_rate (test_prospector.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/Beats-PR/src/github.com/elastic/beats/filebeat/tests/system/test_prospector.py", line 141, in test_rotating_ignore_older_larger_write_rate
    proc.check_kill_and_wait()
  File "../../../libbeat/tests/system/beat/beat.py", line 75, in check_kill_and_wait
    return self.check_wait(exit_code=exit_code)
  File "../../../libbeat/tests/system/beat/beat.py", line 64, in check_wait
    assert actual_exit_code == exit_code, "Expected exit code to be %d, but it was %d" % (exit_code, actual_exit_code)
AssertionError: Expected exit code to be 0, but it was 66
```

**Comment by andrewkroh** [comment]
Exit code 66 is a data race.

**Comment by ruflin** [comment]
@andrewkroh Good to know.

**Comment by ruflin** [comment]
This should be solved through https://github.com/elastic/beats/pull/964

**Comment by tsg** [comment]
I think this can be closed.
