### ISSUE TITLE
[Metricbeat] Flaky test in Kibana status Metricset

### ISSUE THREAD

**Issue by sayden** [elastic/beats#10948]
## Flaky Test

* **Test Name:** Kibana module `status` Metricset
* **Link:** Full stack trace can be found here https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/beat=metricbeat,label=linux-immutable/5389/consoleFull
* **Branch:** master
* **Notes:** It happens just sometimes and I have only seen it in Jenkins.

### Partial Stack Trace

```
16:11:19 ?   	github.com/elastic/beats/metricbeat/module/kibana/mtest	[no test files]
16:11:21 ok  	github.com/elastic/beats/metricbeat/module/kafka	1.035s	coverage: 28.6% of statements
16:11:21 ok  	github.com/elastic/beats/metricbeat/module/kafka/consumergroup	1.028s	coverage: 79.4% of statements
16:11:21 ?   	github.com/elastic/beats/metricbeat/module/kubernetes	[no test files]
16:11:22 ok  	github.com/elastic/beats/metricbeat/module/kibana	1.018s	coverage: 9.7% of statements
16:11:22 ok  	github.com/elastic/beats/metricbeat/module/kibana/stats	1.030s	coverage: 41.1% of statements
16:11:23 ok  	github.com/elastic/beats/metricbeat/module/kibana/status	1.031s	coverage: 42.6% of statements
16:19:39 Building kibana
16:19:39 Step 1/2 : FROM docker.elastic.co/kibana/kibana:6.6.0
16:19:39 6.6.0: Pulling from kibana/kibana
16:20:08 Digest: sha256:7c6eadb13667e36d21b7e96809a02d14527c15bbfc5b92631168a58ed5f9fd33
16:20:08 Status: Downloaded newer image for docker.elastic.co/kibana/kibana:6.6.0
16:20:08  ---> dfc685453eaa
16:20:08 Step 2/2 : HEALTHCHECK --interval=1s --retries=300 CMD curl -f http://localhost:5601/api/status | grep '"disconnects"'
16:20:10  ---> Running in 2a5055a625ea
16:20:10 Removing intermediate container 2a5055a625ea
16:20:10  ---> dc20dab37221
16:20:10 
16:20:10 Successfully built dc20dab37221
16:20:10 Successfully tagged metricbeat17e77212f0ff9ea04c9260c2cd975fc6d645287f_kibana:latest
16:29:02 ok  	github.com/elastic/beats/metricbeat/module/kibana	1.050s	coverage: 9.7% of statements
16:29:02 ?   	github.com/elastic/beats/metricbeat/module/kibana/mtest	[no test files]
16:39:06 command [go test -race -tags integration -cover -coverprofile /tmp/gotestcover-125050760 github.com/elastic/beats/metricbeat/module/kibana/stats]: exit status 1
16:39:06 Killing metricbeat17e77212f0ff9ea04c9260c2cd975fc6d645287f_etcd_1 ... 
16:39:06 
16:39:06 Killing metricbeat17e77212f0ff9ea04c9260c2cd975fc6d645287f_etcd_1 ... done
16:39:06 Killing metricbeat17e77212f0ff9ea04c9260c2cd975fc6d645287f_envoyproxy_1 ... 
16:39:06 
16:39:06 Killing metricbeat17e77212f0ff9ea04c9260c2cd975fc6d645287f_envoyproxy_1 ... done
16:39:06 Building kibana
16:39:06 Step 1/2 : FROM docker.elastic.co/kibana/kibana:6.6.0
16:39:06  ---> dfc685453eaa
16:39:06 Step 2/2 : HEALTHCHECK --interval=1s --retries=300 CMD curl -f http://localhost:5601/api/status | grep '"disconnects"'
16:39:06  ---> Using cache
16:39:06  ---> dc20dab37221
16:39:06 
16:39:06 Successfully built dc20dab37221
16:39:06 Successfully tagged metricbeat17e77212f0ff9ea04c9260c2cd975fc6d645287f_kibana:latest
16:39:06 Creating metricbeat17e77212f0ff9ea04c9260c2cd975fc6d645287f_kibana_1 ... 
16:39:06 
16:39:06 Creating metricbeat17e77212f0ff9ea04c9260c2cd975fc6d645287f_kibana_1 ... done
16:39:06 SIGQUIT: quit
16:39:06 goroutine 21 [sleep]:
16:39:06 time.Sleep(0x3b9aca00)
16:39:06 	/usr/local/go/src/runtime/time.go:102 +0x146
16:39:06 github.com/elastic/beats/libbeat/tests/compose.(*Project).Wait(0xc420348010, 0x258, 0xc42033c000, 0x2, 0x2, 0x0, 0x1)
16:39:06 	/go/src/github.com/elastic/beats/libbeat/tests/compose/project.go:143 +0x117
16:39:06 github.com/elastic/beats/libbeat/tests/compose.EnsureUpWithTimeout(0xc4203340f0, 0x258, 0xc42033c000, 0x2, 0x2)
16:39:06 	/go/src/github.com/elastic/beats/libbeat/tests/compose/compose.go:62 +0x362
16:39:06 github.com/elastic/beats/metricbeat/module/kibana/stats.TestFetch(0xc4203340f0)
16:39:06 	/go/src/github.com/elastic/beats/metricbeat/module/kibana/stats/stats_integration_test.go:39 +0xdb
16:39:06 testing.tRunner(0xc4203340f0, 0xb30750)
16:39:06 	/usr/local/go/src/testing/testing.go:777 +0x16e
16:39:06 created by testing.(*T).Run
16:39:06 	/usr/local/go/src/testing/testing.go:824 +0x565

16:39:43 *** Test killed with quit: ran too long (10m0s).
16:39:43 FAIL	github.com/elastic/beats/metricbeat/module/kibana/status	600.245s
16:39:43 test failed
```

**Comment by cachedout** [comment]
I wonder if this is related to the CCR test failure at all? It's happening at almost ~600s from the failure of the ES container that occurs when the CCR test seems to die.

**Comment by sayden** [comment]
Ohhh :heart_eyes: You are right, I didn't realize of that. It looks like "ES is not ready so Kibana cannot work either" but then all test of ES and Kibana should fail... I guess :thinking: 

Definitely, it looks like at some point, it wouldn't matter much 600 or 6000 seconds

**Comment by ycombinator** [comment]
I haven't seen this failure in a while and looking through the unit and integration tests under https://github.com/elastic/beats/tree/master/metricbeat/module/kibana/stats and https://github.com/elastic/beats/tree/master/metricbeat/module/kibana/status it looks like no tests are currently skipped. So I'm going to close this issue as it appears to be resolved.
