### ISSUE TITLE
Enabling migration.enabled: true in metricbeat.yml breaks the writing of metricbeat index template to elasticsearch

### ISSUE THREAD

**Issue by bhavyarm** [elastic/beats#11271]
- Version: 7.0.0 BC1 metricbeat/elasticsearch/kibana
- Operating System: darwin_x86_64
- Steps to Reproduce: 
If user enables migration.enabled: true in metricbeat.yml - metricbeat cannot write the indexpattern  template [metricbeat-7.0.0-rc1] into elasticsearch.

This is what the ES logs say:
```
2019-03-15T15:10:08,796][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [bhavyarajumandya] updating index lifecycle policy [metricbeat-7.0.0-rc1]
[2019-03-15T15:10:09,025][DEBUG][o.e.a.a.i.t.p.TransportPutIndexTemplateAction] [bhavyarajumandya] failed to put template [metricbeat-7.0.0-rc1]
java.lang.IllegalArgumentException: Invalid [path] value [rabbitmq.node.name] for field alias [rabbitmq.node.name]: an alias cannot refer to itself.
    at org.elasticsearch.index.mapper.FieldTypeLookup.validateAlias(FieldTypeLookup.java:128) ~[elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.index.mapper.FieldTypeLookup.copyAndAddAll(FieldTypeLookup.java:83) ~[elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:480) ~[elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:398) ~[elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:323) ~[elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.validateAndAddTemplate(MetaDataIndexTemplateService.java:253) ~[elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.access$300(MetaDataIndexTemplateService.java:65) ~[elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService$2.execute(MetaDataIndexTemplateService.java:176) ~[elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:687) ~[elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:310) ~[elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:210) [elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:142) [elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.0.0-rc1.jar:7.0.0-rc1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by ruflin** [comment]
Opened https://github.com/elastic/beats/pull/11284 with a fix and added tests to make sure this does not happen again.
