### ISSUE TITLE
[libbeat] keystore add without tty panics

### ISSUE THREAD

**Issue by graphaelli** [elastic/beats#11311]
```
$ docker run --rm docker.elastic.co/beats/filebeat:6.6.2 filebeat keystore add foo
The keystore does not exist. Do you want to create it? [y/N]: panic: could not read from input
goroutine 1 [running]:
runtime/debug.Stack(0x21, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/elastic/beats/libbeat/common/cli.exitOnPanic()
	/go/src/github.com/elastic/beats/libbeat/common/cli/cli.go:31 +0xac
panic(0x1589a40, 0x185b2b0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/elastic/beats/libbeat/common/terminal.PromptYesNo(0x17c0a85, 0x36, 0x0, 0x17858e8)
	/go/src/github.com/elastic/beats/libbeat/common/terminal/terminal.go:55 +0x2d6
github.com/elastic/beats/libbeat/cmd.addKey(0x187eae0, 0xc42016a340, 0xc420168060, 0x1, 0x1, 0xc420160000, 0x0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/cmd/keystore.go:174 +0x964
github.com/elastic/beats/libbeat/cmd.genAddKeystoreCmd.func1(0xc42047dd40, 0xc420168060, 0x1, 0x1, 0x177e2d4, 0x4)
	/go/src/github.com/elastic/beats/libbeat/cmd/keystore.go:100 +0xd2
github.com/elastic/beats/libbeat/common/cli.RunWith.func1(0xc42047dd40, 0xc420168060, 0x1, 0x1)
	/go/src/github.com/elastic/beats/libbeat/common/cli/cli.go:42 +0x84
github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).execute(0xc42047dd40, 0xc420168020, 0x1, 0x1, 0xc42047dd40, 0xc420168020)
	/go/src/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:704 +0x2c6
github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420453180, 0x0, 0xc420453180, 0x178308f)
	/go/src/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:785 +0x2e4
github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420453180, 0xc4204cff78, 0xc4200400b8)
	/go/src/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:738 +0x2b
main.main()
	/go/src/github.com/elastic/beats/x-pack/filebeat/main.go:22 +0x2f
```

This should probably just print out an error message and exit non-zero instead.

**Comment by graphaelli** [comment]
still panics in 7.10.2
