### ISSUE TITLE
Flaky test: coredns

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#11704]
## Flaky Test

* **Test Name:** test_coredns.Test 
* **Link:** https://github.com/elastic/beats/blob/master/metricbeat/tests/system/test_coredns.py
* **Branch:** Master
* **Artifact Link:** https://travis-ci.org/elastic/beats/jobs/517359784 
https://travis-ci.org/elastic/beats/jobs/517184668
https://travis-ci.org/elastic/beats/jobs/517306671
https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/6817/beat=metricbeat,label=linux-immutable/console

### Stack Trace

```
ERROR: test suite for <class 'test_coredns.Test'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/local/lib/python2.7/dist-packages/nose/util.py", line 471, in try_run
    return func()
  File "/go/src/github.com/elastic/beats/metricbeat/tests/system/metricbeat.py", line 28, in setUpClass
    super(BaseTest, self).setUpClass()
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/beat/beat.py", line 150, in setUpClass
    self.compose_up()
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/beat/compose.py", line 85, in compose_up
    ','.join(cls.COMPOSE_SERVICES))
Exception: Timeout while waiting for healthy docker-compose services: coredns
```
Two of my PRs, and a handful of open PRs I'm seeing are failing with this. I don't have much knowledge of coredns, but I'm poking around and having trouble figuring out what the issue is.

**Comment by fearful-symmetry** [comment]
started the coredns container with docker-compose on my laptop, it'll end up in an unhealthy: state after a few minutes:

```
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 13,
                "Log": [
                    {
                        "Start": "2019-04-08T18:35:36.7968972Z",
                        "End": "2019-04-08T18:35:51.8894638Z",
                        "ExitCode": 9,
                        "Output": ""
                    },
```

**Comment by ruflin** [comment]
I see https://github.com/elastic/beats/pull/11711 has been merged. Does this resolve this flaky test issue?

**Comment by odacremolbap** [comment]
I'd say so
https://travis-ci.org/elastic/beats/builds/517634280
