### ISSUE TITLE
[libbeat] race deted in output elasticsearch api_integration_test

### ISSUE THREAD

**Issue by simitt** [elastic/beats#12170]
## Flaky Test

* **Test Name:** `libbeat/outputs/elasticsearch.TestIndex`
* **Link:** [outputs/elasticsearch/api_integration_test.go#L77](https://github.com/elastic/beats/blob/master/libbeat/outputs/elasticsearch/api_integration_test.go#L77).
* **Branch:** https://github.com/elastic/beats/pull/12132 failure seems unrelated to changes though

### Stack Trace
```
15:23:38 command [go test -race -tags integration -cover -coverprofile /tmp/gotestcover-991687420 github.com/elastic/beats/libbeat/outputs/elasticsearch]: exit status 1
15:23:38 --- FAIL: TestIndex (0.58s)
15:23:38     api_integration_test.go:75: SearchUri() returns an error: 400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/beats-test-index-17555/test/_search] contains unrecognized parameter: [q]"}],"type":"illegal_argument_exception","reason":"request [/beats-test-index-17555/test/_search] contains unrecognized parameter: [q]"},"status":400}
15:23:38 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
15:23:38 	panic: runtime error: invalid memory address or nil pointer dereference
15:23:38 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe9fa32]
15:23:38 
15:23:38 goroutine 5 [running]:
15:23:38 testing.tRunner.func1(0xc00011c100)
15:23:38 	/usr/local/go/src/testing/testing.go:830 +0x69d
15:23:38 panic(0xf89ca0, 0x1843ee0)
15:23:38 	/usr/local/go/src/runtime/panic.go:522 +0x1b5
15:23:38 github.com/elastic/beats/libbeat/outputs/elasticsearch.TestIndex(0xc00011c100)
15:23:38 	/go/src/github.com/elastic/beats/libbeat/outputs/elasticsearch/api_integration_test.go:77 +0x8f2
15:23:38 testing.tRunner(0xc00011c100, 0x10561d8)
15:23:38 	/usr/local/go/src/testing/testing.go:865 +0x164
15:23:38 created by testing.(*T).Run
15:23:38 	/usr/local/go/src/testing/testing.go:916 +0x65b
15:23:38 FAIL	github.com/elastic/beats/libbeat/outputs/elasticsearch	0.634s
```

**Comment by simitt** [comment]
Also happened on https://github.com/elastic/beats/pull/12160

**Comment by simitt** [comment]
update: happened on `master` for the first time [here](https://beats-ci.elastic.co/job/elastic+beats+master+multijob-linux/1087/beat=libbeat,label=linux-immutable/)

**Comment by ph** [comment]
This might still be possible, I've labeled this as a bug and we need more investigation.
I haven't seen this in test suite or any test failling reports.
