### ISSUE TITLE
Multiline misses some glassfish messages

### ISSUE THREAD

**Issue by kallisti5** [elastic/beats#13519]
```yaml
- type: log
  enabled: true
  paths:
    - /thing/server.log
  multiline.pattern: \[\#\|
  multiline.negate: true
  multiline.match: after
  multiline.flush_pattern: \|\#\]
```

Sample event not parsed:
```
[#|2019-08-28T10:48:35.105-0500|INFO|glassfish0.0.0|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=59;_ThreadName=Thread-2;|2019-08-28 10:48:35,104 ERROR RandomApiAction - Unable to perform action due to Exception (Error ID: 1234567891234)
com.xx.util.service.ServiceUnavailableException: com.xx.util.service.ServiceUnavailableException: com.xx.util.service.ServiceUnavailableException: com.xx.util.service.ServiceUnavailableException: javax.bus.BUSException
	at com.xx.coolapp.controller.actions.api.SubmitSaveAssociateAction.performAction(SubmitSaveAssociateAction.java:0000
	at com.xx.coolapp.controller.actions.SecureAction.execute(SecureAction.java:0000
	at com.xx.coolapp.controller.actions.api.SecureApiAction.execute(SecureApiAction.java:0000
	at org.apache.struts.chain.commands.servlet.ExecuteAction.execute(ExecuteAction.java:0000
	at org.apache.struts.chain.commands.AbstractExecuteAction.execute(AbstractExecuteAction.java:0000
	at org.apache.struts.chain.commands.ActionCommandBase.execute(ActionCommandBase.java:0000
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:0000
	at org.apache.commons.chain.generic.LookupCommand.execute(LookupCommand.java:0000
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:0000
	at org.apache.struts.chain.ComposableRequestProcessor.process(ComposableRequestProcessor.java:0000
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:0000
	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:0000
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:0000
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:0000
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:0000
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:0000
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:0000
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:0000
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:0000
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:0000
	at org.apache.catalina.connector.BearRace.doService(BearRace.java:0000
	at org.apache.catalina.connector.BearRace.service(BearRace.java:0000
	at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:0000
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:0000
	at com.sun.polarbear.http.ProcessorTask.invokeAdapter(ProcessorTask.java:0000
	at com.sun.polarbear.http.ProcessorTask.doProcess(ProcessorTask.java:0000
	at com.sun.polarbear.http.ProcessorTask.process(ProcessorTask.java:0000
	at com.sun.polarbear.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:0000
	at com.sun.polarbear.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:0000
	at com.sun.polarbear.DefaultProtocolChain.execute(DefaultProtocolChain.java:0000
	at com.sun.polarbear.DefaultProtocolChain.execute(DefaultProtocolChain.java:0000
	at com.sun.polarbear.http.HttpProtocolChain.execute(HttpProtocolChain.java:0000
	at com.sun.polarbear.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:0000
	at com.sun.polarbear.SelectionKeyContextTask.call(SelectionKeyContextTask.java:0000
	at com.sun.polarbear.ContextTask.run(ContextTask.java:0000
	at com.sun.polarbear.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:0000
	at com.sun.polarbear.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:0000
	at java.lang.Thread.run(Thread.java:0000
Caused by: com.xx.util.service.ServiceUnavailableException: com.xx.util.service.ServiceUnavailableException: javax.bus.BUSException
	at com.xx.security.accountmanager.SuperFunLocalService.removeBearsFromOrg(SuperFunLocalService.java:0000
	at com.xx.coolapp.controller.actions.api.SubmitSaveAssociateAction.performAction(SubmitSaveAssociateAction.java:0000
	... 37 more
Caused by: javax.bus.BUSException
	at com.sun.bus.containers.BaseContainer.processSystemException(BaseContainer.java:0000
	at com.sun.bus.containers.BaseContainer.completeNewTx(BaseContainer.java:0000
	at com.sun.bus.containers.BaseContainer.postInvokeTx(BaseContainer.java:0000
	at com.sun.bus.containers.BaseContainer.postInvoke(BaseContainer.java:0000
	at com.sun.bus.containers.BaseContainer.postInvoke(BaseContainer.java:0000
	at com.sun.bus.containers.BUSLocalObjectInvocationHandler.invoke(BUSLocalObjectInvocationHandler.java:0000
	at com.sun.bus.containers.BUSLocalObjectInvocationHandlerDelegate.invoke(BUSLocalObjectInvocationHandlerDelegate.java:0000
	at com.sun.proxy.$Proxy225.removeBearsFromOrg(Unknown Source)
	at com.xx.security.accountmanager.SuperFunLocalService.removeBearsFromOrg(SuperFunLocalService.java:0000
	... 38 more
Caused by: javax.persistence.PersistenceException: Exception [SuperMagicLink-4002] (SuperMagic Persistence Services - 0.0.0.v00000000-r00000): org.supermagic.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: ORA-06519: active autonomous transaction detected and rolled back
ORA-06512: at "MAGICFUNTIME.MAGIC_SCHOOLBUS_TRIPA", line 00
ORA-04088: error during execution of trigger 'MAGICFUNTIME.MAGIC_SCHOOLBUS_TRIPA'

Error Code: 0000
Call: DELETE FROM SCHOOL_BUSA_ORG WHERE (((BUS_ID = ?) AND (SCHOOL_ID = ?)) AND (BUSA_ID = ?))
	bind => [3 parameters bound]
Query: DeleteObjectQuery(com.xx.security.account.BearsRoleOrg@74fbcffd)
	at org.supermagic.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:0000
	at org.supermagic.persistence.internal.jpa.BUSQueryImpl.performPreQueryFlush(BUSQueryImpl.java:0000
	at org.supermagic.persistence.internal.jpa.BUSQueryImpl.executeReadQuery(BUSQueryImpl.java:0000
	at org.supermagic.persistence.internal.jpa.BUSQueryImpl.getResultList(BUSQueryImpl.java:0000
	at com.xx.security.accountmanager.SuperFunBean.get(SuperFunBean.java:0000
	at com.xx.security.accountmanager.SuperFunBean.removeEmail(SuperFunBean.java:0000
	at com.xx.security.accountmanager.SuperFunBean.removeBearsFromOrg(SuperFunBean.java:0000
	at sun.reflect.GeneratedMethodAccessor263.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:0000
	at java.lang.reflect.Method.invoke(Method.java:0000
	at org.glassfish.bus.security.application.BUSSecurityManager.runMethod(BUSSecurityManager.java:0000
	at org.glassfish.bus.security.application.BUSSecurityManager.invoke(BUSSecurityManager.java:0000
	at com.sun.bus.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:0000
	at com.sun.bus.EjbInvocation.invokeBeanMethod(EjbInvocation.java:0000
	at com.sun.bus.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:0000
	at com.sun.bus.EjbInvocation.proceed(EjbInvocation.java:0000
	at com.sun.bus.containers.interceptors.SystemInterceptorProxy.doAround(SystemInterceptorProxy.java:0000
	at com.sun.bus.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:0000
	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:0000
	at java.lang.reflect.Method.invoke(Method.java:0000
	at com.sun.bus.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:0000
	at com.sun.bus.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:0000
	at com.sun.bus.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:0000
	at com.sun.bus.containers.BaseContainer.__intercept(BaseContainer.java:0000
	at com.sun.bus.containers.BaseContainer.intercept(BaseContainer.java:0000
	at com.sun.bus.containers.BUSLocalObjectInvocationHandler.invoke(BUSLocalObjectInvocationHandler.java:0000
	... 41 more
Caused by: Exception [SuperMagicLink-4002] (SuperMagic Persistence Services - 0.0.0.v00000000-r00000): org.supermagic.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: ORA-06519: active autonomous transaction detected and rolled back
ORA-06512: at "MAGICFUNTIME.MAGIC_SCHOOLBUS_TRIPA_NE", line 56
ORA-04088: error during execution of trigger 'MAGICFUNTIME.MAGIC_SCHOOLBUS_TRIPA_NE'

Error Code: 6519
Call: DELETE FROM SCHOOL_BUSA_NET WHERE (((|#]
```

**Comment by dplavcic** [comment]
Hello,

I was able to reproduced this using Filebeat 7.2. The problem seems to be related with  `multiline.flush_pattern: \|\#\]`.
If you remove this line the log file record is parsed fine.

I'll take look into and let you know the details.

**Comment by kallisti5** [comment]
Thanks :-)

That flush_pattern is required to detect the end of the multi-line log event.  My only thought is the event is so long that filebeats "gives up"?

**Comment by dplavcic** [comment]
When I tried to recreate this first time I remember that only part of the event was parsed and uploaded to the ElasticSearch.

I tried to recreate described issue once again, using Filebeat 7.2.2 and the clean installation of the ELK 7.2 I couldn't. Everything seems to be working fine :confused: 

Below is log that confirms my observations:

```
2019-09-10T06:58:30.465+0200	INFO	log/harvester.go:253	Harvester started for file: /filebeat/logs/glassfish.log
2019-09-10T06:58:30.465+0200	INFO	[detect_null_bytes]	debug/debug.go:95	Starting debug reader with a buffer size of 16384 and max failures of 100
2019-09-10T06:58:30.468+0200	DEBUG	[harvester]	log/log.go:102	End of file reached: /filebeat/logs/glassfish.log; Backoff now.
2019-09-10T06:58:30.469+0200	DEBUG	[processors]	processing/processors.go:183	Publish event: {
  "@timestamp": "2019-09-10T04:58:30.466Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "7.2.2"
  },
  "message": "[#|2019-08-28T10:48:35.105-0500|INFO|glassfish0.0.0|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=59;_ThreadName=Thread-2;|2019-08-28 10:48:35,104 ERROR RandomApiAction - Unable to perform action due to Exception (Error ID: 1234567891234)\ncom.xx.util.service.ServiceUnavailableException: com.xx.util.service.ServiceUnavailableException: com.xx.util.service.ServiceUnavailableException: com.xx.util.service.ServiceUnavailableException: javax.bus.BUSException\n\tat com.xx.coolapp.controller.actions.api.SubmitSaveAssociateAction.performAction(SubmitSaveAssociateAction.java:0000\n\tat com.xx.coolapp.controller.actions.SecureAction.execute(SecureAction.java:0000\n\tat com.xx.coolapp.controller.actions.api.SecureApiAction.execute(SecureApiAction.java:0000\n\tat org.apache.struts.chain.commands.servlet.ExecuteAction.execute(ExecuteAction.java:0000\n\tat org.apache.struts.chain.commands.AbstractExecuteAction.execute(AbstractExecuteAction.java:0000\n\tat org.apache.struts.chain.commands.ActionCommandBase.execute(ActionCommandBase.java:0000\n\tat org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:0000\n\tat org.apache.commons.chain.generic.LookupCommand.execute(LookupCommand.java:0000\n\tat org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:0000\n\tat org.apache.struts.chain.ComposableRequestProcessor.process(ComposableRequestProcessor.java:0000\n\tat org.apache.struts.action.ActionServlet.process(ActionServlet.java:0000\n\tat org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:0000\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:0000\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:0000\n\tat org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:0000\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:0000\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:0000\n\tat org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:0000\n\tat org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:0000\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:0000\n\tat org.apache.catalina.connector.BearRace.doService(BearRace.java:0000\n\tat org.apache.catalina.connector.BearRace.service(BearRace.java:0000\n\tat com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:0000\n\tat com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:0000\n\tat com.sun.polarbear.http.ProcessorTask.invokeAdapter(ProcessorTask.java:0000\n\tat com.sun.polarbear.http.ProcessorTask.doProcess(ProcessorTask.java:0000\n\tat com.sun.polarbear.http.ProcessorTask.process(ProcessorTask.java:0000\n\tat com.sun.polarbear.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:0000\n\tat com.sun.polarbear.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:0000\n\tat com.sun.polarbear.DefaultProtocolChain.execute(DefaultProtocolChain.java:0000\n\tat com.sun.polarbear.DefaultProtocolChain.execute(DefaultProtocolChain.java:0000\n\tat com.sun.polarbear.http.HttpProtocolChain.execute(HttpProtocolChain.java:0000\n\tat com.sun.polarbear.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:0000\n\tat com.sun.polarbear.SelectionKeyContextTask.call(SelectionKeyContextTask.java:0000\n\tat com.sun.polarbear.ContextTask.run(ContextTask.java:0000\n\tat com.sun.polarbear.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:0000\n\tat com.sun.polarbear.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:0000\n\tat java.lang.Thread.run(Thread.java:0000\nCaused by: com.xx.util.service.ServiceUnavailableException: com.xx.util.service.ServiceUnavailableException: javax.bus.BUSException\n\tat com.xx.security.accountmanager.SuperFunLocalService.removeBearsFromOrg(SuperFunLocalService.java:0000\n\tat com.xx.coolapp.controller.actions.api.SubmitSaveAssociateAction.performAction(SubmitSaveAssociateAction.java:0000\n\t... 37 more\nCaused by: javax.bus.BUSException\n\tat com.sun.bus.containers.BaseContainer.processSystemException(BaseContainer.java:0000\n\tat com.sun.bus.containers.BaseContainer.completeNewTx(BaseContainer.java:0000\n\tat com.sun.bus.containers.BaseContainer.postInvokeTx(BaseContainer.java:0000\n\tat com.sun.bus.containers.BaseContainer.postInvoke(BaseContainer.java:0000\n\tat com.sun.bus.containers.BaseContainer.postInvoke(BaseContainer.java:0000\n\tat com.sun.bus.containers.BUSLocalObjectInvocationHandler.invoke(BUSLocalObjectInvocationHandler.java:0000\n\tat com.sun.bus.containers.BUSLocalObjectInvocationHandlerDelegate.invoke(BUSLocalObjectInvocationHandlerDelegate.java:0000\n\tat com.sun.proxy.$Proxy225.removeBearsFromOrg(Unknown Source)\n\tat com.xx.security.accountmanager.SuperFunLocalService.removeBearsFromOrg(SuperFunLocalService.java:0000\n\t... 38 more\nCaused by: javax.persistence.PersistenceException: Exception [SuperMagicLink-4002] (SuperMagic Persistence Services - 0.0.0.v00000000-r00000): org.supermagic.persistence.exceptions.DatabaseException\nInternal Exception: java.sql.SQLException: ORA-06519: active autonomous transaction detected and rolled back\nORA-06512: at \"MAGICFUNTIME.MAGIC_SCHOOLBUS_TRIPA\", line 00\nORA-04088: error during execution of trigger 'MAGICFUNTIME.MAGIC_SCHOOLBUS_TRIPA'\n\nError Code: 0000\nCall: DELETE FROM SCHOOL_BUSA_ORG WHERE (((BUS_ID = ?) AND (SCHOOL_ID = ?)) AND (BUSA_ID = ?))\n\tbind => [3 parameters bound]\nQuery: DeleteObjectQuery(com.xx.security.account.BearsRoleOrg@74fbcffd)\n\tat org.supermagic.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:0000\n\tat org.supermagic.persistence.internal.jpa.BUSQueryImpl.performPreQueryFlush(BUSQueryImpl.java:0000\n\tat org.supermagic.persistence.internal.jpa.BUSQueryImpl.executeReadQuery(BUSQueryImpl.java:0000\n\tat org.supermagic.persistence.internal.jpa.BUSQueryImpl.getResultList(BUSQueryImpl.java:0000\n\tat com.xx.security.accountmanager.SuperFunBean.get(SuperFunBean.java:0000\n\tat com.xx.security.accountmanager.SuperFunBean.removeEmail(SuperFunBean.java:0000\n\tat com.xx.security.accountmanager.SuperFunBean.removeBearsFromOrg(SuperFunBean.java:0000\n\tat sun.reflect.GeneratedMethodAccessor263.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:0000\n\tat java.lang.reflect.Method.invoke(Method.java:0000\n\tat org.glassfish.bus.security.application.BUSSecurityManager.runMethod(BUSSecurityManager.java:0000\n\tat org.glassfish.bus.security.application.BUSSecurityManager.invoke(BUSSecurityManager.java:0000\n\tat com.sun.bus.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:0000\n\tat com.sun.bus.EjbInvocation.invokeBeanMethod(EjbInvocation.java:0000\n\tat com.sun.bus.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:0000\n\tat com.sun.bus.EjbInvocation.proceed(EjbInvocation.java:0000\n\tat com.sun.bus.containers.interceptors.SystemInterceptorProxy.doAround(SystemInterceptorProxy.java:0000\n\tat com.sun.bus.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:0000\n\tat sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:0000\n\tat java.lang.reflect.Method.invoke(Method.java:0000\n\tat com.sun.bus.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:0000\n\tat com.sun.bus.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:0000\n\tat com.sun.bus.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:0000\n\tat com.sun.bus.containers.BaseContainer.__intercept(BaseContainer.java:0000\n\tat com.sun.bus.containers.BaseContainer.intercept(BaseContainer.java:0000\n\tat com.sun.bus.containers.BUSLocalObjectInvocationHandler.invoke(BUSLocalObjectInvocationHandler.java:0000\n\t... 41 more\nCaused by: Exception [SuperMagicLink-4002] (SuperMagic Persistence Services - 0.0.0.v00000000-r00000): org.supermagic.persistence.exceptions.DatabaseException\nInternal Exception: java.sql.SQLException: ORA-06519: active autonomous transaction detected and rolled back\nORA-06512: at \"MAGICFUNTIME.MAGIC_SCHOOLBUS_TRIPA_NE\", line 56\nORA-04088: error during execution of trigger 'MAGICFUNTIME.MAGIC_SCHOOLBUS_TRIPA_NE'\n\nError Code: 6519\nCall: DELETE FROM SCHOOL_BUSA_NET WHERE (((|#]",
  "input": {
    "type": "log"
  },
  "ecs": {
    "version": "1.0.0"
  },
  "host": {
    "containerized": false,
    "hostname": "issues-13519-pc",
    ...
  },
  "agent": {
    "type": "filebeat",
    "ephemeral_id": "767b75f4-1405-4ed0-9eee-b66c3a07a03e",
    "hostname": "issues-13519-pc",
    "id": "17d5d755-81fb-4657-98f8-8be610b6b91d",
    "version": "7.2.2"
  },
  "log": {
    "offset": 0,
    "file": {
      "path": "/filebeat/logs/glassfish.log"
    },
    "flags": [
      "multiline"
    ]
  }
}
2019-09-10T06:58:30.472+0200	DEBUG	[registrar]	registrar/registrar.go:404	Registry file updated. 1 states written.
2019-09-10T06:58:31.468+0200	DEBUG	[harvester]	log/log.go:102	End of file reached: /filebeat/logs/glassfish.log; Backoff now.
2019-09-10T06:58:31.470+0200	INFO	pipeline/output.go:95	Connecting to backoff(elasticsearch(http://localhost:9200))
```

Could you please try to recreate this once again and also please specify the exact version of your stack (Filebeat, Elastic)?

**Comment by kallisti5** [comment]
Hm.. Old version of filebeat.  I'll try upgrading and report back.
```
logstash-7.3.1-1.noarch
elasticsearch-7.3.1-1.x86_64
filebeat-6.5.1-1.x86_64
```

Also, this is  filebeat -> logstash -> elastic.
