### ISSUE TITLE
Flaky test: test_beat.Test.test_xpack

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#13947]
## Flaky Test

* **Test Name:** test_beat.Test.test_xpack
* **Link:** https://github.com/elastic/beats/blob/d1cd81a15b8645ca83e2932d058fb64149d4fe00/metricbeat/tests/system/test_beat.py#L23
* **Branch:** `master`

### Stack Trace

```
08:47:47 ======================================================================
08:47:47 ERROR: beat-xpack module tests
08:47:47 ----------------------------------------------------------------------
08:47:47 Traceback (most recent call last):
08:47:47   File "/go/src/github.com/elastic/beats/metricbeat/tests/system/test_beat.py", line 45, in test_xpack
08:47:47     self.wait_until(lambda: self.output_lines() > 0)
08:47:47   File "/go/src/github.com/elastic/beats/libbeat/tests/system/beat/beat.py", line 352, in wait_until
08:47:47     "Waited {} seconds.".format(max_timeout))
08:47:47 TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
```

**Comment by ycombinator** [comment]
This test is failing again occasionally 😞so reopening the issue.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
