### ISSUE TITLE
[Metricbeat] Re-enable App Search module test

### ISSUE THREAD

**Issue by ioanatia** [elastic/beats#14057]
## Flaky Test

* **Test Name:** `test_appsearch.Test`
* **Link:** `x-pack/metricbeat/tests/system/test_appsearch.py`
* **Branch:** `ioanatia:ioanatia/app_search_metricset`
* **PR:** https://github.com/elastic/beats/pull/13738
* **Notes:** The test fails because the test takes too long to boot the containers. The integration test is skipped for now.

### Stack Trace

```
ERROR: test suite for <class 'test_appsearch.Test'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/go/src/github.com/elastic/beats/x-pack/metricbeat/tests/system/xpack_metricbeat.py", line 22, in setUpClass
    super(XPackTest, self).setUpClass()
  File "/go/src/github.com/elastic/beats/x-pack/metricbeat/tests/system/../../../../metricbeat/tests/system/metricbeat.py", line 28, in setUpClass
    super(BaseTest, self).setUpClass()
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/beat/beat.py", line 150, in setUpClass
    self.compose_up()
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/beat/compose.py", line 68, in compose_up
    stopped=True)
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/compose/project.py", line 680, in containers
    containers = self._labeled_containers(stopped, one_off)
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/compose/project.py", line 662, in _labeled_containers
    filters={'label': self.labels(one_off=one_off)})])
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/docker/api/container.py", line 208, in containers
    res = self._result(self._get(u, params=params), True)
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/docker/api/client.py", line 225, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/go/src/github.com/elastic/beats/build/ve/docker/local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
-------------------- >> begin captured stdout << ---------------------
Step 1/2 : FROM docker.elastic.co/app-search/app-search:7.4.0
 ---> f3aa27c97cb4
Step 2/2 : HEALTHCHECK --interval=1s --retries=300 --start-period=60s CMD python -c 'import urllib, json; response = urllib.urlopen("http://myelastic:changeme@localhost:3002/swiftype-app-version"); data = json.loads(response.read()); exit(0);'
 ---> Using cache
 ---> d528907fb37b
```

**Comment by jsoriano** [comment]
Closed by #15114
