### ISSUE TITLE
test_shutdown_wait_ok sometimes fails / filebeat fails to send all queued events on shutdown

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#14647]
I am not sure if this is a flaky test, or this is actually a problem in filebeat. `test_shutdown_wait_ok` fails sometimes, and from what I can see in the logs the problem is that it logs `Time out waiting for events being published.` instead of the expected `All enqueued events being published.`.

I tried to fix the test by increasing the timeout in https://github.com/elastic/beats/pull/14535 but I found that the issue continues happening. this is what makes me wonder if the issue is actually in filebeat.

## Flaky Test

* **Test Name:** `test_shutdown_wait_ok`
* **Link:** `filebeat/tests/system/test_shutdown.py`
* **Branch:** Many PRs and master, reproduced in https://github.com/elastic/beats/pull/14535
* **Notes:** Additional details about the test. e.g. theory as to failure cause

### Stack Trace

```
======================================================================
ERROR: Test stopping filebeat under load: wait for all events being published.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/go/src/github.com/elastic/beats/filebeat/tests/system/test_shutdown.py", line 57, in test_shutdown_wait_ok
    max_timeout=35)
  File "/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 387, in wait_log_contains
    name=name)
  File "/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 352, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'log_contains' to be true. Waited 35 seconds.
```

Filebeat shutdown logs when the issue happens, with filebeat configured with `shutdown_timeout: 30s` (from [this build](https://travis-ci.org/elastic/beats/jobs/614464307)):
```
2019-11-20T11:33:01.251Z	DEBUG	[service]	service/service.go:53	Received sigterm/sigint, stopping
2019-11-20T11:33:01.256Z	INFO	beater/filebeat.go:443	Stopping filebeat
2019-11-20T11:33:01.256Z	INFO	crawler/crawler.go:139	Stopping Crawler
2019-11-20T11:33:01.256Z	INFO	crawler/crawler.go:149	Stopping 1 inputs
2019-11-20T11:33:01.256Z	INFO	input/input.go:149	input ticker stopped
2019-11-20T11:33:01.256Z	INFO	input/input.go:167	Stopping Input: 13424228035328683901
2019-11-20T11:33:01.256Z	DEBUG	[harvester]	log/harvester.go:522	Stopping harvester for file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/log/nasa-50k.log
2019-11-20T11:33:01.256Z	DEBUG	[harvester]	log/harvester.go:532	Closing file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/log/nasa-50k.log
2019-11-20T11:33:01.256Z	DEBUG	[harvester]	log/harvester.go:406	Update state: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/log/nasa-50k.log, offset: 34221
2019-11-20T11:33:01.256Z	DEBUG	[harvester]	log/harvester.go:543	harvester cleanup finished for file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/log/nasa-50k.log
2019-11-20T11:33:01.256Z	DEBUG	[publisher]	pipeline/client.go:162	client: closing acker
2019-11-20T11:33:01.256Z	DEBUG	[publisher]	pipeline/client.go:173	client: done closing acker
2019-11-20T11:33:01.256Z	DEBUG	[publisher]	pipeline/client.go:176	client: cancelled 0 events
2019-11-20T11:33:01.256Z	DEBUG	[publisher]	pipeline/client.go:147	client: wait for acker to finish
2019-11-20T11:33:01.256Z	DEBUG	[publisher]	pipeline/client.go:149	client: acker shut down
2019-11-20T11:33:01.256Z	INFO	crawler/crawler.go:165	Crawler stopped
2019-11-20T11:33:01.256Z	INFO	beater/filebeat.go:430	Shutdown output timer started. Waiting for max 30s.
2019-11-20T11:33:01.256Z	DEBUG	[publisher]	pipeline/client.go:230	Pipeline client receives callback 'onDroppedOnPublish' for event: {Timestamp:2019-11-20 11:33:01.256125618 +0000 UTC m=+0.109060247 Meta:null Fields:{"agent":{"ephemeral_id":"96f792ea-e97f-47b6-be8e-56385810fc73","hostname":"fe10666ef11c","id":"000c62a2-42a3-4099-9477-9711f326b641","type":"filebeat","version":"8.0.0"},"ecs":{"version":"1.2.0"},"host":{"name":"fe10666ef11c"},"input":{"type":"log"},"log":{"file":{"path":"/go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/log/nasa-50k.log"},"offset":34120},"message":"199.166.39.14 - - [01/Jul/1995:00:05:18 -0400] \"GET /shuttle/countdown/count.gif HTTP/1.0\" 200 40310"} Private:{Id: Finished:false Fileinfo:0xc000217040 Source:/go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/log/nasa-50k.log Offset:34221 Timestamp:2019-11-20 11:33:01.200926763 +0000 UTC m=+0.053861394 TTL:-1ns Type:log Meta:map[] FileStateOS:1585350-2049} TimeSeries:false}
2019-11-20T11:33:01.256Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [25: 0, 8]
2019-11-20T11:33:01.256Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [26: 0, 8]
2019-11-20T11:33:01.256Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [27: 0, 8]
2019-11-20T11:33:01.256Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [28: 0, 8]
2019-11-20T11:33:01.256Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [29: 0, 8]
2019-11-20T11:33:01.257Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [30: 0, 8]
2019-11-20T11:33:01.257Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [31: 0, 8]
2019-11-20T11:33:01.257Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [32: 0, 8]
2019-11-20T11:33:01.257Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [33: 0, 8]
2019-11-20T11:33:01.257Z	DEBUG	[acker]	beater/acker.go:64	stateful ack	{"count": 24}
2019-11-20T11:33:01.257Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [34: 0, 8]
2019-11-20T11:33:01.257Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [35: 0, 8]
2019-11-20T11:33:01.258Z	DEBUG	[registrar]	registrar/registrar.go:404	Registry file updated. 1 states written.
2019-11-20T11:33:01.258Z	DEBUG	[registrar]	registrar/registrar.go:356	Processing 16 events
2019-11-20T11:33:01.258Z	DEBUG	[registrar]	registrar/registrar.go:326	Registrar state updates processed. Count: 16
2019-11-20T11:33:01.258Z	DEBUG	[registrar]	registrar/registrar.go:411	Write registry file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/registry/filebeat/data.json (1)
2019-11-20T11:33:01.259Z	DEBUG	[publisher]	memqueue/eventloop.go:535	broker ACK events: count=88, start-seq=201, end-seq=288
2019-11-20T11:33:01.259Z	DEBUG	[publisher]	memqueue/ackloop.go:128	ackloop: return ack to broker loop:88
2019-11-20T11:33:01.259Z	DEBUG	[publisher]	memqueue/ackloop.go:131	ackloop:  done send ack
2019-11-20T11:33:01.259Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [36: 0, 8]
2019-11-20T11:33:01.259Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [37: 0, 8]
2019-11-20T11:33:01.259Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [38: 0, 8]
2019-11-20T11:33:01.259Z	DEBUG	[acker]	beater/acker.go:64	stateful ack	{"count": 88}
2019-11-20T11:33:01.264Z	DEBUG	[registrar]	registrar/registrar.go:404	Registry file updated. 1 states written.
2019-11-20T11:33:01.264Z	DEBUG	[registrar]	registrar/registrar.go:356	Processing 24 events
2019-11-20T11:33:01.264Z	DEBUG	[registrar]	registrar/registrar.go:326	Registrar state updates processed. Count: 24
2019-11-20T11:33:01.264Z	DEBUG	[registrar]	registrar/registrar.go:411	Write registry file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/registry/filebeat/data.json (1)
2019-11-20T11:33:01.264Z	DEBUG	[publisher]	memqueue/eventloop.go:535	broker ACK events: count=24, start-seq=289, end-seq=312
2019-11-20T11:33:01.264Z	DEBUG	[publisher]	memqueue/ackloop.go:128	ackloop: return ack to broker loop:24
2019-11-20T11:33:01.264Z	DEBUG	[publisher]	memqueue/ackloop.go:131	ackloop:  done send ack
2019-11-20T11:33:01.264Z	DEBUG	[acker]	beater/acker.go:64	stateful ack	{"count": 24}
2019-11-20T11:33:01.268Z	DEBUG	[registrar]	registrar/registrar.go:404	Registry file updated. 1 states written.
2019-11-20T11:33:01.268Z	DEBUG	[registrar]	registrar/registrar.go:356	Processing 88 events
2019-11-20T11:33:01.268Z	DEBUG	[registrar]	registrar/registrar.go:326	Registrar state updates processed. Count: 88
2019-11-20T11:33:01.268Z	DEBUG	[registrar]	registrar/registrar.go:411	Write registry file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/registry/filebeat/data.json (1)
2019-11-20T11:33:01.273Z	DEBUG	[registrar]	registrar/registrar.go:404	Registry file updated. 1 states written.
2019-11-20T11:33:01.273Z	DEBUG	[registrar]	registrar/registrar.go:356	Processing 24 events
2019-11-20T11:33:01.273Z	DEBUG	[registrar]	registrar/registrar.go:326	Registrar state updates processed. Count: 24
2019-11-20T11:33:01.273Z	DEBUG	[registrar]	registrar/registrar.go:411	Write registry file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/registry/filebeat/data.json (1)
2019-11-20T11:33:01.276Z	DEBUG	[registrar]	registrar/registrar.go:404	Registry file updated. 1 states written.
2019-11-20T11:33:01.357Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [39: 0, 2]
2019-11-20T11:33:01.357Z	DEBUG	[publisher]	memqueue/eventloop.go:535	broker ACK events: count=2, start-seq=313, end-seq=314
2019-11-20T11:33:01.357Z	DEBUG	[publisher]	memqueue/ackloop.go:128	ackloop: return ack to broker loop:2
2019-11-20T11:33:01.357Z	DEBUG	[publisher]	memqueue/ackloop.go:131	ackloop:  done send ack
2019-11-20T11:33:01.357Z	DEBUG	[acker]	beater/acker.go:64	stateful ack	{"count": 2}
2019-11-20T11:33:01.357Z	DEBUG	[registrar]	registrar/registrar.go:356	Processing 2 events
2019-11-20T11:33:01.357Z	DEBUG	[registrar]	registrar/registrar.go:326	Registrar state updates processed. Count: 2
2019-11-20T11:33:01.357Z	DEBUG	[registrar]	registrar/registrar.go:411	Write registry file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/registry/filebeat/data.json (1)
2019-11-20T11:33:01.362Z	DEBUG	[registrar]	registrar/registrar.go:404	Registry file updated. 1 states written.
2019-11-20T11:33:31.196Z	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":20,"time":{"ms":20}},"total":{"ticks":80,"time":{"ms":88},"value":80},"user":{"ticks":60,"time":{"ms":68}}},"handles":{"limit":{"hard":1048576,"soft":524288},"open":77},"info":{"ephemeral_id":"96f792ea-e97f-47b6-be8e-56385810fc73","uptime":{"ms":30044}},"memstats":{"gc_next":6571520,"memory_alloc":4207496,"memory_total":10012088,"rss":44535808},"runtime":{"goroutines":15}},"filebeat":{"events":{"active":1,"added":316,"done":315},"harvester":{"closed":1,"open_files":0,"running":0,"started":1}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":314,"batches":40,"total":314},"type":"file","write":{"bytes":201690}},"pipeline":{"clients":0,"events":{"active":0,"failed":1,"filtered":1,"published":314,"total":316},"queue":{"acked":314}}},"registrar":{"states":{"current":1,"update":315},"writes":{"success":11,"total":11}},"system":{"cpu":{"cores":2},"load":{"1":3.02,"15":3.3,"5":4.51,"norm":{"1":1.51,"15":1.65,"5":2.255}}}}}}
2019-11-20T11:33:31.256Z	INFO	beater/signalwait.go:93	Continue shutdown: Time out waiting for events being published.
2019-11-20T11:33:31.256Z	INFO	registrar/registrar.go:367	Stopping Registrar
2019-11-20T11:33:31.256Z	INFO	registrar/registrar.go:293	Ending Registrar
2019-11-20T11:33:31.256Z	DEBUG	[registrar]	registrar/registrar.go:411	Write registry file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/registry/filebeat/data.json (1)
2019-11-20T11:33:31.261Z	DEBUG	[registrar]	registrar/registrar.go:404	Registry file updated. 1 states written.
2019-11-20T11:33:31.263Z	INFO	[monitoring]	log/log.go:153	Total non-zero metrics	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":20,"time":{"ms":20}},"total":{"ticks":90,"time":{"ms":92},"value":90},"user":{"ticks":70,"time":{"ms":72}}},"handles":{"limit":{"hard":1048576,"soft":524288},"open":77},"info":{"ephemeral_id":"96f792ea-e97f-47b6-be8e-56385810fc73","uptime":{"ms":30111}},"memstats":{"gc_next":6571520,"memory_alloc":4571032,"memory_total":10375624,"rss":44535808},"runtime":{"goroutines":13}},"filebeat":{"events":{"active":1,"added":316,"done":315},"harvester":{"closed":1,"open_files":0,"running":0,"started":1}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":314,"batches":40,"total":314},"type":"file","write":{"bytes":201690}},"pipeline":{"clients":0,"events":{"active":0,"failed":1,"filtered":1,"published":314,"total":316},"queue":{"acked":314}}},"registrar":{"states":{"current":1,"update":315},"writes":{"success":12,"total":12}},"system":{"cpu":{"cores":2},"load":{"1":3.02,"15":3.3,"5":4.51,"norm":{"1":1.51,"15":1.65,"5":2.255}}}}}}
2019-11-20T11:33:31.263Z	INFO	[monitoring]	log/log.go:154	Uptime: 30.113398554s
2019-11-20T11:33:31.263Z	INFO	[monitoring]	log/log.go:131	Stopping metrics logging.
2019-11-20T11:33:31.263Z	INFO	instance/beat.go:444	filebeat stopped.
```

**Comment by exekias** [comment]
@urso what do you think about this one? could be a regression

**Comment by urso** [comment]
Filebeat keeps a counter on published events. Shutdown blocks until counter becomes there or the `shutdown_timeout` kicks in.

Metrics say: `"filebeat":{"events":{"active":1,"added":316,"done":315}`
Yet we have: `"pipeline":{"clients":0,"events":{"active":0,"failed":1,"filtered":1,"published":314,"total":316},"queue":{"acked":314}}}`.
The filtered and ACKed events seem to be forwarded to the registrar: `"registrar":{"states":{"current":1,"update":315},`

It could be related to this line:
`2019-11-20T11:33:01.256Z	DEBUG	[publisher]	pipeline/client.go:230	Pipeline client receives callback 'onDroppedOnPublish' for event: {Timestamp:2019-11-20 11:33:01.256125618 +0000 UTC m=+0.109060247 Meta:null Fields:{"agent":{"ephemeral_id":"96f792ea-e97f-47b6-be8e-56385810fc73","hostname":"fe10666ef11c","id":"000c62a2-42a3-4099-9477-9711f326b641","type":"filebeat","version":"8.0.0"},"ecs":{"version":"1.2.0"},"host":{"name":"fe10666ef11c"},"input":{"type":"log"},"log":{"file":{"path":"/go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/log/nasa-50k.log"},"offset":34120},"message":"199.166.39.14 - - [01/Jul/1995:00:05:18 -0400] \"GET /shuttle/countdown/count.gif HTTP/1.0\" 200 40310"} Private:{Id: Finished:false Fileinfo:0xc000217040 Source:/go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_shutdown.Test.test_shutdown_wait_ok/log/nasa-50k.log Offset:34221 Timestamp:2019-11-20 11:33:01.200926763 +0000 UTC m=+0.053861394 TTL:-1ns Type:log Meta:map[] FileStateOS:1585350-2049} TimeSeries:false}`

The publisher pipeline can cancel events on shutdown. Makes me wonder if the global counter in filebeat is wrong in this case.

The publisher pipeline itself is aware of active events and supports wait-shutdown directly. Unfortunately we can't use this in filebeat yet. In the future we will use the wait functionality from the pipeline.

**Comment by faec** [comment]
With the main changes in https://github.com/elastic/beats/pull/49482, this test no longer hits flakiness related to acknowledgments never completing, however it does hit failures _after_ that check when it [confirms the ingested offset in the registry](https://github.com/elastic/beats/blob/18aea77d9d31c01ec5477789c3ba3506ed9bed11/filebeat/tests/system/test_shutdown.py#L83). This test code has been unused for a long time and I haven't found solid evidence that the failures are real, but I haven't found a bug in the test either, so we should fix and reenable or else replace this test as part of https://github.com/elastic/beats/issues/49679.
