### ISSUE TITLE
`make update` requires manually installing `six` & `PyYaml`

### ISSUE THREAD

**Issue by Brian-Williams** [elastic/beats#14922]
**Describe the enhancement:**
Install dependencies for `auditbeat/scripts/docs_collector.py` in the `update` target. The required deps are `six` and `PyYaml`.

For me the target requires installing in the venv and rerunning `<path>/go/src/github.com/elastic/beats/build/ve/darwin/bin/pip install six PyYaml`.

```
$ VIRTUALENV_PARAMS="-p python2.7" make update
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Generating NOTICE
Get the licenses available from ['./vendor', './metricbeat/module/postgresql/vendor', './metricbeat/module/vsphere/vendor', './metricbeat/module/kvm/vendor', './metricbeat/module/mysql/vendor']
WARNING: No version information found for: gopkg.in/goracle.v2/odpi
WARNING: No version information found for: github.com/go-ini/ini
WARNING: No version information found for: github.com/prometheus/client_model
Available at /Users/admin/go/src/github.com/elastic/beats/NOTICE.txt
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /Users/admin/go/src/github.com/elastic/beats/libbeat/build/python-env/bin/python
Installing setuptools, pip, wheel...
done.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
2019/12/03 14:50:28 Found Elastic Beats dir at /Users/admin/go/src/github.com/elastic/beats
Generated fields.yml for libbeat to /Users/admin/go/src/github.com/elastic/beats/libbeat/fields.yml
2019/12/03 14:50:30 Found Elastic Beats dir at /Users/admin/go/src/github.com/elastic/beats
>> Building libbeat.yml for linux/amd64
>> Building libbeat.reference.yml for linux/amd64
Updating generated files for libbeat
if [ -d /Users/admin/go/src/github.com/elastic/beats/libbeat/_meta/kibana ]; then \
                cp -pr /Users/admin/go/src/github.com/elastic/beats/libbeat/_meta/kibana/* /Users/admin/go/src/github.com/elastic/beats/libbeat/_meta/kibana.generated ; \
        fi
mage update
2019/12/03 14:50:33 Found Elastic Beats dir at /Users/admin/go/src/github.com/elastic/beats
Generated fields.yml for auditbeat to /Users/admin/go/src/github.com/elastic/beats/auditbeat/fields.yml
Generated fields.yml for auditbeat to /Users/admin/go/src/github.com/elastic/beats/auditbeat/fields.yml
>> Building auditbeat.yml for linux/amd64
>> Building auditbeat.reference.yml for linux/amd64
>> Building auditbeat.docker.yml for linux/amd64
2019/12/03 14:50:36 Found Elastic Beats dir at /Users/admin/go/src/github.com/elastic/beats
Traceback (most recent call last):
  File "/Users/admin/go/src/github.com/elastic/beats/auditbeat/scripts/docs_collector.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Generated fields.yml for auditbeat to /Users/admin/go/src/github.com/elastic/beats/auditbeat/build/fields/fields.all.yml
Traceback (most recent call last):
  File "/Users/admin/go/src/github.com/elastic/beats/libbeat/scripts/generate_fields_docs.py", line 5, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Error: running "/Users/admin/go/src/github.com/elastic/beats/build/ve/darwin/bin/python /Users/admin/go/src/github.com/elastic/beats/auditbeat/scripts/docs_collector.py --base-paths /Users/admin/go/src/github.com/elastic/beats/auditbeat /Users/admin/go/src/github.com/elastic/beats/x-pack/auditbeat" failed with exit code 1
running "/Users/admin/go/src/github.com/elastic/beats/build/ve/darwin/bin/python /Users/admin/go/src/github.com/elastic/beats/libbeat/scripts/generate_fields_docs.py build/fields/fields.all.yml auditbeat /Users/admin/go/src/github.com/elastic/beats --output_path /Users/admin/go/src/github.com/elastic/beats/auditbeat" failed with exit code 1
make[1]: *** [update] Error 1
make: *** [update] Error 1
```

**Describe a specific use case for the enhancement or feature:**
Remove a manual update step.

**Comment by jsoriano** [comment]
Hey @Brian-Williams,

Thanks for reporting. We have migrated our python tests and scripts to Python 3 (https://github.com/elastic/beats/pull/14798), so this shouldn't be needed anymore.
I am closing this issue by now, it'd be great if you could test again with current master.
