### ISSUE TITLE
Flaky test around filtering

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1517]
We occasionally get flaky test, usually in `test_filtering.py` from topbeat with a python stack trace like this:

```
ERROR: Check include_fields filtering action

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/gopath/src/github.com/elastic/beats/topbeat/tests/system/test_filtering.py", line 60, in test_include_fields

    required_fields=["@timestamp", "type"],

  File "../../../libbeat/tests/system/beat/beat.py", line 204, in read_output

    jsons.append(self.flatten_object(json.loads(line), []))

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads

    return _default_decoder.decode(s)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 381, in raw_decode

    obj, end = self.scan_once(s, idx)

ValueError: Invalid control character at: line 1 column 38 (char 37)

-------------------- >> begin captured stdout << ---------------------

Fail to load the json {"@timestamp":"2016-04-25T11:31:51.94           
 

```

This is for investigating it and fixing it.

**Comment by tsg** [comment]
It didn't happen when running it on a loop on my computer (yet), but here is what I suspect:

* The test waits until the output has at least 1 line
* It then calls `read_output` which reads the full file and tries to decode the JSON line by line
* In parallel, topbeat keeps adding new lines
* It is possible that the python process reads a line that's not complete yet (like it looks like in the above)
* Tries to json decode the incomplete line and 💥

To solve it, I'm thinking to check if the line ands with `\n` before attempting to JSON decode it.
