### ISSUE TITLE
Heartbeat Testsuite failing

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#15202]
Go: $TRAVIS_GO_VERSION
AMD64
TARGETS="TEST_ENVIRONMENT=0 -C heartbeat testsuite"

Here is the test output:

```
ERROR
Test a reload of a config ... 127.0.0.1 - - [18/Dec/2019 23:20:19] "GET / HTTP/1.1" 200 -
ok (6.9113s)
Test the removal of a dynamic config ... 127.0.0.1 - - [18/Dec/2019 23:20:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2019 23:20:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2019 23:20:28] "GET / HTTP/1.1" 200 -
ok (3.7844s)
Test that telemetry metrics are correctly registered and increment / decrement ... SKIP
======================================================================
ERROR: Basic test with fields and tags in monitor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/gopath/src/github.com/elastic/beats/heartbeat/tests/system/test_base.py", line 59, in test_fields_under_root
    "env": "dev"
  File "/Users/travis/gopath/src/github.com/elastic/beats/heartbeat/tests/system/test_base.py", line 133, in run_fields
    self.wait_until(lambda: self.output_lines() > 0)
  File "/Users/travis/gopath/src/github.com/elastic/beats/heartbeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 352, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
======================================================================
ERROR: Test the addition of a dynamic config
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/gopath/src/github.com/elastic/beats/heartbeat/tests/system/test_reload.py", line 83, in test_config_add
    self.wait_until(lambda: self.output_has(lines=1))
  File "/Users/travis/gopath/src/github.com/elastic/beats/heartbeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 352, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
----------------------------------------------------------------------
XML: /Users/travis/gopath/src/github.com/elastic/beats/heartbeat/build/TEST-system.xml
[error] 30.84% test_base.Test.test_fields_under_root: 20.1690s
[error] 20.69% test_reload.Test.test_config_add: 13.5306s
```

Didn't investigate it deeper, definitely a flaky test.

**Comment by mtojek** [comment]
Also:

```
Test that telemetry metrics are correctly registered and increment / decrement ... SKIP
======================================================================
FAIL: Test JSON response checks [with expected_status='down', body='{"foo": "unexpected"}']
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/gopath/src/github.com/elastic/beats/heartbeat/build/python-env/lib/python2.7/site-packages/parameterized/parameterized.py", line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/Users/travis/gopath/src/github.com/elastic/beats/heartbeat/tests/system/test_monitor.py", line 124, in test_http_json
    proc.check_kill_and_wait()
  File "/Users/travis/gopath/src/github.com/elastic/beats/heartbeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 104, in check_kill_and_wait
    return self.check_wait(exit_code=exit_code)
  File "/Users/travis/gopath/src/github.com/elastic/beats/heartbeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 93, in check_wait
    exit_code, actual_exit_code)
AssertionError: Expected exit code to be 0, but it was -15
----------------------------------------------------------------------
XML: /Users/travis/gopath/src/github.com/elastic/beats/heartbeat/build/TEST-system.xml
[fail] 38.20% test_monitor.Test.test_http_json_1_down: 20.2185s
```

**Comment by mtojek** [comment]
1. Error `AssertionError: Expected exit code to be 0, but it was -15` is most likely due to out of memory.
2. Fix error in `Test the addition of a dynamic config`: https://github.com/elastic/beats/pull/15233

**Comment by mtojek** [comment]
Resolving now.
