### ISSUE TITLE
filebeat 7.4.0 not work well by kafka input

### ISSUE THREAD

**Issue by listen-lavender** [elastic/beats#15263]
**filebeat config:** 

```
- type: kafka
  hosts: ["127.0.0.1:9092"]
  topics: ["test-weblog"]
  group_id: "test-weblog-batch"
  username: "consumer"
  password: "123"
  ssl.enabled: true
  version: "1.0.0"
  fetch:
    max: 524288
    default: 524288
    min: 524288
```

**filebeat error log:**

`Error initializing kafka consumer group	{"hosts": ["127.0.0.1:9092"], "error": "kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"`

**kafka error log:**

```
[2019-12-28 09:17:47,639] WARN [SocketServer brokerId=1] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369295616 larger than 524288)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:237)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:132)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:532)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kvch** [comment]
Could you please post a question on Discuss and if a dev verified that it's a bug, open an issue here? https://discuss.elastic.co
