### ISSUE TITLE
filebeat to logstash:  Failed to publish events caused by: read tcp 192.168.155.177:55376->47.102.46.68:5045:wsarecv:An existing connection was forcibly closed by the remote host 

### ISSUE THREAD

**Issue by cheninnocent** [elastic/beats#15313]
computer A is ok.
computer B is failed when log is to much.
filebeat log
![企业微信截图_15780165168763](https://user-images.githubusercontent.com/26034307/71703521-f18a9600-2e0f-11ea-8614-59f7648fdd07.png)
filebeat to logstash: Failed to publish events caused by: read tcp 192.168.155.177:55376->47.102.46.68:5045:wsarecv:An existing connection was forcibly closed by the remote host
faliled to publish events caused by:client is not connected

wireshark
![企业微信截图_157801654122](https://user-images.githubusercontent.com/26034307/71703532-09fab080-2e10-11ea-98b8-913145a51593.png)

**Comment by cheninnocent** [comment]
logstash-plain.
[logstash-plain.log](https://github.com/elastic/beats/files/4017924/logstash-plain.log)
log
[2020-01-03T09:45:53,841][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 140.207.6.158:57306] Handling exception: Connection reset by peer
[2020-01-03T09:45:53,843][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_232]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_232]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_232]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_232]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_232]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by andrewkroh** [comment]
Your Wireshark output shows the Logstash is resetting the connection with a RST/ACK packet. There is probably an issue in your Logstash setup or config. Try enabling some debug in Logstash, looking at Logstash's metrics, and/or commenting out your filters plus temporarily switching to the Logstash console output to narrow down the cause.

Please post any future discussions to https://discuss.elastic.co. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can open a new issue.
