### ISSUE TITLE
Flaky test_monitoring.Test

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#16247]
## Flaky Test

* **Test Name:** test_monitoring.Test.*
* **Link:** https://github.com/elastic/beats/blob/feature/python3/libbeat/tests/system/test_monitoring.py#L95
* **Branch:** Seen frequently failing in Python 3 branch (https://github.com/elastic/beats/pull/14798), e.g. in [this build]( https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/6230/beat=libbeat,label=linux-immutable/) all monitoring tests fail.
* **Notes:** Skip in https://github.com/elastic/beats/pull/16248

### Stack Trace

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/test_monitoring.py", line 120, in test_compare
    self.wait_until(lambda: self.monitoring_doc_exists('beats_stats'))
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/beat/beat.py", line 349, in wait_until
    while not cond():
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/test_monitoring.py", line 120, in <lambda>
    self.wait_until(lambda: self.monitoring_doc_exists('beats_stats'))
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/test_monitoring.py", line 188, in monitoring_doc_exists
    hits = self.search_monitoring_doc(monitoring_type)
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/test_monitoring.py", line 183, in search_monitoring_doc
    size=1
  File "/tmp/python-env/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/tmp/python-env/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 811, in search
    "GET", _make_path(index, "_search"), params=params, body=body
  File "/tmp/python-env/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/tmp/python-env/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/tmp/python-env/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(503, 'search_phase_execution_exception')
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/test_monitoring.py", line 84, in test_direct_to_monitoring_cluster
    self.wait_until(lambda: self.monitoring_doc_exists('beats_stats'))
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/beat/beat.py", line 349, in wait_until
    while not cond():
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/test_monitoring.py", line 84, in <lambda>
    self.wait_until(lambda: self.monitoring_doc_exists('beats_stats'))
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/test_monitoring.py", line 188, in monitoring_doc_exists
    hits = self.search_monitoring_doc(monitoring_type)
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/test_monitoring.py", line 183, in search_monitoring_doc
    size=1
  File "/tmp/python-env/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/tmp/python-env/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 811, in search
    "GET", _make_path(index, "_search"), params=params, body=body
  File "/tmp/python-env/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/tmp/python-env/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/tmp/python-env/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(503, 'search_phase_execution_exception')
```

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.

**Comment by cmacknz** [comment]
It has been disabled for 2 years so we may as well remove it.
