### ISSUE TITLE
Flaky Test in redisenterprise module node_integration_test.go and proxy_integration_test.go

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#16718]
## Flaky Test

* **Test Name:**  node_integration_test.go and proxy_integration_test.go
* **Link:** https://travis-ci.org/elastic/beats/jobs/656282905#L2062
* **Branch:** master
* **Notes:** I think these two tests have been failing every time. 

### Stack Trace

```
--- FAIL: TestFetch (90.06s)
    node_integration_test.go:37: 
        	Error Trace:	node_integration_test.go:37
        	Error:      	Should NOT be empty, but was []
        	Test:       	TestFetch
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
goroutine 21 [running]:
testing.tRunner.func1(0xc0000f9800)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0xdbe480, 0xc0000c3720)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/elastic/beats/x-pack/metricbeat/module/redisenterprise/node.TestFetch(0xc0000f9800)
	/go/src/github.com/elastic/beats/x-pack/metricbeat/module/redisenterprise/node/node_integration_test.go:38 +0x6fc
testing.tRunner(0xc0000f9800, 0xe3fda0)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
FAIL	github.com/elastic/beats/x-pack/metricbeat/module/redisenterprise/node	90.070s
=== RUN   TestFetch
--- FAIL: TestFetch (91.20s)
    proxy_integration_test.go:37: 
        	Error Trace:	proxy_integration_test.go:37
        	Error:      	Should NOT be empty, but was []
        	Test:       	TestFetch
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
goroutine 21 [running]:
testing.tRunner.func1(0xc0000f9800)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0xdbe480, 0xc0000c27e0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/elastic/beats/x-pack/metricbeat/module/redisenterprise/proxy.TestFetch(0xc0000f9800)
	/go/src/github.com/elastic/beats/x-pack/metricbeat/module/redisenterprise/proxy/proxy_integration_test.go:38 +0x6fc
testing.tRunner(0xc0000f9800, 0xe3fda8)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
FAIL	github.com/elastic/beats/x-pack/metricbeat/module/redisenterprise/proxy	91.209s
FAIL
FAILURES:
Package: github.com/elastic/beats/x-pack/metricbeat/module/redisenterprise/node
Test:    TestFetch
Error Trace:	proxy_integration_test.go:37
panic: runtime error: index out of range [0] with length 0 [recovered]
goroutine 21 [running]:
/usr/local/go/src/testing/testing.go:874 +0x3a3
/usr/local/go/src/runtime/panic.go:679 +0x1b2
/go/src/github.com/elastic/beats/x-pack/metricbeat/module/redisenterprise/proxy/proxy_integration_test.go:38 +0x6fc
/usr/local/go/src/testing/testing.go:909 +0xc9
/usr/local/go/src/testing/testing.go:960 +0x350
Step 3/4 : ADD healthcheck.sh /
 ---> 3121d8398b1f
Step 4/4 : HEALTHCHECK --interval=1s --retries=300 CMD /healthcheck.sh
 ---> Running in a46fe4dca803
 ---> 1e9a549de83a
Removing intermediate container a46fe4dca803
Successfully built 1e9a549de83a
Successfully tagged docker.elastic.co/integrations-ci/beats-redisenterprise:5.4.10-22-3
Image for service redisenterprise was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating metricbeat_8_0_0_128c38dc2f-snapshot_redisenterprise_1 ... 
Creating metricbeat_8_0_0_128c38dc2f-snapshot_redisenterprise_1 ... done
Error Trace:	node_integration_test.go:37
panic: runtime error: index out of range [0] with length 0 [recovered]
goroutine 21 [running]:
/usr/local/go/src/testing/testing.go:874 +0x3a3
/usr/local/go/src/runtime/panic.go:679 +0x1b2
/go/src/github.com/elastic/beats/x-pack/metricbeat/module/redisenterprise/node/node_integration_test.go:38 +0x6fc
/usr/local/go/src/testing/testing.go:909 +0xc9
/usr/local/go/src/testing/testing.go:960 +0x350
----
Package: github.com/elastic/beats/x-pack/metricbeat/module/redisenterprise/proxy
Test:    TestFetch
Error Trace:	proxy_integration_test.go:37
panic: runtime error: index out of range [0] with length 0 [recovered]
goroutine 21 [running]:
/usr/local/go/src/testing/testing.go:874 +0x3a3
/usr/local/go/src/runtime/panic.go:679 +0x1b2
/go/src/github.com/elastic/beats/x-pack/metricbeat/module/redisenterprise/proxy/proxy_integration_test.go:38 +0x6fc
/usr/local/go/src/testing/testing.go:909 +0xc9
/usr/local/go/src/testing/testing.go:960 +0x350
----
```

**Comment by mtojek** [comment]
Resolving.
