### ISSUE TITLE
[Agent] Concurrency issue in fleet gateway

### ISSUE THREAD

**Issue by ph** [elastic/beats#16771]
Found with #16494 

````
2020-03-03T18:38:39Z INFO	fleet_gateway.go:213	Fleet gateway is stopping

coverage: 30.1% of statements

panic: test timed out after 10m0s

goroutine 136 [running]:

testing.(*M).startAlarm.func1()

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/testing/testing.go:1377 +0x11c

created by time.goFunc

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/time/sleep.go:168 +0x52

goroutine 1 [chan receive, 9 minutes]:

testing.(*T).Run(0xc0000fe700, 0x1c1e872, 0x10, 0x1c46470, 0x1)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/testing/testing.go:961 +0x68a

testing.runTests.func1(0xc0000fe700)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/testing/testing.go:1202 +0xa7

testing.tRunner(0xc0000fe700, 0xc0000d7cd8)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/testing/testing.go:909 +0x19a

testing.runTests(0xc00018ce40, 0x236d780, 0xd, 0xd, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/testing/testing.go:1200 +0x522

testing.(*M).Run(0xc0000cec80, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/testing/testing.go:1117 +0x300

main.main()

	_testmain.go:162 +0x338

goroutine 81 [chan receive, 9 minutes]:

github.com/elastic/beats/v7/x-pack/agent/pkg/agent/application.TestAcker.func2(0xc000046de0)

	/Users/travis/gopath/src/github.com/elastic/beats/x-pack/agent/pkg/agent/application/fleet_acker_test.go:56 +0x45

created by github.com/elastic/beats/v7/x-pack/agent/pkg/agent/application.TestAcker

	/Users/travis/gopath/src/github.com/elastic/beats/x-pack/agent/pkg/agent/application/fleet_acker_test.go:55 +0x2e2

goroutine 132 [semacquire, 9 minutes]:

sync.runtime_Semacquire(0xc0000b55e0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/runtime/sema.go:56 +0x42

sync.(*WaitGroup).Wait(0xc0000b55d8)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/sync/waitgroup.go:130 +0xb1

github.com/elastic/beats/v7/x-pack/agent/pkg/agent/application.(*fleetGateway).Stop(0xc0000b5550)

	/Users/travis/gopath/src/github.com/elastic/beats/x-pack/agent/pkg/agent/application/fleet_gateway.go:216 +0x156

github.com/elastic/beats/v7/x-pack/agent/pkg/agent/application.TestFleetGateway.func5(0xc0000ffc00)

	/Users/travis/gopath/src/github.com/elastic/beats/x-pack/agent/pkg/agent/application/fleet_gateway_test.go:342 +0x579

testing.tRunner(0xc0000ffc00, 0xc00021f740)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/testing/testing.go:909 +0x19a

created by testing.(*T).Run

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/testing/testing.go:960 +0x652

goroutine 78 [IO wait, 9 minutes]:

internal/poll.runtime_pollWait(0x3c36868, 0x72, 0x1d3cb80)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/runtime/netpoll.go:184 +0x55

internal/poll.(*pollDesc).wait(0xc0002c2818, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/internal/poll/fd_poll_runtime.go:87 +0xe4

internal/poll.(*pollDesc).waitRead(...)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/internal/poll/fd_poll_runtime.go:92

internal/poll.(*FD).Read(0xc0002c2800, 0xc000148000, 0x1000, 0x1000, 0x0, 0x0, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/internal/poll/fd_unix.go:169 +0x36a

net.(*netFD).Read(0xc0002c2800, 0xc000148000, 0x1000, 0x1000, 0xc0000b4420, 0xc00006e920, 0x10448cc)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/fd_unix.go:202 +0x66

net.(*conn).Read(0xc0000100c0, 0xc000148000, 0x1000, 0x1000, 0xc00006e920, 0x104d010, 0xc00021e540)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/net.go:184 +0xa1

net/http.(*persistConn).Read(0xc0004af0e0, 0xc000148000, 0x1000, 0x1000, 0x0, 0xf3c, 0x1)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/http/transport.go:1758 +0xe8

bufio.(*Reader).fill(0xc000085860)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/bufio/bufio.go:100 +0x19a

bufio.(*Reader).Peek(0xc000085860, 0x1, 0x0, 0x0, 0x1, 0xc000046800, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/bufio/bufio.go:138 +0xa0

net/http.(*persistConn).readLoop(0xc0004af0e0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/http/transport.go:1911 +0x2af

created by net/http.(*Transport).dialConn

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/http/transport.go:1580 +0xbe2

goroutine 134 [semacquire, 9 minutes]:

sync.runtime_SemacquireMutex(0xc0002a97e4, 0x900000000, 0x1)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/runtime/sema.go:71 +0x47

sync.(*Mutex).lockSlow(0xc0002a97e0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/sync/mutex.go:138 +0x1c1

sync.(*Mutex).Lock(0xc0002a97e0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/sync/mutex.go:81 +0x7d

github.com/elastic/beats/v7/x-pack/agent/pkg/agent/application.(*testingDispatcher).Answer(0xc0002a97e0, 0x1c46458, 0x0)

	/Users/travis/gopath/src/github.com/elastic/beats/x-pack/agent/pkg/agent/application/fleet_gateway_test.go:82 +0x48

github.com/elastic/beats/v7/x-pack/agent/pkg/agent/application.TestFleetGateway.func5.1(0xc0002a97e0)

	/Users/travis/gopath/src/github.com/elastic/beats/x-pack/agent/pkg/agent/application/fleet_gateway_test.go:332 +0x45

created by github.com/elastic/beats/v7/x-pack/agent/pkg/agent/application.TestFleetGateway.func5

	/Users/travis/gopath/src/github.com/elastic/beats/x-pack/agent/pkg/agent/application/fleet_gateway_test.go:332 +0x544

goroutine 45 [IO wait, 9 minutes]:

internal/poll.runtime_pollWait(0x3c36ee8, 0x72, 0x1d3cb80)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/runtime/netpoll.go:184 +0x55

internal/poll.(*pollDesc).wait(0xc0000ce618, 0x72, 0x700, 0x7d2, 0xffffffffffffffff)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/internal/poll/fd_poll_runtime.go:87 +0xe4

internal/poll.(*pollDesc).waitRead(...)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/internal/poll/fd_poll_runtime.go:92

internal/poll.(*FD).Read(0xc0000ce600, 0xc0002e6800, 0x7d2, 0x7d2, 0x0, 0x0, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/internal/poll/fd_unix.go:169 +0x36a

net.(*netFD).Read(0xc0000ce600, 0xc0002e6800, 0x7d2, 0x7d2, 0xc0002e6805, 0x298, 0x7cd)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/fd_unix.go:202 +0x66

net.(*conn).Read(0xc0002a60b0, 0xc0002e6800, 0x7d2, 0x7d2, 0x117d9d3, 0xc0000f0258, 0xc0000ab470)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/net.go:184 +0xa1

crypto/tls.(*atLeastReader).Read(0xc0002dac40, 0xc0002e6800, 0x7d2, 0x7d2, 0xc0002dac40, 0x7cd, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/crypto/tls/conn.go:780 +0xa7

bytes.(*Buffer).ReadFrom(0xc0000f0258, 0x1d3a1a0, 0xc0002dac40, 0x1bdab80, 0x3c6e138, 0xc0002e6805)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/bytes/buffer.go:204 +0x159

crypto/tls.(*Conn).readFromUntil(0xc0000f0000, 0x3c6e138, 0xc0002a60b0, 0x5, 0xc0002a60b0, 0x287)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/crypto/tls/conn.go:802 +0x210

crypto/tls.(*Conn).readRecordOrCCS(0xc0000f0000, 0x0, 0x0, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/crypto/tls/conn.go:609 +0x2e1

crypto/tls.(*Conn).readRecord(...)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/crypto/tls/conn.go:577

crypto/tls.(*Conn).Read(0xc0000f0000, 0xc000302000, 0x1000, 0x1000, 0x0, 0x0, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/crypto/tls/conn.go:1255 +0x20c

net/http.(*persistConn).Read(0xc0000e30e0, 0xc000302000, 0x1000, 0x1000, 0x0, 0xd79, 0x1)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/http/transport.go:1758 +0xe8

bufio.(*Reader).fill(0xc0002e8e40)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/bufio/bufio.go:100 +0x19a

bufio.(*Reader).Peek(0xc0002e8e40, 0x1, 0x0, 0x0, 0x1, 0xc000046100, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/bufio/bufio.go:138 +0xa0

net/http.(*persistConn).readLoop(0xc0000e30e0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/http/transport.go:1911 +0x2af

created by net/http.(*Transport).dialConn

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/http/transport.go:1580 +0xbe2

goroutine 26 [IO wait, 9 minutes]:

internal/poll.runtime_pollWait(0x3c36e18, 0x72, 0x1d3cb80)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/runtime/netpoll.go:184 +0x55

internal/poll.(*pollDesc).wait(0xc0002c2018, 0x72, 0x200, 0x205, 0xffffffffffffffff)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/internal/poll/fd_poll_runtime.go:87 +0xe4

internal/poll.(*pollDesc).waitRead(...)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/internal/poll/fd_poll_runtime.go:92

internal/poll.(*FD).Read(0xc0002c2000, 0xc0002ce000, 0x205, 0x205, 0x0, 0x0, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/internal/poll/fd_unix.go:169 +0x36a

net.(*netFD).Read(0xc0002c2000, 0xc0002ce000, 0x205, 0x205, 0x8, 0x0, 0xc0002ccf01)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/fd_unix.go:202 +0x66

net.(*conn).Read(0xc000010030, 0xc0002ce000, 0x205, 0x205, 0x117d9d3, 0xc00009e258, 0x10d99cc)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/net.go:184 +0xa1

crypto/tls.(*atLeastReader).Read(0xc0002a8140, 0xc0002ce000, 0x205, 0x205, 0xc0002a8140, 0x4061008, 0xc0002cd170)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/crypto/tls/conn.go:780 +0xa7

bytes.(*Buffer).ReadFrom(0xc00009e258, 0x1d3a1a0, 0xc0002a8140, 0x1bdab80, 0x3c6e138, 0xc000000000)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/bytes/buffer.go:204 +0x159

crypto/tls.(*Conn).readFromUntil(0xc00009e000, 0x3c6e138, 0xc000010030, 0x5, 0xc000010030, 0xc0002cd350)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/crypto/tls/conn.go:802 +0x210

crypto/tls.(*Conn).readRecordOrCCS(0xc00009e000, 0x0, 0x0, 0xc00019a698)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/crypto/tls/conn.go:609 +0x2e1

crypto/tls.(*Conn).readRecord(...)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/crypto/tls/conn.go:577

crypto/tls.(*Conn).Read(0xc00009e000, 0xc0002ea000, 0x1000, 0x1000, 0x0, 0x0, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/crypto/tls/conn.go:1255 +0x20c

net/http.(*connReader).Read(0xc00019a690, 0xc0002ea000, 0x1000, 0x1000, 0x0, 0xe36, 0x1)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/http/server.go:785 +0x24c

bufio.(*Reader).fill(0xc0001fa360)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/bufio/bufio.go:100 +0x19a

bufio.(*Reader).Peek(0xc0001fa360, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc0002cd948)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/bufio/bufio.go:138 +0xa0

net/http.(*conn).readRequest(0xc000194500, 0x1d49260, 0xc0000320c0, 0x0, 0x0, 0x0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/http/server.go:962 +0x1a0a

net/http.(*conn).serve(0xc000194500, 0x1d49260, 0xc0000320c0)

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/http/server.go:1817 +0x4e2

created by net/http.(*Server).Serve

	/Users/travis/.gimme/versions/go1.13.8.darwin.amd64/src/net/http/server.go:2928 +0x5b6

**Comment by ph** [comment]
Disabling the suite for fleet gateway so we can merge in master.

**Comment by ph** [comment]
@michalpristas can you take a look at this issue?

**Comment by ph** [comment]
@michalpristas nevermind, I've move it to myself and moved some windows issues to you. :)
