### ISSUE TITLE
[Agent] Panic when running mage package

### ISSUE THREAD

**Issue by ph** [elastic/beats#17757]
When I run `mage package` in the elastic-agent I get the following.
To reproduce with the traces you have to run with:

`MAGE_VERBOSE=true mage package`

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x44ca22]

goroutine 6 [running]:
runtime.throw(0xbcf715, 0x2a)
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/panic.go:774 +0x72 fp=0xc00004e730 sp=0xc00004e700 pc=0x42ef12
runtime.sigpanic()
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/signal_unix.go:378 +0x47c fp=0xc00004e760 sp=0xc00004e730 pc=0x443bcc
runtime.timerproc(0x12ad8e0)
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/time.go:260 +0xa2 fp=0xc00004e7d8 sp=0xc00004e760 pc=0x44ca22
runtime.goexit()
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00004e7e0 sp=0xc00004e7d8 pc=0x45bec1
created by runtime.(*timersBucket).addtimerLocked
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/time.go:169 +0x10e
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x452081]

runtime stack:
runtime.throw(0xbcf715, 0x2a)
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/panic.go:774 +0x72 fp=0xc00005be88 sp=0xc00005be58 pc=0x42ef12
runtime.sigpanic()
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/signal_unix.go:378 +0x47c fp=0xc00005beb8 sp=0xc00005be88 pc=0x443bcc
runtime.readgstatus(...)
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/proc.go:707
runtime.tracebackothers(0xc000001500)
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/traceback.go:916 +0x211 fp=0xc00005bf20 sp=0xc00005beb8 pc=0x452081
runtime.dopanic_m(0xc000001500, 0x42ef12, 0xc00004e700, 0xbcf715)
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/panic.go:974 +0x29e fp=0xc00005bf88 sp=0xc00005bf20 pc=0x42f5ee
runtime.fatalthrow.func1()
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/panic.go:829 +0x5f fp=0xc00005bfd0 sp=0xc00005bf88 pc=0x4588df
runtime.systemstack(0x0)
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/asm_amd64.s:370 +0x66 fp=0xc00005bfd8 sp=0xc00005bfd0 pc=0x459fe6
runtime.mstart()
        /Users/ph/.gvm/versions/go1.13.10.darwin.amd64/src/runtime/proc.go:1146 fp=0xc00005bfe0 sp=0xc00005bfd8 pc=0x4334d0
Error: failed building for windows/amd64: exit status 2
failed building for windows/amd64: exit status 2
>> buildGoDaemon: Building for linux/arm64
```

This doesn't happen on Linux, I do have a similar problem when running mage package in the x-pack/filebeaat directory.

**Comment by ph** [comment]
This look like related to the upgrade to go 1.13.10 in #17665 reverting to 1.13.9 fixes the issue. 

Checking If I can get more debug information for a go bug report.

**Comment by ph** [comment]
This was a rabbit hole, if you don't have enough memory for your docker daemon its possible to run into the above issues. I've bump the memory to 4gb (default is 2gb) and
