### ISSUE TITLE
elastic-agent: panic while stopping

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#17760]
I forgot to close the agent and it tried to communicate with already dead instance of Kibana. I noticed it and tried to stop. Failed with the following panic:

```bash
	fail to checkin to fleet: Post http://localhost:5601/api/ingest_manager/fleet/agents/10df6330-7ff2-11ea-aa00-a79c7a194129/checkin?: invalid api key to authenticate with fleet
2020-04-16T18:04:03+02:00 DEBUG	client.go:170	Request method: POST, path: /api/ingest_manager/fleet/agents/10df6330-7ff2-11ea-aa00-a79c7a194129/checkin
2020-04-16T18:04:03+02:00 ERROR	fleet_gateway.go:162	Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post http://localhost:5601/api/ingest_manager/fleet/agents/10df6330-7ff2-11ea-aa00-a79c7a194129/checkin?: invalid api key to authenticate with fleet
	fail to checkin to fleet: Post http://localhost:5601/api/ingest_manager/fleet/agents/10df6330-7ff2-11ea-aa00-a79c7a194129/checkin?: invalid api key to authenticate with fleet
2020-04-16T18:04:09+02:00 DEBUG	client.go:170	Request method: POST, path: /api/ingest_manager/fleet/agents/10df6330-7ff2-11ea-aa00-a79c7a194129/checkin
2020-04-16T18:04:09+02:00 ERROR	fleet_gateway.go:162	Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post http://localhost:5601/api/ingest_manager/fleet/agents/10df6330-7ff2-11ea-aa00-a79c7a194129/checkin?: invalid api key to authenticate with fleet
	fail to checkin to fleet: Post http://localhost:5601/api/ingest_manager/fleet/agents/10df6330-7ff2-11ea-aa00-a79c7a194129/checkin?: invalid api key to authenticate with fleet
2020-04-16T18:04:16+02:00 DEBUG	client.go:170	Request method: POST, path: /api/ingest_manager/fleet/agents/10df6330-7ff2-11ea-aa00-a79c7a194129/checkin
2020-04-16T18:04:16+02:00 ERROR	fleet_gateway.go:162	Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post http://localhost:5601/api/ingest_manager/fleet/agents/10df6330-7ff2-11ea-aa00-a79c7a194129/checkin?: invalid api key to authenticate with fleet
	fail to checkin to fleet: Post http://localhost:5601/api/ingest_manager/fleet/agents/10df6330-7ff2-11ea-aa00-a79c7a194129/checkin?: invalid api key to authenticate with fleet
^C2020-04-16T18:04:22+02:00 INFO	fleet_gateway.go:215	Fleet gateway is stopping
2020-04-16T18:04:22+02:00 ERROR	fleet_gateway.go:133	execute retry loop was stopped: /Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go[164]: unknown error
	execute retry loop was stopped: /Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go[164]: unknown error
^C2020-04-16T18:04:25+02:00 INFO	fleet_gateway.go:215	Fleet gateway is stopping
2020-04-16T18:04:25+02:00 INFO	panic.go:679	Fleet gateway is stopped
2020-04-16T18:04:25+02:00 INFO	panic.go:679	Agent is stopped
panic: close of closed channel

goroutine 65 [running]:
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application.(*fleetGateway).Stop(0xc0002ea0b0)
	/Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go:217 +0xd2
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application.(*fleetGateway).worker(0xc0002ea0b0)
	/Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go:150 +0x4cb
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application.(*fleetGateway).Start.func1(0xc0002ea0b0, 0xc0002ea138)
	/Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go:210 +0xfe
created by github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application.(*fleetGateway).Start
	/Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go:206 +0x6e
panic: close of closed channel

goroutine 1 [running]:
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/scheduler.(*PeriodicJitter).Stop(0xc0002e66c0)
	/Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/scheduler/scheduler.go:128 +0x2f
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application.(*fleetGateway).Stop(0xc0002ea0b0)
	/Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go:219 +0xea
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application.(*Managed).Stop(0xc0002e2660, 0x0, 0x0)
	/Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/managed_mode.go:199 +0xd0
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/cmd.run(0xc000217200, 0xc000263830, 0x4162a04, 0xc0000ff000)
	/Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/cmd/run.go:64 +0x41a
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/cmd.newRunCommandWithArgs.func1(0xc000278a00, 0x4f06e10, 0x0, 0x0)
	/Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/cmd/run.go:27 +0x3c
github.com/spf13/cobra.(*Command).execute(0xc000278a00, 0x4f06e10, 0x0, 0x0, 0xc000278a00, 0x4f06e10)
	/Users/marcin.tojek/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000278500, 0x2, 0x2, 0xc000263830)
	/Users/marcin.tojek/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/marcin.tojek/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/Users/marcin.tojek/go/src/github.com/elastic/beats/x-pack/elastic-agent/main.go:20 +0x138
```
/cc @ruflin

**Comment by ph** [comment]
Thanks @mtojek  working on a fix.

**Comment by ph** [comment]
I have fixed the panic, will check a bit more to make sure it's gone for good.

**Comment by ph** [comment]
Fixed in https://github.com/elastic/beats/pull/18135
