### ISSUE TITLE
Filebeat (7.6.2) crashes on fingerprint

### ISSUE THREAD

**Issue by nickytd** [elastic/beats#17837]
filebeat crashes when adding fingerprint
Can you please take a look and confirm? Thanks.

Here is the stack trace:
```
...

panic: d.nx != 0

goroutine 113 [running]:
crypto/sha256.(*digest).checkSum(0xc000c0f950, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/sha256/sha256.go:234 +0x1d9
crypto/sha256.(*digest).Sum(0xc0000c6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/sha256/sha256.go:210 +0x69
github.com/elastic/beats/libbeat/processors/fingerprint.(*fingerprint).Run(0xc00012e070, 0xc0000d0300, 0xc0000d0300, 0x0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/processors/fingerprint/fingerprint.go:73 +0xd1
github.com/elastic/beats/libbeat/publisher/processing.(*group).Run(0xc0006c0450, 0xc0000d0300, 0xc0000d0300, 0x0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/publisher/processing/processors.go:104 +0x94
github.com/elastic/beats/libbeat/publisher/processing.(*group).Run(0xc000781d70, 0xc0000d0300, 0xed62f4f4d, 0x0, 0xc000753ce0)
	/go/src/github.com/elastic/beats/libbeat/publisher/processing/processors.go:104 +0x94
github.com/elastic/beats/libbeat/publisher/pipeline.(*client).publish(0xc00070bc00, 0x391f483f, 0xed62f4f4d, 0x0, 0x0, 0xc000753f80, 0x31fb340, 0xc0004f3440, 0x0)
	/go/src/github.com/elastic/beats/libbeat/publisher/pipeline/client.go:89 +0x571
github.com/elastic/beats/libbeat/publisher/pipeline.(*client).Publish(0xc00070bc00, 0x391f483f, 0xed62f4f4d, 0x0, 0x0, 0xc000753f80, 0x31fb340, 0xc0004f3440, 0x0)
	/go/src/github.com/elastic/beats/libbeat/publisher/pipeline/client.go:68 +0xc2
github.com/elastic/beats/filebeat/channel.(*outlet).OnEvent(0xc000781e60, 0x391f483f, 0xed62f4f4d, 0x0, 0x0, 0xc000753f80, 0x31fb340, 0xc0004f3440, 0x0, 0x1)
	/go/src/github.com/elastic/beats/filebeat/channel/outlet.go:64 +0x7e
github.com/elastic/beats/filebeat/channel.SubOutlet.func1(0xc000d242a0, 0x37331e0, 0xc000781e60)
	/go/src/github.com/elastic/beats/filebeat/channel/util.go:45 +0x10d
created by github.com/elastic/beats/filebeat/channel.SubOutlet
	/go/src/github.com/elastic/beats/filebeat/channel/util.go:43 +0xf8
```

**Comment by ycombinator** [comment]
Hi @nickytd, appreciate you filing this issue here after initially posting it on discuss.elastic.co. Thank you!

As I mentioned in my reply on your discuss post, could you post your Filebeat configuration (with any sensitive information redacted, of course)? Also, do you happen to know which log entry or maybe a set of entries that's resulting in this panic? Essentially, it would be invaluable to have as much information as possible for us to be able to reproduce this issue. Thanks!

**Comment by nickytd** [comment]
Here is the related configuration
processors:
      - add_id: ~
      - add_kubernetes_metadata:
          in_cluster: true  
      - fingerprint:
          fields: ["@timestamp", "@metadata._id"]

There are no logs as the process is terminated immediately as seen in the stack trace.

**Comment by nickytd** [comment]
Here is a [helm chart ](https://github.com/nickytd/k8s-logging-helm/) bringing the stack to reproduce on minikube

**Comment by sashagutfraind** [comment]
I'm also seeing this error.  This might be possible related, although my setup is a 64bit OSX https://github.com/golang/go/issues/29517
