### ISSUE TITLE
metricbeat/mysql mapper - out of range of int

### ISSUE THREAD

**Issue by murlock** [elastic/beats#1809]
I'm playing with Elastic Search 5.0-alpha3 and MetricBeat 5.0.0-alpha3 on Ubuntu 14.04

I've only used metricbeat.full.yml, when I have enabled mysql module, I have a lot of errors regarding mysql stats, it seems that template contains integer instead of long 

<pre>
[2016-06-07 10:05:25,870][DEBUG][action.bulk              ] [Mad Jim Jaspers] [metricbeat-2016.06.07][3] failed to execute bulk item (index) index {[metricbeat-2016.06.07][metricsets][AVUp5RCSvhTyM2s9n6_o], source[{"@timestamp":"2016-06-07T08:05:25.614Z","beat":{"hostname":"ns332660.ip-176-31-124.eu","name":"ns332660.ip-176-31-124.eu"},"metricset":{"host":"tcp(127.0.0.1:3306)/","module":"mysql","name":"status","rtt":2145},"mysql":{"status":{"aborted":{"clients":15,"connects":33245},"binlog":{"cache":{"disk_use":0,"use":0}},"bytes":{"received":400742675,"sent":3938668244},"connections":114443,"created":{"tmp":{"disk_tables":12869,"files":6,"tables":36461}},"delayed":{"errors":0,"insert_threads":0,"writes":0},"flush_commands":1,"max_used_connections":12,"open":{"files":344,"streams":0,"tables":252},"opened_tables":12289}},"type":"metricsets"}]}

MapperParsingException[failed to parse [mysql.status.bytes.sent]]; nested: JsonParseException[Numeric value (3938668244) out of range of int
 at [Source: org.elasticsearch.common.io.stream.InputStreamStreamInput@4ec900b9; line: 1, column: 363]];
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:292)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:446)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:572)
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:392)
<pre>

**Comment by ruflin** [comment]
@murlock Thanks for reporting this. We should definitively use long for most fields.

**Comment by ruflin** [comment]
This should be resolved by https://github.com/elastic/beats/pull/1838
