### ISSUE TITLE
Nose tests failing to run (Failure: TypeError) on Linux with Python 3.5

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#18150]
## Flaky Test

* **Test Name:** No particular test
* **Link:** 
* **Branch:** master
* **Artifact Link:** https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats-beats-mbp/detail/PR-18149/1/pipeline/359
* **Notes:** `mage -d x-pack/filebeat pythonUnitTests`

### Stack Trace

```
 >> python test: Unit Testing
 E
 ======================================================================
 ERROR: Failure: TypeError (Cannot subscript an existing Union. Use Union[u, t] instead.)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/var/lib/jenkins/workspace/Beats_beats-beats-mbp_PR-18149/python-env/build/ve/linux/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
     raise self.exc_val.with_traceback(self.tb)
   File "/var/lib/jenkins/workspace/Beats_beats-beats-mbp_PR-18149/python-env/build/ve/linux/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
     addr.filename, addr.module)
   File "/var/lib/jenkins/workspace/Beats_beats-beats-mbp_PR-18149/python-env/build/ve/linux/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
     return self.importFromDir(dir_path, fqname)
   File "/var/lib/jenkins/workspace/Beats_beats-beats-mbp_PR-18149/python-env/build/ve/linux/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
     mod = load_module(part_fqname, fh, filename, desc)
   File "/usr/lib/python3.5/imp.py", line 234, in load_module
     return load_source(name, filename, file)
   File "/usr/lib/python3.5/imp.py", line 172, in load_source
     module = _load(spec)
   File "<frozen importlib._bootstrap>", line 693, in _load
   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
   File "/var/lib/jenkins/workspace/Beats_beats-beats-mbp_PR-18149/src/github.com/elastic/beats/x-pack/filebeat/tests/system/test_xpack_modules.py", line 6, in <module>
     import test_modules
   File "/var/lib/jenkins/workspace/Beats_beats-beats-mbp_PR-18149/src/github.com/elastic/beats/x-pack/filebeat/tests/system/../../../../filebeat/tests/system/test_modules.py", line 12, in <module>
     from deepdiff import DeepDiff
   File "/var/lib/jenkins/workspace/Beats_beats-beats-mbp_PR-18149/python-env/build/ve/linux/lib/python3.5/site-packages/deepdiff/__init__.py", line 10, in <module>
     from .diff import DeepDiff
   File "/var/lib/jenkins/workspace/Beats_beats-beats-mbp_PR-18149/python-env/build/ve/linux/lib/python3.5/site-packages/deepdiff/diff.py", line 17, in <module>
     from ordered_set import OrderedSet
   File "/var/lib/jenkins/workspace/Beats_beats-beats-mbp_PR-18149/python-env/build/ve/linux/lib/python3.5/site-packages/ordered_set.py", line 51, in <module>
     class OrderedSet(MutableSet[T], Sequence[T]):
   File "/var/lib/jenkins/workspace/Beats_beats-beats-mbp_PR-18149/python-env/build/ve/linux/lib/python3.5/site-packages/ordered_set.py", line 186, in OrderedSet
     def update(self, sequence: SetLike[T]) -> int:
   File "/usr/lib/python3.5/typing.py", line 546, in __getitem__
     "Cannot subscript an existing Union. Use Union[u, t] instead.")
 TypeError: Cannot subscript an existing Union. Use Union[u, t] instead.

```

[build.txt](https://github.com/elastic/beats/files/4566373/build.txt)

**Comment by andrewkroh** [comment]
On my mac this target runs without error. There is a deprecation warning though.

```
$ mage pythonUnitTest
>> python test: Unit Testing
/Users/akroh/go/src/github.com/elastic/beats/build/ve/darwin/lib/python3.7/site-packages/nose/suite.py:541: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(tests, collections.Callable) or isinstance(tests, unittest.TestSuite):
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
----------------------------------------------------------------------
Ran 116 tests in 0.012s

OK (SKIP=116)
>> python test: Unit Testing Complete
```

**Comment by andrewkroh** [comment]
A new version of ordered-set was released on April 29, 2020. I'm testing pinning it to the previous version 3.1.1.  See #18152.
