### ISSUE TITLE
[Filebeat] Flaky test test_inode_marker_based_identity_tracking

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#20010]
## Flaky Test

* **Test Name:** test_inode_marker_based_identity_tracking
* **Link:** https://github.com/elastic/beats/blob/8ff6894cab0591cc3a898d7abd6a9103e535efdd/filebeat/tests/system/test_input.py#L717
* **Branch:** master
* **Artifact Link:** https://travis-ci.org/github/elastic/beats/jobs/708873325#L782-L791
* **Notes:** Additional details about the test. e.g. theory as to failure cause

### Stack Trace

```
======================================================================

ERROR: File is picked up again if the contents of the marker file changes.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/gopath/src/github.com/elastic/beats/filebeat/tests/system/test_input.py", line 747, in test_inode_marker_based_identity_tracking

    self.wait_until(lambda: self.output_has(lines=2))

  File "/Users/travis/gopath/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 366, in wait_until

    "Waited {} seconds.".format(max_timeout))

beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
```

**Comment by andrewkroh** [comment]
I added a skip in #19960 .
