### ISSUE TITLE
Beats setup is throwing internal server error

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#20716]
For confirmed bugs, please report:
- Version: master, 7.x - snapshot
- Operating System: Ubuntu
- Steps to Reproduce: 

Run any of the supported beats setup ex: filebeat, metricbeat, packetbeat, auditbeat
`
./filebeat setup
Overwriting ILM policy is disabled. Set `setup.ilm.overwrite: true` for enabling.
Index setup finished.
Loading dashboards (Kibana must be running and reachable)
STDERR:
Exiting: 1 error: error loading index pattern: returned 500 to import file: \<nil\>. Response: {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred."}
`

Logfile:
`ERROR	instance/beat.go:935	Exiting: 1 error: error loading index pattern: returned 500 to import file: <nil>. Response: {"statusCode":500,"error":"Internal Server Error","message"
:"An internal server error occurred."}`

**Comment by jsoriano** [comment]
I have been able to reproduce this while running auditbeat tests in 7.x with `mage pythonIntegTest`, but it seems to be affecting at least libbeat too. The complete error in Kibana side is:
```
{"type":"log","@timestamp":"2020-08-24T11:15:14Z","tags":["error","http"],"pid":6,"message":"{ Error: Invalid version [1]\n    at Function.createInvalidVersionError (/usr/share/kibana/src/core/server/saved_objects/service/lib/errors.js:101:35)\n    at decodeVersion (/usr/share/kibana/src/core/server/saved_objects/version/decode_version.js:52:44)\n    at decodeRequestVersion (/usr/share/kibana/src/core/server/saved_objects/version/decode_request_version.js:34:53)\n    at getExpectedVersionProperties (/usr/share/kibana/src/core/server/saved_objects/service/lib/repository.js:1548:46)\n    at expectedResults.map.expectedBulkGetResult (/usr/share/kibana/src/core/server/saved_objects/service/lib/repository.js:319:29)\n    at Array.map (<anonymous>)\n    at SavedObjectsRepository.bulkCreate (/usr/share/kibana/src/core/server/saved_objects/service/lib/repository.js:273:49)\n    at SavedObjectsClient.bulkCreate (/usr/share/kibana/src/core/server/saved_objects/service/saved_objects_client.js:46:35)\n    at EncryptedSavedObjectsClientWrapper.bulkCreate (/usr/share/kibana/x-pack/plugins/encrypted_saved_objects/server/saved_objects/encrypted_saved_objects_client_wrapper.js:93:93)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n  data: null,\n  isBoom: true,\n  isServer: false,\n  output:\n   { statusCode: 400,\n     payload:\n      { statusCode: 400,\n        error: 'Bad Request',\n        message: 'Invalid version [1]' },\n     headers: {} },\n  reformat: [Function],\n  typeof: [Function: badRequest],\n  [Symbol(SavedObjectsClientErrorCode)]: 'SavedObjectsClient/invalidVersion' }"}
{"type":"error","@timestamp":"2020-08-24T11:15:14Z","tags":[],"pid":6,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toInternalError (/usr/share/kibana/src/core/server/http/router/response_adapter.js:69:19)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:177:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"?force=true","query":{"force":"true"},"pathname":"/api/kibana/dashboards/import","path":"/api/kibana/dashboards/import?force=true","href":"/api/kibana/dashboards/import?force=true"},"message":"Internal Server Error"}
```

**Comment by jsoriano** [comment]
Same errors in Kibana with `libbeat/tests/system/test_dashboard.py`.

**Comment by kvch** [comment]
It seems like a transient problem with Kibana. Please reopen the issue if it shows up again.
