### ISSUE TITLE
[build][metricbeat][darwin][7.x] mage build unitTest failed 

### ISSUE THREAD

**Issue by v1v** [elastic/beats#22044]
### Command

```bash
$ cd metricbeat
$ mage build unitTest
```

### Stacktrace

<details><summary>Expand to view</summary>
<p>

```
[2020-10-21T10:29:51.986Z] + mage build unitTest
[2020-10-21T10:30:00.746Z] >> build: Building metricbeat
[2020-10-21T10:31:42.893Z] >> go test: Unit Testing
[2020-10-21T10:34:10.320Z] SUMMARY:
[2020-10-21T10:34:10.320Z]   Fail:     0
[2020-10-21T10:34:10.320Z]   Skip:     2
[2020-10-21T10:34:10.320Z]   Pass:     267
[2020-10-21T10:34:10.320Z]   Packages: 34
[2020-10-21T10:34:10.320Z]   Duration: 2m26.793274187s
[2020-10-21T10:34:10.320Z]   Coverage Report: /private/var/lib/jenkins/workspace/Beats_beats_7.x@2/src/github.com/elastic/beats/x-pack/metricbeat/build/TEST-go-unit.html
[2020-10-21T10:34:10.320Z]   JUnit Report:    /private/var/lib/jenkins/workspace/Beats_beats_7.x@2/src/github.com/elastic/beats/x-pack/metricbeat/build/TEST-go-unit.xml
[2020-10-21T10:34:10.320Z]   Output File:     /private/var/lib/jenkins/workspace/Beats_beats_7.x@2/src/github.com/elastic/beats/x-pack/metricbeat/build/TEST-go-unit.out
[2020-10-21T10:34:10.320Z] >> go test: Unit Test Passed
[2020-10-21T10:34:10.320Z] Generated fields.yml for metricbeat to /private/var/lib/jenkins/workspace/Beats_beats_7.x@2/src/github.com/elastic/beats/x-pack/metricbeat/fields.yml
[2020-10-21T10:34:53.231Z] >> python test: Unit Testing
[2020-10-21T10:35:11.211Z]   ERROR: Command errored out with exit status 1:
[2020-10-21T10:35:11.211Z]    command: /private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/30/v8fqcvss33z_vy3cqhxrz8c80000md/T/pip-install-az7o8pqu/ordered-set/setup.py'"'"'; __file__='"'"'/private/var/folders/30/v8fqcvss33z_vy3cqhxrz8c80000md/T/pip-install-az7o8pqu/ordered-set/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/30/v8fqcvss33z_vy3cqhxrz8c80000md/T/pip-wheel-gbgmo52g
[2020-10-21T10:35:11.211Z]        cwd: /private/var/folders/30/v8fqcvss33z_vy3cqhxrz8c80000md/T/pip-install-az7o8pqu/ordered-set/
[2020-10-21T10:35:11.211Z]   Complete output (26 lines):
[2020-10-21T10:35:11.211Z]   running bdist_wheel
[2020-10-21T10:35:11.211Z]   running build
[2020-10-21T10:35:11.211Z]   running build_py
[2020-10-21T10:35:11.211Z]   file ordered_set.py (for module ordered_set) not found
[2020-10-21T10:35:11.211Z]   file ordered_set.py (for module ordered_set) not found
[2020-10-21T10:35:11.211Z]   running egg_info
[2020-10-21T10:35:11.211Z]   writing ordered_set.egg-info/PKG-INFO
[2020-10-21T10:35:11.211Z]   writing dependency_links to ordered_set.egg-info/dependency_links.txt
[2020-10-21T10:35:11.211Z]   writing top-level names to ordered_set.egg-info/top_level.txt
[2020-10-21T10:35:11.211Z]   writing manifest file 'ordered_set.egg-info/SOURCES.txt'
[2020-10-21T10:35:11.211Z]   file ordered_set.py (for module ordered_set) not found
[2020-10-21T10:35:11.211Z]   warning: Failed to find the configured license file 'MIT-LICENSE'
[2020-10-21T10:35:11.211Z]   reading manifest file 'ordered_set.egg-info/SOURCES.txt'
[2020-10-21T10:35:11.211Z]   reading manifest template 'MANIFEST.in'
[2020-10-21T10:35:11.211Z]   warning: no files found matching 'MIT-LICENSE'
[2020-10-21T10:35:11.211Z]   warning: no files found matching 'test.py'
[2020-10-21T10:35:11.211Z]   writing manifest file 'ordered_set.egg-info/SOURCES.txt'
[2020-10-21T10:35:11.211Z]   installing to build/bdist.macosx-10.14-x86_64/wheel
[2020-10-21T10:35:11.211Z]   running install
[2020-10-21T10:35:11.211Z]   running install_lib
[2020-10-21T10:35:11.211Z]   warning: install_lib: 'build/lib' does not exist -- no Python modules to install
[2020-10-21T10:35:11.211Z]   
[2020-10-21T10:35:11.211Z]   running install_egg_info
[2020-10-21T10:35:11.211Z]   Copying ordered_set.egg-info to build/bdist.macosx-10.14-x86_64/wheel/ordered_set-3.1.1-py3.8.egg-info
[2020-10-21T10:35:11.211Z]   running install_scripts
[2020-10-21T10:35:11.211Z]   error: [Errno 2] No such file or directory: 'MIT-LICENSE'
[2020-10-21T10:35:11.211Z]   ----------------------------------------
[2020-10-21T10:35:11.211Z]   ERROR: Failed building wheel for ordered-set
[2020-10-21T10:35:11.211Z]   ERROR: Command errored out with exit status 1:
[2020-10-21T10:35:11.211Z]    command: /private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/30/v8fqcvss33z_vy3cqhxrz8c80000md/T/pip-install-az7o8pqu/pyyaml/setup.py'"'"'; __file__='"'"'/private/var/folders/30/v8fqcvss33z_vy3cqhxrz8c80000md/T/pip-install-az7o8pqu/pyyaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/30/v8fqcvss33z_vy3cqhxrz8c80000md/T/pip-wheel-slirmqqu
[2020-10-21T10:35:11.211Z]        cwd: /private/var/folders/30/v8fqcvss33z_vy3cqhxrz8c80000md/T/pip-install-az7o8pqu/pyyaml/
[2020-10-21T10:35:11.211Z]   Complete output (31 lines):
[2020-10-21T10:35:11.211Z]   running bdist_wheel
[2020-10-21T10:35:11.211Z]   running build
[2020-10-21T10:35:11.211Z]   running build_py
[2020-10-21T10:35:11.211Z]   package init file 'lib3/yaml/__init__.py' not found (or not a regular file)
[2020-10-21T10:35:11.211Z]   running build_ext
[2020-10-21T10:35:11.211Z]   building '_yaml' extension
[2020-10-21T10:35:11.211Z]   creating build
[2020-10-21T10:35:11.211Z]   creating build/temp.macosx-10.14-x86_64-3.8
[2020-10-21T10:35:11.211Z]   creating build/temp.macosx-10.14-x86_64-3.8/ext
[2020-10-21T10:35:11.211Z]   clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/include -I/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c ext/_yaml.c -o build/temp.macosx-10.14-x86_64-3.8/ext/_yaml.o
[2020-10-21T10:35:11.211Z]   clang: error: no such file or directory: 'ext/_yaml.c'
[2020-10-21T10:35:11.211Z]   clang: error: no input files
[2020-10-21T10:35:11.211Z]   Error compiling module, falling back to pure Python
[2020-10-21T10:35:11.211Z]   installing to build/bdist.macosx-10.14-x86_64/wheel
[2020-10-21T10:35:11.211Z]   running install
[2020-10-21T10:35:11.211Z]   running install_lib
[2020-10-21T10:35:11.211Z]   warning: install_lib: 'build/lib.macosx-10.14-x86_64-3.8' does not exist -- no Python modules to install
[2020-10-21T10:35:11.211Z]   
[2020-10-21T10:35:11.211Z]   running install_egg_info
[2020-10-21T10:35:11.211Z]   running egg_info
[2020-10-21T10:35:11.211Z]   creating lib3/PyYAML.egg-info
[2020-10-21T10:35:11.211Z]   writing lib3/PyYAML.egg-info/PKG-INFO
[2020-10-21T10:35:11.211Z]   writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
[2020-10-21T10:35:11.211Z]   writing top-level names to lib3/PyYAML.egg-info/top_level.txt
[2020-10-21T10:35:11.211Z]   writing manifest file 'lib3/PyYAML.egg-info/SOURCES.txt'
[2020-10-21T10:35:11.211Z]   warning: Failed to find the configured license file 'LICENSE'
[2020-10-21T10:35:11.212Z]   reading manifest file 'lib3/PyYAML.egg-info/SOURCES.txt'
[2020-10-21T10:35:11.212Z]   writing manifest file 'lib3/PyYAML.egg-info/SOURCES.txt'
[2020-10-21T10:35:11.212Z]   Copying lib3/PyYAML.egg-info to build/bdist.macosx-10.14-x86_64/wheel/PyYAML-5.3.1-py3.8.egg-info
[2020-10-21T10:35:11.212Z]   running install_scripts
[2020-10-21T10:35:11.212Z]   error: [Errno 2] No such file or directory: 'LICENSE'
[2020-10-21T10:35:11.212Z]   ----------------------------------------
[2020-10-21T10:35:11.212Z]   ERROR: Failed building wheel for PyYAML
[2020-10-21T10:35:12.801Z]   DEPRECATION: ordered-set was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
[2020-10-21T10:35:14.389Z]   DEPRECATION: PyYAML was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
[2020-10-21T10:35:16.637Z] ============================= test session starts ==============================
[2020-10-21T10:35:16.637Z] platform darwin -- Python 3.8.6, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
[2020-10-21T10:35:16.637Z] rootdir: /private/var/lib/jenkins/workspace/Beats_beats_7.x@2/src/github.com/elastic/beats, configfile: pytest.ini
[2020-10-21T10:35:16.637Z] plugins: timeout-1.3.4, rerunfailures-9.0
[2020-10-21T10:35:16.637Z] timeout: 90.0s
[2020-10-21T10:35:16.637Z] timeout method: signal
[2020-10-21T10:35:16.637Z] timeout func_only: True
[2020-10-21T10:35:16.637Z] INTERNALERROR> Traceback (most recent call last):
[2020-10-21T10:35:16.637Z] INTERNALERROR>   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/main.py", line 240, in wrap_session
[2020-10-21T10:35:16.637Z] INTERNALERROR>     session.exitstatus = doit(config, session) or 0
[2020-10-21T10:35:16.637Z] INTERNALERROR>   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/main.py", line 295, in _main
[2020-10-21T10:35:16.638Z] INTERNALERROR>     config.hook.pytest_collection(session=session)
[2020-10-21T10:35:16.638Z] INTERNALERROR>   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
[2020-10-21T10:35:16.638Z] INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
[2020-10-21T10:35:16.638Z] INTERNALERROR>   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
[2020-10-21T10:35:16.638Z] INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
[2020-10-21T10:35:16.638Z] INTERNALERROR>   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
[2020-10-21T10:35:16.638Z] INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
[2020-10-21T10:35:16.638Z] INTERNALERROR>   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
[2020-10-21T10:35:16.638Z] INTERNALERROR>     return outcome.get_result()
[2020-10-21T10:35:16.638Z] INTERNALERROR>   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
[2020-10-21T10:35:16.638Z] INTERNALERROR>     raise ex[1].with_traceback(ex[2])
[2020-10-21T10:35:16.638Z] INTERNALERROR>   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/callers.py", line 182, in _multicall
[2020-10-21T10:35:16.638Z] INTERNALERROR>     next(gen)  # first yield
[2020-10-21T10:35:16.638Z] INTERNALERROR>   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/warnings.py", line 169, in pytest_collection
[2020-10-21T10:35:16.638Z] INTERNALERROR>     with catch_warnings_for_item(
[2020-10-21T10:35:16.638Z] INTERNALERROR>   File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
[2020-10-21T10:35:16.638Z] INTERNALERROR>     return next(self.gen)
[2020-10-21T10:35:16.638Z] INTERNALERROR>   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/warnings.py", line 113, in catch_warnings_for_item
[2020-10-21T10:35:16.638Z] INTERNALERROR>     warnings.filterwarnings(*_parse_filter(arg, escape=False))
[2020-10-21T10:35:16.638Z] INTERNALERROR>   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/warnings.py", line 39, in _parse_filter
[2020-10-21T10:35:16.638Z] INTERNALERROR>     category = warnings._getcategory(
[2020-10-21T10:35:16.638Z] INTERNALERROR>   File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/warnings.py", line 262, in _getcategory
[2020-10-21T10:35:16.638Z] INTERNALERROR>     raise _OptionError("invalid module name: %r" % (module,)) from None
[2020-10-21T10:35:16.638Z] INTERNALERROR> warnings._OptionError: invalid module name: 'yaml'
[2020-10-21T10:35:16.638Z] Traceback (most recent call last):
[2020-10-21T10:35:16.638Z]   File "/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/bin/pytest", line 8, in <module>
[2020-10-21T10:35:16.638Z]     sys.exit(console_main())
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/config/__init__.py", line 180, in console_main
[2020-10-21T10:35:16.638Z]     code = main()
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/config/__init__.py", line 157, in main
[2020-10-21T10:35:16.638Z]     ret = config.hook.pytest_cmdline_main(
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
[2020-10-21T10:35:16.638Z]     return self._hookexec(self, self.get_hookimpls(), kwargs)
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
[2020-10-21T10:35:16.638Z]     return self._inner_hookexec(hook, methods, kwargs)
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
[2020-10-21T10:35:16.638Z]     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
[2020-10-21T10:35:16.638Z]     return outcome.get_result()
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
[2020-10-21T10:35:16.638Z]     raise ex[1].with_traceback(ex[2])
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
[2020-10-21T10:35:16.638Z]     res = hook_impl.function(*args)
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/main.py", line 289, in pytest_cmdline_main
[2020-10-21T10:35:16.638Z]     return wrap_session(config, _main)
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/main.py", line 277, in wrap_session
[2020-10-21T10:35:16.638Z]     config.hook.pytest_sessionfinish(
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
[2020-10-21T10:35:16.638Z]     return self._hookexec(self, self.get_hookimpls(), kwargs)
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
[2020-10-21T10:35:16.638Z]     return self._inner_hookexec(hook, methods, kwargs)
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
[2020-10-21T10:35:16.638Z]     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
[2020-10-21T10:35:16.638Z]     gen.send(outcome)
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/terminal.py", line 803, in pytest_sessionfinish
[2020-10-21T10:35:16.638Z]     outcome.get_result()
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
[2020-10-21T10:35:16.638Z]     raise ex[1].with_traceback(ex[2])
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/pluggy/callers.py", line 182, in _multicall
[2020-10-21T10:35:16.638Z]     next(gen)  # first yield
[2020-10-21T10:35:16.638Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/warnings.py", line 189, in pytest_sessionfinish
[2020-10-21T10:35:16.639Z]     with catch_warnings_for_item(
[2020-10-21T10:35:16.639Z]   File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
[2020-10-21T10:35:16.639Z]     return next(self.gen)
[2020-10-21T10:35:16.639Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/warnings.py", line 113, in catch_warnings_for_item
[2020-10-21T10:35:16.639Z]     warnings.filterwarnings(*_parse_filter(arg, escape=False))
[2020-10-21T10:35:16.639Z]   File "/private/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/lib/python3.8/site-packages/_pytest/warnings.py", line 39, in _parse_filter
[2020-10-21T10:35:16.639Z]     category = warnings._getcategory(
[2020-10-21T10:35:16.639Z]   File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/warnings.py", line 262, in _getcategory
[2020-10-21T10:35:16.639Z]     raise _OptionError("invalid module name: %r" % (module,)) from None
[2020-10-21T10:35:16.639Z] warnings._OptionError: invalid module name: 'yaml'
[2020-10-21T10:35:16.639Z] >> python test: Unit Testing Complete
[2020-10-21T10:35:16.639Z] Error: running "/var/lib/jenkins/workspace/Beats_beats_7.x@2/python-env/build/ve/darwin/bin/pytest --timeout=90 --durations=20 --junit-xml=build/TEST-python-unit.xml tests/system/test_xpack_base.py module/activemq/test_activemq.py module/appsearch/test_appsearch.py module/cockroachdb/test_cockroachdb.py module/coredns/test_coredns.py module/ibmmq/test_ibmmq.py module/mssql/test_mssql.py module/openmetrics/test_openmetrics.py module/redisenterprise/test_redisenterprise.py module/sql/test_sql.py module/stan/test_stan.py module/statsd/test_statsd.py" failed with exit code 1
script returned exit code 1
```
</p>
</details>

![image](https://user-images.githubusercontent.com/2871786/96714254-c7539600-1399-11eb-9944-5e0251be036a.png)

Worker -> [worker-c07mq1u7dy3h](https://beats-ci.elastic.co/computer/worker-c07mq1u7dy3h/)

![image](https://user-images.githubusercontent.com/2871786/96714629-55c81780-139a-11eb-8b9a-2990017757bf.png)

## Question

- Is there any specific mage goal/task to prepare the `ve` context before running them? If so, we could add a `retry` step for the `ve` prepare context to avoid this kind of issue as much as possible, since so far if it happens then the builds get broken

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
