### ISSUE TITLE
Unix datagram sockets on Darwin time out

### ISSUE THREAD

**Issue by kvch** [elastic/beats#22775]
The datagram connection in test `TestReceiveNewEventsConcurrently` in `filebeat/inputsource/unix/server_test.go` times out after two events are processed.

Log lines from Travis:

```
=== RUN   TestReceiveNewEventsConcurrently/socket_type_datagram
difference between two IDs: 1 0 -1
difference between two IDs: 1 1 0
difference between two IDs: 1 2 1
panic: test timed out after 10m0s
goroutine 105 [running]:
testing.(*M).startAlarm.func1()
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/testing/testing.go:1509 +0xdf
created by time.goFunc
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/time/sleep.go:168 +0x44
goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0000e3680, 0x14ab246, 0x20, 0x14bcbe0, 0x108a301)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/testing/testing.go:1091 +0x399
testing.runTests.func1(0xc0000e27e0)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/testing/testing.go:1334 +0x78
testing.tRunner(0xc0000e27e0, 0xc0000d5e10)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/testing/testing.go:1039 +0xdc
testing.runTests(0xc0000aaac0, 0x1826ac0, 0xa, 0xa, 0x0)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/testing/testing.go:1332 +0x2a7
testing.(*M).Run(0xc000104100, 0x0)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/testing/testing.go:1249 +0x1b7
main.main()
	_testmain.go:62 +0x135
goroutine 130 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0000e2120, 0xc000026640, 0x14, 0xc00003a060, 0x8)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/testing/testing.go:1091 +0x399
github.com/elastic/beats/v7/filebeat/inputsource/unix.TestReceiveNewEventsConcurrently(0xc0000e3680)
	/Users/travis/gopath/src/github.com/elastic/beats/filebeat/inputsource/unix/server_test.go:315 +0xf2
testing.tRunner(0xc0000e3680, 0x14bcbe0)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/testing/testing.go:1039 +0xdc
created by testing.(*T).Run
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/testing/testing.go:1090 +0x372
goroutine 138 [runnable]:
github.com/elastic/beats/v7/filebeat/inputsource/unix.TestReceiveNewEventsConcurrently.func1(0xc0000e2120)
	/Users/travis/gopath/src/github.com/elastic/beats/filebeat/inputsource/unix/server_test.go:367 +0x8b7
testing.tRunner(0xc0000e2120, 0xc00003a060)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/testing/testing.go:1039 +0xdc
created by testing.(*T).Run
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/testing/testing.go:1090 +0x372
goroutine 104 [select, 9 minutes]:
github.com/elastic/go-concert/ctxtool.(*funcContext).wait(0xc000118000, 0xc000036060, 0xc0000360c0, 0xc00000e040)
	/Users/travis/gopath/pkg/mod/github.com/elastic/go-concert@v0.0.4/ctxtool/func.go:62 +0x107
created by github.com/elastic/go-concert/ctxtool.WithFunc
	/Users/travis/gopath/pkg/mod/github.com/elastic/go-concert@v0.0.4/ctxtool/func.go:48 +0xfe
goroutine 142 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x19a0618, 0x72, 0x0)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000104018, 0x72, 0x1400000, 0x1400000, 0x0)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).ReadFrom(0xc000104000, 0xc001a00000, 0x1400000, 0x1400000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/internal/poll/fd_unix.go:219 +0x1a3
net.(*netFD).readFrom(0xc000104000, 0xc001a00000, 0x1400000, 0x1400000, 0x100e566, 0x0, 0x0, 0x0, 0xc0000a0298)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/net/fd_unix.go:208 +0x5b
net.(*UnixConn).readFrom(0xc00009e048, 0xc001a00000, 0x1400000, 0x1400000, 0x101, 0xc000059cc0, 0xc000059d38, 0x104d35c)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/net/unixsock_posix.go:103 +0x5c
net.(*UnixConn).ReadFrom(0xc00009e048, 0xc001a00000, 0x1400000, 0x1400000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.14.7.darwin.amd64/src/net/unixsock.go:122 +0x5d
github.com/elastic/beats/v7/filebeat/inputsource/common/dgram.DatagramReaderFactory.func1.1(0x1548980, 0xc000118000, 0x154b100, 0xc00009e048, 0x1457ce0, 0xc000036001)
	/Users/travis/gopath/src/github.com/elastic/beats/filebeat/inputsource/common/dgram/handler.go:58 +0xe2
github.com/elastic/beats/v7/filebeat/inputsource/common/dgram.(*Listener).run(0xc0000b82c0, 0x1548980, 0xc000118000, 0x154b100, 0xc00009e048, 0xc00000e001, 0x1857320)
	/Users/travis/gopath/src/github.com/elastic/beats/filebeat/inputsource/common/dgram/server.go:117 +0x9a
github.com/elastic/beats/v7/filebeat/inputsource/common/dgram.(*Listener).Start.func1(0x19a3628, 0xc0000201c0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/elastic/beats/filebeat/inputsource/common/dgram/server.go:109 +0x1df
github.com/elastic/go-concert/unison.(*TaskGroup).Go.func1(0xc0000b82f0, 0xc0000aa700)
	/Users/travis/gopath/pkg/mod/github.com/elastic/go-concert@v0.0.4/unison/taskgroup.go:110 +0x99
created by github.com/elastic/go-concert/unison.(*TaskGroup).Go
	/Users/travis/gopath/pkg/mod/github.com/elastic/go-concert@v0.0.4/unison/taskgroup.go:108 +0x9b
goroutine 143 [chan receive, 9 minutes]:
github.com/elastic/beats/v7/filebeat/inputsource/unix.sendOverUnixDatagram(0xc0000e2120, 0x1548780, 0xc000020200, 0xc00002c4c0, 0x3a, 0xc000094700, 0x64, 0x64)
	/Users/travis/gopath/src/github.com/elastic/beats/filebeat/inputsource/unix/server_test.go:408 +0x20b
created by github.com/elastic/beats/v7/filebeat/inputsource/unix.TestReceiveNewEventsConcurrently.func1
	/Users/travis/gopath/src/github.com/elastic/beats/filebeat/inputsource/unix/server_test.go:359 +0x786
```

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
