### ISSUE TITLE
Flaky Test [Build&Test / x-pack/heartbeat-windows-windows-2019 / TestRunCmd/has_echo'd_stdin_to_stdout – github.com/elastic/beats/v7/x-pack/heartbeat/monitors/browser/synthexec]

### ISSUE THREAD

**Issue by v1v** [elastic/beats#23957]
## Flaky Test

* **Test Name:** `TestRunCmd/has_echo'd_stdin_to_stdout – github.com/elastic/beats/v7/x-pack/heartbeat/monitors/browser/synthexec`
* **Link:** Link to file/line number in github.
* **Branch:** master
* **Artifact Link:** Ihttps://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-23873/runs/4/steps/1274/log/?start=0
* **Notes:** Platforms: only fails in Windows (all the versions)

### Stack Trace

```
Error
Failed
Stacktrace
=== RUN   TestRunCmd/has_echo'd_stdin_to_stdout
    --- FAIL: TestRunCmd/has_echo'd_stdin_to_stdout (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
goroutine 21 [running]:
testing.tRunner.func1.1(0x152b220, 0xc0004a6860)
	C:/Users/jenkins/workspace/Beats_beats_PR-23873/.gvm/versions/go1.15.7.windows.amd64/src/testing/testing.go:1072 +0x310
testing.tRunner.func1(0xc00010a300)
	C:/Users/jenkins/workspace/Beats_beats_PR-23873/.gvm/versions/go1.15.7.windows.amd64/src/testing/testing.go:1075 +0x43a
panic(0x152b220, 0xc0004a6860)
	C:/Users/jenkins/workspace/Beats_beats_PR-23873/.gvm/versions/go1.15.7.windows.amd64/src/runtime/panic.go:969 +0x1c7
github.com/elastic/beats/v7/x-pack/heartbeat/monitors/browser/synthexec.TestRunCmd.func2(0xc00010a300)
	C:/Users/jenkins/workspace/Beats_beats_PR-23873/src/github.com/elastic/beats/x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go:133 +0x136
testing.tRunner(0xc00010a300, 0xc00049c040)
	C:/Users/jenkins/workspace/Beats_beats_PR-23873/.gvm/versions/go1.15.7.windows.amd64/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	C:/Users/jenkins/workspace/Beats_beats_PR-23873/.gvm/versions/go1.15.7.windows.amd64/src/testing/testing.go:1168 +0x2b3
```

**Comment by v1v** [comment]
still valid

**Comment by v1v** [comment]
> Closing as not seen in a while

Windows was disabled as per https://github.com/elastic/beats/issues/23859#issuecomment-781520450 and https://github.com/elastic/beats/issues/23958#issuecomment-1183320503

https://github.com/elastic/beats/pull/23873 was the original implementation, but the windows errors were reported (this is one of the issues) and disabled them to move forward with some CI validation for some other stages/OSes

**Comment by v1v** [comment]
To help with I just raised https://github.com/elastic/beats/pull/32937 so the @elastic/uptime can troubleshoot those test failures, if they are still happening
