### ISSUE TITLE
[x-pack/metricbeats] build/test process cannot take more than 2 gb of RAM in Windows 7 32 bits

### ISSUE THREAD

**Issue by v1v** [elastic/beats#24082]
Windows 7 32 bits got a memory limitation by definition and causes

```
[2021-02-16T18:43:58.114Z] === Errors
[2021-02-16T18:43:58.114Z] panic: Not enough storage is available to process this command.
[2021-02-16T18:43:58.114Z] 
[2021-02-16T18:43:58.114Z] goroutine 1 [running]:
[2021-02-16T18:43:58.114Z] cmd/link/internal/ld.(*OutBuf).copyHeap(0x110bc080, 0x35355570)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/ld/outbuf.go:155 +0x106
[2021-02-16T18:43:58.114Z] cmd/link/internal/ld.(*OutBuf).writeLoc(0x110bc080, 0x4, 0x0, 0xa00000, 0x0, 0x41070000, 0xa00004, 0xad8000)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/ld/outbuf.go:189 +0x20e
[2021-02-16T18:43:58.114Z] cmd/link/internal/ld.(*OutBuf).Write(0x110bc080, 0x110bc0b0, 0x4, 0x8, 0xc07a, 0x0, 0x0)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/ld/outbuf.go:210 +0x38
[2021-02-16T18:43:58.114Z] cmd/link/internal/ld.(*OutBuf).Write32(0x110bc080, 0xc07a)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/ld/outbuf.go:235 +0x72
[2021-02-16T18:43:58.114Z] cmd/link/internal/x86.pereloc1(0x7f0940, 0x110bc080, 0x69b4f750, 0x70ff8cc0, 0x1ff4eb6, 0x0, 0x802001)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/x86/asm.go:416 +0x5f
[2021-02-16T18:43:58.114Z] cmd/link/internal/ld.(*peFile).emitRelocations.func1(0x110d5950, 0x111a4000, 0x24295, 0x24295, 0x400000, 0x0, 0x110bc0b0)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/ld/pe.go:530 +0x23c
[2021-02-16T18:43:58.114Z] cmd/link/internal/ld.(*peFile).emitRelocations.func2(0x110bc080)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/ld/pe.go:553 +0x76
[2021-02-16T18:43:58.114Z] cmd/link/internal/ld.(*peSection).emitRelocations(0x65a2a7e0, 0x110bc080, 0x6493b638)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/ld/pe.go:364 +0x66
[2021-02-16T18:43:58.114Z] cmd/link/internal/ld.(*peFile).emitRelocations(0x7f7fa0, 0x110e01a0)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/ld/pe.go:550 +0x222
[2021-02-16T18:43:58.114Z] cmd/link/internal/ld.Asmbpe(0x110e01a0)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/ld/pe.go:1583 +0x2cb
[2021-02-16T18:43:58.114Z] cmd/link/internal/x86.asmb2(0x110e01a0)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/x86/asm.go:675 +0xbd
[2021-02-16T18:43:58.114Z] cmd/link/internal/ld.Main(0x7f0940, 0x10, 0x20, 0x1, 0x4, 0x8, 0x0, 0x0, 0x674f00, 0x12, ...)
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/internal/ld/main.go:349 +0x1220
[2021-02-16T18:43:58.114Z] main.main()
[2021-02-16T18:43:58.114Z] 	c:/go/src/cmd/link/main.go:68 +0x150
[2021-02-16T18:43:58.114Z] 
[2021-02-16T18:43:58.114Z] DONE 262 tests, 2 skipped, 16 errors in 81.962s
[2021-02-16T18:43:58.114Z] Error: go test returned a non-zero value: exit status 2
```

You can see the whole logs in -> https://gist.github.com/v1v/9846a39dc2b5506f7d9acb78ebb14c4c

### Expectations

The `x-pack/metricbeats` build/test system to be adjusted in a way it can cope the OS expectations, then we won't face any runtime build errors related to a limited capacity in the 32 arch for Windows 7

**Comment by v1v** [comment]
This is not about the Automation team but the build system that requires to be adapted to the SO requirements, for Windows-7 32 bits, there is no a possibility to run processes with more than 2 gb of RAM. Since the build system is owned by the beats team, I've just removed the automation team as being the one assigned.  I don't know who should be the team to work on this though :(

**Comment by v1v** [comment]
https://github.com/elastic/beats/pull/24188 failed with a similar error, even worst, since it did nothing but failing quite fast

```
[2021-02-23T17:03:17.090Z] 
[2021-02-23T17:03:17.090Z] C:\Users\jenkins\workspace\Beats_beats_PR-24188\src\github.com\elastic\beats\x-pack\metricbeat>mage build unitTest 
[2021-02-23T17:03:39.995Z] >> build: Building metricbeat
[2021-02-23T17:05:31.883Z] # github.com/elastic/beats/v7/x-pack/metricbeat
[2021-02-23T17:05:31.883Z] panic: Not enough storage is available to process this command.
[2021-02-23T17:05:31.883Z] 
[2021-02-23T17:05:31.883Z] goroutine 1 [running]:
[2021-02-23T17:05:31.883Z] cmd/link/internal/ld.(*OutBuf).copyHeap(0x110400c0, 0x0)
[2021-02-23T17:05:31.883Z] 	c:/go/src/cmd/link/internal/ld/outbuf.go:155 +0x106
[2021-02-23T17:05:31.883Z] cmd/link/internal/ld.(*OutBuf).writeLoc(0x110400c0, 0x1, 0x0, 0x9ffffd, 0x0, 0x40b80000, 0x9ffffe, 0xad8000)
[2021-02-23T17:05:31.884Z] 	c:/go/src/cmd/link/internal/ld/outbuf.go:189 +0x20e
[2021-02-23T17:05:31.884Z] cmd/link/internal/ld.(*OutBuf).Write8(...)
[2021-02-23T17:05:31.884Z] 	c:/go/src/cmd/link/internal/ld/outbuf.go:217
[2021-02-23T17:05:31.884Z] cmd/link/internal/ld.(*peStringTable).write(0x7f7fac, 0x110400c0)
[2021-02-23T17:05:31.884Z] 	c:/go/src/cmd/link/internal/ld/pe.go:290 +0xb2
[2021-02-23T17:05:31.884Z] cmd/link/internal/ld.(*peFile).writeSymbolTableAndStringTable(0x7f7fa0, 0x111041a0)
[2021-02-23T17:05:31.884Z] 	c:/go/src/cmd/link/internal/ld/pe.go:725 +0x8d
[2021-02-23T17:05:31.884Z] cmd/link/internal/ld.Asmbpe(0x111041a0)
[2021-02-23T17:05:31.884Z] 	c:/go/src/cmd/link/internal/ld/pe.go:1580 +0x297
[2021-02-23T17:05:31.884Z] cmd/link/internal/x86.asmb2(0x111041a0)
[2021-02-23T17:05:31.884Z] 	c:/go/src/cmd/link/internal/x86/asm.go:675 +0xbd
[2021-02-23T17:05:31.884Z] cmd/link/internal/ld.Main(0x7f0940, 0x10, 0x20, 0x1, 0x4, 0x8, 0x0, 0x0, 0x674f00, 0x12, ...)
[2021-02-23T17:05:31.884Z] 	c:/go/src/cmd/link/internal/ld/main.go:349 +0x1220
[2021-02-23T17:05:31.884Z] main.main()
[2021-02-23T17:05:31.884Z] 	c:/go/src/cmd/link/main.go:68 +0x150
[2021-02-23T17:05:31.884Z] Error: running "go build -o metricbeat.exe -ldflags -s -w -X github.com/elastic/beats/v7/libbeat/version.buildTime=2021-02-23T17:03:36Z -X github.com/elastic/beats/v7/libbeat/version.commit=1a9f524e7ef1d169fb476049be9aff978d1bc75f" failed with exit code 2
script returned exit code 2
```

**Comment by mtojek** [comment]
FYI I have just detached the worker Windows 7 32 bit from the building process of x-pack/metricbeat.

**Comment by jlind23** [comment]
Closing it as 32 bits are not supported anymore
