### ISSUE TITLE
[CI]  .ci/scripts/pre_archive_test.py fails only for x-pack/functionbeat in some Windows versions

### ISSUE THREAD

**Issue by v1v** [elastic/beats#24406]
Module: `x-pack/functionbeat`

Windows:
* windows-2012-r2
* windows-2016
* windows-7-32-bit
* wiindows-2019

Stacktrace:

```
python .ci/scripts/pre_archive_test.py
— Prepare test output
2s
[2021-03-05T12:19:53.263Z] 
[2021-03-05T12:19:53.263Z] C:\Users\jenkins\workspace\PR-24374-2-f69dd93b-7f43-43af-b2b7-60fd64536706\src\github.com\elastic\beats>python .ci/scripts/pre_archive_test.py 
[2021-03-05T12:19:55.174Z] Copy .\x-pack\functionbeat\build into build\x-pack\functionbeat\build
[2021-03-05T12:19:55.174Z] Copy .\x-pack\functionbeat\null\build into build\x-pack\functionbeat\null\build
[2021-03-05T12:19:55.174Z] Traceback (most recent call last):
[2021-03-05T12:19:55.174Z]   File "C:\Python38\lib\distutils\file_util.py", line 41, in _copy_file_contents
[2021-03-05T12:19:55.174Z]     fdst = open(dst, 'wb')
[2021-03-05T12:19:55.174Z] FileNotFoundError: [Errno 2] No such file or directory: 'build\\x-pack\\functionbeat\\null\\build\\ve\\windows\\Lib\\site-packages\\pip\\_vendor\\urllib3\\packages\\ssl_match_hostname\\__pycache__\\_implementation.cpython-38.pyc'
[2021-03-05T12:19:55.174Z] 
[2021-03-05T12:19:55.174Z] During handling of the above exception, another exception occurred:
[2021-03-05T12:19:55.174Z] 
[2021-03-05T12:19:55.174Z] Traceback (most recent call last):
[2021-03-05T12:19:55.174Z]   File ".ci/scripts/pre_archive_test.py", line 20, in <module>
[2021-03-05T12:19:55.174Z]     distutils.dir_util.copy_tree(root, dest, preserve_symlinks=1)
[2021-03-05T12:19:55.174Z]   File "C:\Python38\lib\distutils\dir_util.py", line 157, in copy_tree
[2021-03-05T12:19:55.174Z]     copy_tree(src_name, dst_name, preserve_mode,
[2021-03-05T12:19:55.174Z]   File "C:\Python38\lib\distutils\dir_util.py", line 157, in copy_tree
[2021-03-05T12:19:55.174Z]     copy_tree(src_name, dst_name, preserve_mode,
[2021-03-05T12:19:55.174Z]   File "C:\Python38\lib\distutils\dir_util.py", line 157, in copy_tree
[2021-03-05T12:19:55.174Z]     copy_tree(src_name, dst_name, preserve_mode,
[2021-03-05T12:19:55.174Z]   [Previous line repeated 7 more times]
[2021-03-05T12:19:55.174Z]   File "C:\Python38\lib\distutils\dir_util.py", line 161, in copy_tree
[2021-03-05T12:19:55.174Z]     copy_file(src_name, dst_name, preserve_mode,
[2021-03-05T12:19:55.174Z]   File "C:\Python38\lib\distutils\file_util.py", line 151, in copy_file
[2021-03-05T12:19:55.174Z]     _copy_file_contents(src, dst)
[2021-03-05T12:19:55.174Z]   File "C:\Python38\lib\distutils\file_util.py", line 43, in _copy_file_contents
[2021-03-05T12:19:55.174Z]     raise DistutilsFileError(
[2021-03-05T12:19:55.174Z] distutils.errors.DistutilsFileError: could not create 'build\x-pack\functionbeat\null\build\ve\windows\Lib\site-packages\pip\_vendor\urllib3\packages\ssl_match_hostname\__pycache__\_implementation.cpython-38.pyc': No such file or directory
script returned exit code 1
```

![image](https://user-images.githubusercontent.com/2871786/110207666-f5cf9a80-7e7c-11eb-85d8-3fa102616bf7.png)

While the expected behaviour should be something like:

![image](https://user-images.githubusercontent.com/2871786/110207691-139cff80-7e7d-11eb-8981-8763742eb79f.png)

**Comment by v1v** [comment]
https://github.com/elastic/beats/pull/24316 was added to ensure workspaces were unique, and somehow might be related, no idea how but it seems the very first time it happened was with that particular PR and also when merged

![image](https://user-images.githubusercontent.com/2871786/110208881-8d36ec80-7e81-11eb-974d-d4cef67c6b0e.png)
