### ISSUE TITLE
Filebeat panics on heavy file rotation

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#2508]
Running the system test test_no_missing_events with RACE_DETECTOR enabled, filebeat sometimes panics. Seen here: http://build-eu-00.elastic.co/job/Beats-PR/3349/artifact/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_load.Test.test_no_missing_events/filebeat.log

```
2016/09/09 06:18:43.087986 log.go:328: WARN Stopping harvester, NOT closing file as file info not available: /home/jenkins/workspace/Beats-PR/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_load.Test.test_no_missing_events/log/test.log.5
2016/09/09 06:18:43.087962 crawler.go:66: DBG  Prospector 0 stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x4bac3c]

goroutine 52 [running]:
panic(0xb15220, 0xc420012100)
	/home/jenkins/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1ae
github.com/elastic/beats/filebeat/input/file.GetOSState(0x0, 0x0, 0x1a, 0x1d)
	github.com/elastic/beats/filebeat/input/file/_obj/file_other.go:23 +0x4c
github.com/elastic/beats/filebeat/input/file.NewState(0x0, 0x0, 0xc42023e1e0, 0x93, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/elastic/beats/filebeat/input/file/_obj/state.go:31 +0x98
github.com/elastic/beats/filebeat/prospector.(*ProspectorLog).scan(0xc4200d0630)
	github.com/elastic/beats/filebeat/prospector/_obj/prospector_log.go:183 +0x2a7
github.com/elastic/beats/filebeat/prospector.(*ProspectorLog).Run(0xc4200d0630)
	github.com/elastic/beats/filebeat/prospector/_obj/prospector_log.go:64 +0xd3
github.com/elastic/beats/filebeat/prospector.(*Prospector).Run(0xc420127930)
	github.com/elastic/beats/filebeat/prospector/_obj/prospector.go:170 +0x360
github.com/elastic/beats/filebeat/crawler.(*Crawler).Start.func1(0xc42007b4f0, 0x0, 0xc420127930)
	github.com/elastic/beats/filebeat/crawler/_obj/crawler.go:70 +0x166
created by github.com/elastic/beats/filebeat/crawler.(*Crawler).Start
	github.com/elastic/beats/filebeat/crawler/_obj/crawler.go:71 +0x5ee
```

**Comment by ruflin** [comment]
Closing as fixed in https://github.com/elastic/beats/pull/2512
