### ISSUE TITLE
[elastic-agent] panic on receiving osquery action 

### ISSUE THREAD

**Issue by james-elastic** [elastic/beats#25441]
Using the latest 7.13 BC snapshot of agent and the stack I was issuing an osquery action the agent stopped and panicked.   A side affect of this is that the other beats will spike up the CPU to the max and I had to manually `kill -9` .

Downloaded the lates

Cmds ran
```
sudo ./elastic-agent enroll -f --url=<URL> --enrollment-token=<TOKEN> --insecure
sudo ./elastic-agent -e 
```

Trace:
```
2021-04-29T14:40:53.219-0400	INFO	operation/operator.go:259	operation 'operation-install' skipped for filebeat.7.13.0-SNAPSHOT
2021-04-29T14:40:53.368-0400	INFO	log/reporter.go:40	2021-04-29T14:40:53-04:00 - message: Application: filebeat--7.13.0-SNAPSHOT[1e597d6f-0176-4a1f-b3f0-5dff7137f628]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2021-04-29T14:40:53.562-0400	INFO	operation/operator.go:259	operation 'operation-install' skipped for filebeat.7.13.0-SNAPSHOT
2021-04-29T14:40:53.714-0400	INFO	log/reporter.go:40	2021-04-29T14:40:53-04:00 - message: Application: filebeat--7.13.0-SNAPSHOT--36643631373035623733363936343635[1e597d6f-0176-4a1f-b3f0-5dff7137f628]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2021-04-29T14:40:53.775-0400	INFO	log/reporter.go:40	2021-04-29T14:40:53-04:00 - message: Application: metricbeat--7.13.0-SNAPSHOT[1e597d6f-0176-4a1f-b3f0-5dff7137f628]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2021-04-29T14:40:53.883-0400	INFO	operation/operator.go:259	operation 'operation-install' skipped for metricbeat.7.13.0-SNAPSHOT
2021-04-29T14:40:54.180-0400	INFO	log/reporter.go:40	2021-04-29T14:40:54-04:00 - message: Application: metricbeat--7.13.0-SNAPSHOT--36643631373035623733363936343635[1e597d6f-0176-4a1f-b3f0-5dff7137f628]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2021-04-29T14:40:54.185-0400	INFO	stateresolver/stateresolver.go:66	Updating internal state
2021-04-29T14:40:54.526-0400	INFO	log/reporter.go:40	2021-04-29T14:40:54-04:00 - message: Application: osquerybeat--7.13.0-SNAPSHOT[1e597d6f-0176-4a1f-b3f0-5dff7137f628]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2021-04-29T14:40:54.898-0400	INFO	log/reporter.go:40	2021-04-29T14:40:54-04:00 - message: Application: filebeat--7.13.0-SNAPSHOT--36643631373035623733363936343635[1e597d6f-0176-4a1f-b3f0-5dff7137f628]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2021-04-29T14:40:54.899-0400	INFO	log/reporter.go:40	2021-04-29T14:40:54-04:00 - message: Application: filebeat--7.13.0-SNAPSHOT[1e597d6f-0176-4a1f-b3f0-5dff7137f628]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2021-04-29T14:40:55.314-0400	INFO	log/reporter.go:40	2021-04-29T14:40:55-04:00 - message: Application: metricbeat--7.13.0-SNAPSHOT--36643631373035623733363936343635[1e597d6f-0176-4a1f-b3f0-5dff7137f628]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2021-04-29T14:41:16.405-0400	INFO	runtime/panic.go:969	Fleet gateway is stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10cd9ea66]

goroutine 62 [running]:
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/core/server.(*Server).FindByInputType(0x0, 0xc0003f79e0, 0x7, 0x27, 0xc000b6dc40)
	/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/core/server/server.go:201 +0x66
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers.(*AppAction).Handle(0xc00041d440, 0x10dfd2820, 0xc00020e400, 0x10dfbeda0, 0xc000c88680, 0x10df946a0, 0xc00025b060, 0x10dba3201, 0xc000949390)
	/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_application.go:41 +0x1b9
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application/pipeline/dispatcher.(*ActionDispatcher).dispatchAction(0xc000c8a8d0, 0x10dfbeda0, 0xc000c88680, 0x10df946a0, 0xc00025b060, 0x2, 0x2)
	/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/pipeline/dispatcher/dispatcher.go:110 +0xd2
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application/pipeline/dispatcher.(*ActionDispatcher).Dispatch(0xc000c8a8d0, 0x10df946a0, 0xc00025b060, 0xc000949370, 0x1, 0x1, 0x1, 0x0)
	/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/pipeline/dispatcher/dispatcher.go:94 +0x254
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application/gateway/fleet.(*fleetGateway).worker(0xc000120000)
	/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway.go:178 +0x366
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application/gateway/fleet.(*fleetGateway).Start.func1(0xc000120000, 0xc000120088)
	/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway.go:292 +0xbd
created by github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/application/gateway/fleet.(*fleetGateway).Start
	/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway.go:288 +0x71
```

**Comment by ruflin** [comment]
@aleksmaus Could you take a look at this?

**Comment by james-elastic** [comment]
@ruflin He's on it :)

**Comment by aleksmaus** [comment]
The stack trace points at:
https://github.com/elastic/beats/blob/7.13/x-pack/elastic-agent/pkg/core/server/server.go#L201

Server pointer is nil? what has changed since the last time it was working?
Looking

**Comment by aleksmaus** [comment]
looks like missing change on 7.13
https://github.com/elastic/beats/blob/7.13/x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_application.go#L27

the master branch for comparison
https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_application.go#L27

**Comment by aleksmaus** [comment]
looks like a bad merge 
https://github.com/elastic/beats/commit/8b6ac25b1ffd62a9aef1b2bf3fbacc98d1e8caf9#diff-7cae4c8965dc39e26ca4b27e10c[…]c4702184a2fe1e9177a463f9d4336L22

**Comment by ruflin** [comment]
Going to close this as https://github.com/elastic/beats/pull/25447 was merged. @james-elastic Would be good if you could confirm / test with the changes.
