### ISSUE TITLE
TestDefaultHarvesterGroup failing on CI

### ISSUE THREAD

**Issue by jalvz** [elastic/beats#26203]
Found in https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-25998/4/tests/ 

Output:

```
=== RUN   TestDefaultHarvesterGroup/assert_a_harvester_for_same_source_cannot_be_started
coverage: 42.5% of statements
panic: test timed out after 10m0s
goroutine 66 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1700 +0xe5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:180 +0x45
goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00066aa80, 0xcdb673, 0x19, 0xcfc760, 0x493101)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc0005c2300)
	/usr/local/go/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc0005c2300, 0xc0005bfda8)
	/usr/local/go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc000630000, 0x1247a00, 0x11, 0x11, 0xc0264ad7f42a101d, 0x8bb4bac924, 0x1255b60, 0xcd351f)
	/usr/local/go/src/testing/testing.go:1509 +0x2fe
testing.(*M).Run(0xc00062c000, 0x0)
	/usr/local/go/src/testing/testing.go:1417 +0x1eb
main.main()
	_testmain.go:141 +0x1c5
goroutine 45 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00066af00, 0xcee234, 0x34, 0xc0005d1750, 0xd9bc01)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup(0xc00066aa80)
	/go/src/github.com/elastic/beats/filebeat/input/filestream/internal/input-logfile/harvester_test.go:155 +0x18a
testing.tRunner(0xc00066aa80, 0xcfc760)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3
goroutine 50 [chan receive, 9 minutes]:
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.blockUntilCancelOnRun(0xc0005d17e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/elastic/beats/filebeat/input/filestream/internal/input-logfile/harvester_test.go:354 +0x4e
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*mockHarvester).Run(0xc0005d27a0, 0xc0005d17e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/elastic/beats/filebeat/input/filestream/internal/input-logfile/harvester_test.go:333 +0x19b
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.startHarvester.func1(0x7fee503e0f90, 0xc0005d5c00, 0x0, 0x0)
	/go/src/github.com/elastic/beats/filebeat/input/filestream/internal/input-logfile/harvester.go:204 +0x9a8
github.com/elastic/go-concert/unison.(*TaskGroup).Go.func1(0xc00066ead0, 0xc0005d5bc0)
	/go/pkg/mod/github.com/elastic/go-concert@v0.1.0/unison/taskgroup.go:124 +0x99
created by github.com/elastic/go-concert/unison.(*TaskGroup).Go
	/go/pkg/mod/github.com/elastic/go-concert@v0.1.0/unison/taskgroup.go:122 +0xda
goroutine 49 [sleep]:
time.Sleep(0x2dc6c0)
	/usr/local/go/src/runtime/time.go:193 +0xd2
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.TestDefaultHarvesterGroup.func5(0xc00066af00)
	/go/src/github.com/elastic/beats/filebeat/input/filestream/internal/input-logfile/harvester_test.go:170 +0x305
testing.tRunner(0xc00066af00, 0xc0005d1750)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3
```

Feel free to close if not appropiate

**Comment by urso** [comment]
@kvch Can you have a look?
