### ISSUE TITLE
Heartbeat test failing on CI

### ISSUE THREAD

**Issue by jalvz** [elastic/beats#26205]
Found in https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-25998/8/testReport/junit/github/com_elastic_beats_v7_heartbeat_scheduler_timerqueue/Extended___heartbeat_windows_7_32_windows_7_32_bit___TestQueueRunsInOrder/

Output:

```
=== RUN   TestQueueRunsInOrder
coverage: 81.4% of statements
panic: test timed out after 10m0s

goroutine 105 [running]:
testing.(*M).startAlarm.func1()
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/.gvm/versions/go1.16.4.windows.386/src/testing/testing.go:1700 +0xcb
created by time.goFunc
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/.gvm/versions/go1.16.4.windows.386/src/time/sleep.go:180 +0x37

goroutine 1 [chan receive]:
testing.(*T).Run(0x11030fc0, 0x5a4e6a, 0x14, 0x5b3e34, 0xf)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/.gvm/versions/go1.16.4.windows.386/src/testing/testing.go:1239 +0x239
testing.runTests.func1(0x11030ee0)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/.gvm/versions/go1.16.4.windows.386/src/testing/testing.go:1511 +0x5a
testing.tRunner(0x11030ee0, 0x1105bed0)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/.gvm/versions/go1.16.4.windows.386/src/testing/testing.go:1193 +0xc5
testing.runTests(0x110042c0, 0x6d7980, 0x2, 0x2, 0xd315ac6c, 0xc0267b02, 0xb2f62425, 0x8b, 0x6dc8a0, 0x5)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/.gvm/versions/go1.16.4.windows.386/src/testing/testing.go:1509 +0x25a
testing.(*M).Run(0x11100190, 0x0)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/.gvm/versions/go1.16.4.windows.386/src/testing/testing.go:1417 +0x178
main.main()
	_testmain.go:97 +0x162

goroutine 6 [chan receive]:
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.testQueueRunsInOrderOnce(0x11030fc0)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue_test.go:79 +0x199
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.TestQueueRunsInOrder(0x11030fc0)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue_test.go:33 +0x29
testing.tRunner(0x11030fc0, 0x5b3e34)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/.gvm/versions/go1.16.4.windows.386/src/testing/testing.go:1193 +0xc5
created by testing.(*T).Run
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/.gvm/versions/go1.16.4.windows.386/src/testing/testing.go:1238 +0x21a

goroutine 139 [runnable]:
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start.func1(0x11184820)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:74 +0x10a
created by github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:72 +0x49

goroutine 143 [runnable]:
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start.func1(0x11184960)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:74 +0x10a
created by github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:72 +0x49

goroutine 145 [runnable]:
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start.func1(0x11184a00)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:74 +0x10a
created by github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:72 +0x49

goroutine 179 [select]:
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start.func1(0x11184aa0)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:74 +0x10a
created by github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:72 +0x49

goroutine 180 [runnable]:
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start.func1.1(0x11187fc0, 0xa, 0x10, 0xd3ac1b5c, 0xc0267b02, 0xb3050a99, 0x8b, 0x6dc8a0)
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:82
created by github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start.func1
	C:/Users/jenkins/workspace/PR-25998-8-5339f7b2-56eb-40bb-b4f1-eb72d047ef3a/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:82 +0x19c
```

Feel free to close if not appropriate  / relevant.

**Comment by urso** [comment]
@andrewvc Can you have a look?

**Comment by andrewkroh** [comment]
I'm seeing the same failure on a PR at https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-26260/3/.

**Comment by andrewvc** [comment]
I'm taking a look now. This is very strange, this is a very old test, and no code has changed in a long time (1yr maybe?) Will dig in and see if there's a race.

**Comment by andrewvc** [comment]
I've spent quite a bit of time looking at this, and it seems to be very specific to windows, and quite likely a bug in the windows timer impl in golang. Though it's hard to say for sure. Will report back next week.

**Comment by andrewvc** [comment]
Is this failing enough that we should disable the test @jalvz / @andrewkroh ?

**Comment by jalvz** [comment]
I'm a very occasional contributor, only saw it once.

**Comment by kaiyan-sheng** [comment]
Thank you Andrew for disabling this test temporarily. This test also failed in 7.x branch for the last build: https://beats-ci.elastic.co/job/Beats/job/beats/job/7.x/lastFailedBuild/testReport/junit/github/com_elastic_beats_v7_heartbeat_scheduler_timerqueue/Build_Test___heartbeat_windows_windows_2019___TestQueueRunsInOrder/

**Comment by andrewvc** [comment]
@kaiyan-sheng it's been backported to 7.x as of this morning, so that shouldn't happen again (if you merge the latest 7.x in): https://github.com/elastic/beats/pull/26425

**Comment by mdelapenya** [comment]
I'm seeing this same error with a PR rebased with today's master: https://github.com/elastic/beats/pull/26209

CI job: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-26209/13/tests

Test error:
``` 
Stacktrace
=== RUN   TestQueueRunsInOrder
coverage: 79.1% of statements
panic: test timed out after 10m0s
goroutine 162 [running]:
testing.(*M).startAlarm.func1()
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/.gvm/versions/go1.16.5.linux.amd64/src/testing/testing.go:1700 +0xe5
created by time.goFunc
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/.gvm/versions/go1.16.5.linux.amd64/src/time/sleep.go:180 +0x45
goroutine 1 [chan receive]:
testing.(*T).Run(0xc000106600, 0x607664, 0x14, 0x615bd8, 0x4880c6)
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/.gvm/versions/go1.16.5.linux.amd64/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000106480)
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/.gvm/versions/go1.16.5.linux.amd64/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc000106480, 0xc000191da8)
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/.gvm/versions/go1.16.5.linux.amd64/src/testing/testing.go:1193 +0xef
testing.runTests(0xc000136138, 0x75bca0, 0x2, 0x2, 0xc02e850d04faf354, 0x8bb2dc17db, 0x765820, 0x6055fc)
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/.gvm/versions/go1.16.5.linux.amd64/src/testing/testing.go:1509 +0x2fe
testing.(*M).Run(0xc000188080, 0x0)
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/.gvm/versions/go1.16.5.linux.amd64/src/testing/testing.go:1417 +0x1eb
main.main()
	_testmain.go:97 +0x1c5
goroutine 19 [runnable]:
time.NewTimer(0x451093b66f00000, 0x1000)
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/.gvm/versions/go1.16.5.linux.amd64/src/time/sleep.go:86 +0xfe
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.NewTimerQueue(0x645f78, 0xc000094540, 0x645f78)
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:50 +0x67
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.testQueueRunsInOrderOnce(0xc000106600)
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue_test.go:44 +0x89
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.TestQueueRunsInOrder(0xc000106600)
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue_test.go:37 +0x35
testing.tRunner(0xc000106600, 0x615bd8)
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/.gvm/versions/go1.16.5.linux.amd64/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/var/lib/jenkins/workspace/PR-26209-13-ddcab0a4-7c79-45e4-aa83-31ef2705916c/.gvm/versions/go1.16.5.linux.amd64/src/testing/testing.go:1238 +0x2b3
```

**Comment by andrewvc** [comment]
Thanks for the ping, we'll temporarily skip this test today. Previously we'd only seen this issue on windows.
