### ISSUE TITLE
[Heartbeat] Scheduler segfault

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#26229]
This esoteric bug was spotted in CI. It's likely incredibly rare given that we haven't heard of it in > 1 year

```

<1s
Error
Failed
Stacktrace
=== RUN   TestQueueRunsInOrder
coverage: 79.1% of statements
panic: test timed out after 10m0s
goroutine 50 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1700 +0xe5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:180 +0x45
goroutine 1 [chan receive]:
testing.(*T).Run(0xc000001b00, 0x607664, 0x14, 0x615bd8, 0x4880c6)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000001980)
	/usr/local/go/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc000001980, 0xc0000dbda8)
	/usr/local/go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc00000e138, 0x751ca0, 0x2, 0x2, 0xc0284fa2854ca87e, 0x8bb2da4773, 0x75b820, 0x6055fc)
	/usr/local/go/src/testing/testing.go:1509 +0x2fe
testing.(*M).Run(0xc0000d2080, 0x0)
	/usr/local/go/src/testing/testing.go:1417 +0x1eb
main.main()
	_testmain.go:97 +0x1c5
goroutine 6 [runnable]:
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.testQueueRunsInOrderOnce(0xc000001b00)
	/go/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue_test.go:79 +0x228
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.TestQueueRunsInOrder(0xc000001b00)
	/go/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue_test.go:33 +0x35
testing.tRunner(0xc000001b00, 0x615bd8)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3
goroutine 48 [runnable]:
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start.func1(0xc00017a2c0)
	/go/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:74 +0x116
created by github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start
	/go/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:72 +0x4f
goroutine 66 [runnable]:
github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start.func1(0xc00017a400)
	/go/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:72
created by github.com/elastic/beats/v7/heartbeat/scheduler/timerqueue.(*TimerQueue).Start
	/go/src/github.com/elastic/beats/heartbeat/scheduler/timerqueue/queue.go:72 +0x4f
```

**Comment by andrewvc** [comment]
This was fixed with our change to stop using scheduler reset temporarily
