### ISSUE TITLE
[build] Functionbeat MSI signing is failing

### ISSUE THREAD

**Issue by kvch** [elastic/beats#27397]
Signing of Functionbeat MSIs has been failing with the following error:

```
09:39:59 INFO:sign-artifact.py:Repacking winlogbeat-oss-7.15.0-SNAPSHOT-windows-x86.zip ...
09:40:02 INFO:sign-artifact.py:Extracting files from C:\wsbeats\cd\release\release-manager\build\external-artifacts\downloads\beats\functionbeat\functionbeat-7.15.0-SNAPSHOT-windows-x86_64.zip
09:40:05 Traceback (most recent call last):
09:40:05   File "sign-artifact.py", line 260, in <module>
09:40:05     main()
09:40:05   File "sign-artifact.py", line 74, in main
09:40:05     run_command(args.command, args)
09:40:05   File "sign-artifact.py", line 79, in run_command
09:40:05     commands.get(cmd)(args, LOGGER)
09:40:05   File "sign-artifact.py", line 104, in run_sign
09:40:05     targets = unpack_archives(input_zip, real_workdir, logger)
09:40:05   File "sign-artifact.py", line 129, in unpack_archives
09:40:05     extracted_file = zip.extract(zip_item, work_dir)
09:40:05   File "c:\python38\lib\zipfile.py", line 1629, in extract
09:40:05     return self._extract_member(member, path, pwd)
09:40:05   File "c:\python38\lib\zipfile.py", line 1696, in _extract_member
09:40:05     os.mkdir(targetpath)
09:40:05 FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\wsbeats\\cd\\release\\windows-artifact-signer\\workdir\\beats\\estc\\functionbeat\\functionbeat-7.15.0-SNAPSHOT-windows-x86_64\\pkg\\pubsub\\vendor\\github.com\\elastic\\beats\\v7\\libbeat\\metric\\system\\cgroup\\testdata\\docker\\sys\\fs\\cgroup\\blkio\\docker\\b29faf21b7eff959f64b4192c34d5d67a707fe8561e9eaa608cb27693fba4242'
```

It seems that some files in the vendor folder we generate have too long paths for Windows. We have to investigate if we can either shorten the paths or get rid of the dependency. Or some third option if all else fails.

**Comment by kvch** [comment]
Builder machines were adjusted. No further action needed from us. Thanks @Conky5

**Comment by ruflin** [comment]
@kvch Any chance you could share a bit more on what need to be adjusted? So in case it happens again, we know how to fix.

**Comment by kvch** [comment]
The variable `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` set to 1 and the Windows builder machine was rebooted.

Ref: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd
