### ISSUE TITLE
heartbeat: panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by drewr** [elastic/beats#2746]
Trying heartbeat 614b05e7ef881269f12f75c54bb1c409a33a4162.  Works ok on my local 5.0, but really needed it on our Cloud pingbeat cluster for availability (2.3.1), which doesn't yet expose 5.0.  Not sure if we support pre-5.0 clusters, but in case we wanted to, figured I'd log this. 

```
2016/10/11 01:56:02.935339 scheduler.go:208: DBG  Job 'facebook-ssl@www.facebook.com:443' returned at 2016-10-10 20:56:02.935323838 -0500 CDT (cont=0).
2016/10/11 01:56:02.935358 scheduler.go:237: DBG  start 3 waiting tasks
2016/10/11 01:56:02.935373 asm_amd64.s:480: DBG  Scheduler stopped.
panic: runtime error: slice bounds out of range

goroutine 40 [running]:
panic(0x4cfac0, 0xc420014180)
	/Users/aar/src/go/src/runtime/panic.go:500 +0x1a1
github.com/elastic/beats/heartbeat/scheduler.(*Scheduler).run(0xc420194a80)
	/Users/aar/src/golib/src/github.com/elastic/beats/heartbeat/scheduler/scheduler.go:238 +0xfc1
created by github.com/elastic/beats/heartbeat/scheduler.(*Scheduler).Start
	/Users/aar/src/golib/src/github.com/elastic/beats/heartbeat/scheduler/scheduler.go:96 +0xbc
```

heartbeat.yml:

```
heartbeat.monitors:
- type: tcp
  name: facebook
  #enabled: true
  schedule: '@every 14s'
  hosts: ["ssl://www.facebook.com:443"]
  ipv4: true
  ipv6: true
  mode: any
heartbeat.scheduler:
  limit: 3
output.elasticsearch:
  hosts: ["localhost:9200", "https://admin:xxxxxxxxxx@f70229faaaeb656f7784d95b935cd550.us-east-1.aws.found.io:9243"]
logging.level: debug
logging.selectors: ["*"]
```

**Comment by drewr** [comment]
This actually may not be an ES version issue.  I took the 2.3.1 cluster out of the rotation, leaving only 5.0, and got the same error again.

**Comment by drewr** [comment]
Removing this makes it work again.
```
heartbeat.scheduler:
  limit: 3
```

**Comment by tsg** [comment]
@drewr Is that workaround acceptable for now? Because @urso is on vacation this week.
