### ISSUE TITLE
Filebeat7.15 Start error label:<bug> bug:<bug>  <bug> 

### ISSUE THREAD

**Issue by xqm1991** [elastic/beats#28112]
or confirmed bugs, please report:

Version: 7.15

Operating System: Linux linux-7eon 2.6.16.60-0.21-smp I can't install packetbeat #1 SMP Tue May 6 12:41:02 UTC 2008 x86_64 x86_64 x86_64 GNU/Linux

Discuss Forum URL: -

Steps to Reproduce:
i run shell for this:
sudo ./filebeat -e -c filebeat.yml

os console sysout for :
futexwakeup addr=0x608d428 returned -38
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1006 pc=0x165411b]

runtime stack:
runtime.throw(0x3da70ad, 0x2a)
/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:679 +0x46a
runtime.futexwakeup(0x608d428, 0x2b0c00000001)
/usr/local/go/src/runtime/os_linux.go:69 +0x8b
runtime.notewakeup(0x608d428)
/usr/local/go/src/runtime/lock_futex.go:136 +0x42
runtime.startlockedm(0xc000000180)
/usr/local/go/src/runtime/proc.go:2006 +0x7d
runtime.schedule()
/usr/local/go/src/runtime/proc.go:2563 +0x69
runtime.park_m(0xc000001080)
/usr/local/go/src/runtime/proc.go:2696 +0x9d
runtime.mcall(0x800000)
/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [chan receive, locked to thread]:
runtime.gopark(0x3ec63f0, 0xc0000ac058, 0x170e, 0x2)
/usr/local/go/src/runtime/proc.go:304 +0xe0
runtime.chanrecv(0xc0000ac000, 0x0, 0xc000000101, 0x1630101)
/usr/local/go/src/runtime/chan.go:525 +0x2e7
runtime.chanrecv1(0xc0000ac000, 0x0)
/usr/local/go/src/runtime/chan.go:407 +0x2b
runtime.gcenable()
/usr/local/go/src/runtime/mgc.go:217 +0xac
runtime.main()
/usr/local/go/src/runtime/proc.go:166 +0x115
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1

**Comment by xqm1991** [comment]
> 

- 

1.

**Comment by xqm1991** [comment]
@7.15-candidate

**Comment by xqm1991** [comment]
Team:<test>
