### ISSUE TITLE
beats/dev-tools/deploy fails

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/beats#29375]
```
Make[1]: Leaving directory '/home/steph/go/src/github.com/elastic/beats/x-pack/packetbeat'
make[1]: Entering directory '/home/steph/go/src/github.com/elastic/beats/x-pack/libbeat'
Makefile:12: warning: overriding recipe for target 'update'
../../libbeat/scripts/Makefile:350: warning: ignoring old recipe for target 'update'
Makefile:12: warning: overriding recipe for target 'fields'
../../libbeat/scripts/Makefile:341: warning: ignoring old recipe for target 'fields'
Makefile:12: warning: overriding recipe for target 'config'
../../libbeat/scripts/Makefile:345: warning: ignoring old recipe for target 'config'
/home/steph/.magefile cleaned
make[1]: Leaving directory '/home/steph/go/src/github.com/elastic/beats/x-pack/libbeat'
make[1]: *** generator: No such file or directory.  Stop.
make: *** [Makefile:89: clean] Error 2
Traceback (most recent call last):
  File "./deploy", line 25, in <module>
    main()
  File "./deploy", line 16, in main
    check_call("make clean", shell=True)
  File "/home/steph/Applications/miniconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make clean' returned non-zero exit status 2.
```

For confirmed bugs, please report:
- Version: 7.15
- Operating System: Linux, Ubuntu 20.04
- Discuss Forum URL:
- Steps to Reproduce: git clone..., make

**Comment by svanschalkwyk** [comment]
CLOSED: make sure 
``` make update ``` is run beforehand
