### ISSUE TITLE
[Heartbeat] concurrent map writes panic at startup

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#29580]
Heartbeat 7.16.2 panicked during startup due to `concurrent map writes`.

For confirmed bugs, please report:
- Version: docker.elastic.co/beats/heartbeat:7.16.2
- Operating System: Docker on linux/arm64
- Steps to Reproduce: I only observed this once so it's probably a race condition.

1. Start heartbeat.
2. It panics and exits.

Full Log: [heartbeat-7.16.2-panic.txt](https://github.com/elastic/beats/files/7763239/heartbeat-7.16.2-panic.txt)

```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 335 [running]:
runtime.throw({0x5589613da0, 0x15})
	/usr/local/go/src/runtime/panic.go:1198 +0x54 fp=0x4000b0e2c0 sp=0x4000b0e290 pc=0x55879e5564
runtime.mapassign_faststr(0x558a000580, 0x4000bba330, {0x55895f96fd, 0xa})
	/usr/local/go/src/runtime/map_faststr.go:294 +0x3d0 fp=0x4000b0e330 sp=0x4000b0e2c0 pc=0x55879c0c50
net/textproto.MIMEHeader.Set(...)
	/usr/local/go/src/net/textproto/header.go:22
net/http.Header.Set(...)
	/usr/local/go/src/net/http/header.go:38
github.com/elastic/beats/v7/libbeat/common/transport/httpcommon.(*headerRoundTripper).RoundTrip(0x40003eca50, 0x4000696a00)
	/go/src/github.com/elastic/beats/libbeat/common/transport/httpcommon/httpcommon.go:145 +0x154 fp=0x4000b0e410 sp=0x4000b0e330 pc=0x5588247ef4
net/http.send(0x4000696700, {0x558a2a1580, 0x40003eca50}, {0xc068eb0c0a49e6c5, 0x4b2d2d7a1, 0x558bb6c9e0})
	/usr/local/go/src/net/http/client.go:252 +0x5c4 fp=0x4000b0e600 sp=0x4000b0e410 pc=0x5587cf17c4
net/http.(*Client).send(0x4000ab9b90, 0x4000696700, {0xc068eb0c0a49e6c5, 0x4b2d2d7a1, 0x558bb6c9e0})
	/usr/local/go/src/net/http/client.go:176 +0xa4 fp=0x4000b0e680 sp=0x4000b0e600 pc=0x5587cf1074
net/http.(*Client).do(0x4000ab9b90, 0x4000696700)
	/usr/local/go/src/net/http/client.go:725 +0x858 fp=0x4000b0e870 sp=0x4000b0e680 pc=0x5587cf3408
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:593
github.com/elastic/beats/v7/heartbeat/monitors/active/http.execRequest(0x4000ab9b90, 0x4000696700)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:307 +0x50 fp=0x4000b0e8d0 sp=0x4000b0e870 pc=0x558905f200
github.com/elastic/beats/v7/heartbeat/monitors/active/http.execPing(0x400033b440, 0x4000ab9b90, 0x4000b90300, {0x0, 0x0, 0x0}, 0x3b9aca000, {{0x4000012d88, 0x1, 0x1}, ...}, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:232 +0xd4 fp=0x4000b0ef20 sp=0x4000b0e8d0 pc=0x558905e4a4
github.com/elastic/beats/v7/heartbeat/monitors/active/http.createPingFactory.func1(0x400033b440, 0x400055cd50)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:166 +0x688 fp=0x4000b0f2b0 sp=0x4000b0ef20 pc=0x558905d578
github.com/elastic/beats/v7/heartbeat/monitors.MakePingIPFactory.func1.1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:91 +0x38 fp=0x4000b0f2e0 sp=0x4000b0f2b0 pc=0x55881f06b8
github.com/elastic/beats/v7/heartbeat/monitors.MakeSimpleCont.func1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:80 +0x30 fp=0x4000b0f310 sp=0x4000b0f2e0 pc=0x55881f0520
github.com/elastic/beats/v7/heartbeat/monitors/wrappers.Fields.func1.1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/wrappers/util.go:40 +0x38 fp=0x4000b0f380 sp=0x4000b0f310 pc=0x5587ffd6e8
github.com/elastic/beats/v7/heartbeat/monitors/jobs.Wrap.func1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/jobs/job.go:72 +0x48 fp=0x4000b0f400 sp=0x4000b0f380 pc=0x5587ff08b8
github.com/elastic/beats/v7/heartbeat/monitors/wrappers.Fields.func1.1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/wrappers/util.go:40 +0x38 fp=0x4000b0f470 sp=0x4000b0f400 pc=0x5587ffd6e8
github.com/elastic/beats/v7/heartbeat/monitors/jobs.Wrap.func1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/jobs/job.go:72 +0x48 fp=0x4000b0f4f0 sp=0x4000b0f470 pc=0x5587ff08b8
github.com/elastic/beats/v7/heartbeat/monitors/wrappers.addMonitorMeta.func1.1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/wrappers/monitors.go:77 +0x40 fp=0x4000b0f5d0 sp=0x4000b0f4f0 pc=0x5587ffbf90
github.com/elastic/beats/v7/heartbeat/monitors/jobs.Wrap.func1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/jobs/job.go:72 +0x48 fp=0x4000b0f650 sp=0x4000b0f5d0 pc=0x5587ff08b8
github.com/elastic/beats/v7/heartbeat/monitors/wrappers.addMonitorStatus.func1.1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/wrappers/monitors.go:149 +0x38 fp=0x4000b0f820 sp=0x4000b0f650 pc=0x5587ffe008
github.com/elastic/beats/v7/heartbeat/monitors/jobs.Wrap.func1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/jobs/job.go:72 +0x48 fp=0x4000b0f8a0 sp=0x4000b0f820 pc=0x5587ff08b8
github.com/elastic/beats/v7/heartbeat/monitors/wrappers.addMonitorDuration.func1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/wrappers/monitors.go:170 +0x5c fp=0x4000b0fa90 sp=0x4000b0f8a0 pc=0x5587ffcb1c
github.com/elastic/beats/v7/heartbeat/monitors/jobs.Wrap.func1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/jobs/job.go:72 +0x48 fp=0x4000b0fb10 sp=0x4000b0fa90 pc=0x5587ff08b8
github.com/elastic/beats/v7/heartbeat/monitors/wrappers.makeAddSummary.func2.1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/wrappers/monitors.go:216 +0x68 fp=0x4000b0fd10 sp=0x4000b0fb10 pc=0x5587ffcfe8
github.com/elastic/beats/v7/heartbeat/monitors/jobs.Wrap.func1(0x400033b440)
	/go/src/github.com/elastic/beats/heartbeat/monitors/jobs/job.go:72 +0x48 fp=0x4000b0fd90 sp=0x4000b0fd10 pc=0x5587ff08b8
github.com/elastic/beats/v7/heartbeat/monitors.runPublishJob(0x4000bce420, 0x400021bda0)
	/go/src/github.com/elastic/beats/heartbeat/monitors/task.go:109 +0x7c fp=0x4000b0feb0 sp=0x4000b0fd90 pc=0x55881f00cc
github.com/elastic/beats/v7/heartbeat/monitors.runPublishJob.func1({0x558a2ed518, 0x4000051e40})
	/go/src/github.com/elastic/beats/heartbeat/monitors/task.go:145 +0x30 fp=0x4000b0fef0 sp=0x4000b0feb0 pc=0x55881f03c0
github.com/elastic/beats/v7/heartbeat/scheduler.(*schedJob).runTask(0x40000b14f0, 0x4000bce480)
	/go/src/github.com/elastic/beats/heartbeat/scheduler/schedjob.go:105 +0x218 fp=0x4000b0ffb0 sp=0x4000b0fef0 pc=0x5587ff2a68
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1133 +0x4 fp=0x4000b0ffb0 sp=0x4000b0ffb0 pc=0x5587a1c994
created by github.com/elastic/beats/v7/heartbeat/scheduler.(*schedJob).runTask
	/go/src/github.com/elastic/beats/heartbeat/scheduler/schedjob.go:114 +0x384
```

```
heartbeat.config.monitors:
  path: /local/monitors.d/*.yml # Points to several ICMP and HTTP monitors.
  reload.enabled: true
  reload.period: 1s

fields_under_root: true
fields:
  observer:
    name: 'FOO'
    hostname: 'FOO'
    ip:
      - '1.2.3.4'
    vendor: Elastic
    product: Heartbeat
  nomad:
    allocation:
      id: 'FOO'

processors:
- add_cloud_metadata: ~

logging.json: true
logging.ecs: true

http.host: 0.0.0.0
http.port: '${NOMAD_HOST_PORT_metrics:}'

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
```

**Comment by andrewvc** [comment]
Fixed in https://github.com/elastic/beats/pull/29697
