### ISSUE TITLE
Agent [master]: dev, snapshot build crashes on start on Windows 

### ISSUE THREAD

**Issue by aleksmaus** [elastic/beats#30315]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: master branch (commit a1bf996c72bc51ab4fba22a40e2acaffd21f6176), DEV, SNAPSHOT build
- Operating System: Windows 10
- Steps to Reproduce: Start the agent, observe the crash 

```
PS C:\work\elastic-agent-7.16.3-SNAPSHOT-windows-x86_64> .\elastic-agent.exe -e
{"log.level":"info","@timestamp":"2022-02-09T15:27:24.431-0500","log.origin":{"file.name":"cmd/run.go","file.line":126},"message":"Artifact has been built with security disabled. Elastic Agent will not verify signatures of the artifacts.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-02-09T15:27:24.443-0500","log.origin":{"file.name":"application/application.go","file.line":68},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-02-09T15:27:24.444-0500","log.origin":{"file.name":"application/application.go","file.line":92},"message":"Agent is managed by Fleet","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-02-09T15:27:24.444-0500","log.origin":{"file.name":"capabilities/capabilities.go","file.line":59},"message":"capabilities file not found in C:\\work\\elastic-agent-7.16.3-SNAPSHOT-windows-x86_64\\capabilities.yml","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-02-09T15:27:24.777-0500","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":43},"message":"Docker provider skipped, unable to connect: protocol not available","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-02-09T15:27:24.785-0500","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":62},"message":"Starting stats endpoint","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-02-09T15:27:24.785-0500","log.origin":{"file.name":"application/managed_mode.go","file.line":290},"message":"Agent is starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-02-09T15:27:24.785-0500","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":64},"message":"Metrics endpoint listening on: \\\\.\\pipe\\elastic-agent (configured: npipe:///elastic-agent)","ecs.version":"1.6.0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x14bae42]

goroutine 13 [running]:
github.com/elastic/beats/v7/libbeat/common/transport.tlsDialWith({0x2a55f20, 0x3a80e00}, {0x2a06ea0, 0xc0003b0980}, {0x278782d, 0x2030000}, {0xc0006d7aa0, 0x2030000}, 0x1bf08eb000, 0xc0000f5380, ...)
        /go/src/github.com/elastic/beats/libbeat/common/transport/tls.go:164 +0x182
github.com/elastic/beats/v7/libbeat/common/transport.TestTLSDialer.func1({0x278782d, 0x3}, {0xc0006d7aa0, 0x120})
        /go/src/github.com/elastic/beats/libbeat/common/transport/tls.go:72 +0x385
github.com/elastic/beats/v7/libbeat/common/transport.DialerFunc.Dial(0x100000000000060, {0x278782d, 0x118}, {0xc0006d7aa0, 0x14b21970108})
        /go/src/github.com/elastic/beats/libbeat/common/transport/transport.go:38 +0x33
net/http.(*Transport).customDialTLS(0xc00010d320, {0x2a38ff8, 0xc00010d320}, {0x278782d, 0x0}, {0xc0006d7aa0, 0x5})
        /usr/local/go/src/net/http/transport.go:1316 +0x6b
net/http.(*Transport).dialConn(0xc00073fa40, {0x2a38ff8, 0xc00010d320}, {{}, 0x0, {0xc0008a42d0, 0x5}, {0xc0006d7aa0, 0x1c}, 0x0})
        /usr/local/go/src/net/http/transport.go:1580 +0x3ff
net/http.(*Transport).dialConnFor(0xc0001100c0, 0xc0006506e0)
        /usr/local/go/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
        /usr/local/go/src/net/http/transport.go:1415 +0x3d7
 ```
 
 looks like config is nil on this line
 https://github.com/elastic/beats/commit/e208c22507890eb3633d55f1ba7d388f3076b2d6#diff-78433e68076d1f328ffe63cecdcea0f215f2902c5edc90024f2400b43b939f2fR164

**Comment by cmacknz** [comment]
Reverting https://github.com/elastic/beats/pull/30063 temporarily will only affect log messages if we want to get main working again quickly. 

I am also very curious how no tests caught this problem.

**Comment by cmacknz** [comment]
I'm also curious if this affects branches other than main, or just main.

**Comment by ph** [comment]
Thanks @cmacknz for looking into this.

**Comment by cmacknz** [comment]
This went into the 8.0 branch scheduled for release tomorrow, probably we'll have to revert this change and re-target it into v8.0.1.

**Comment by ph** [comment]
+1 to revert.

**Comment by cmacknz** [comment]
We are fortunate, the backports for 8.0 and 7.17 aren't merged yet.

- 7.17: https://github.com/elastic/beats/pull/30301#pullrequestreview-878066776
- 8.0: https://github.com/elastic/beats/pull/30302#pullrequestreview-878066399

**Comment by belimawr** [comment]
> I am very curious about how no tests caught this problem.

Me too. I did a quick test and if one just setup the cloud output it already breaks, for filebeat:
 ```yaml

# You can find the `cloud.id` in the Elastic Cloud web UI.
cloud.id: "<my cloud ID>"

# The cloud.auth setting overwrites the `output.elasticsearch.username` and
# `output.elasticsearch.password` settings. The format is `<user>:<pass>`.
cloud.auth: "elastic:please-change-me"
```

It seems like anything that uses SSL but does not explicitly add it to the config and goes through this code path might break.

I'll make a fix for the issue soon, but we should think on how to improve our testing to catch things like that.

**Comment by mtojek** [comment]
@jsoriano found that we hit it also with elastic-package.

[Pipeline job
](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package/detail/PR-693/2)[Fleet Server logs](https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-693/2/artifact/build/elastic-stack-dump/stack/8.2.0-SNAPSHOT/logs/fleet-server.log)

```
Attaching to elastic-package-stack_fleet-server_1
[36mfleet-server_1               |[0m Performing setup of Fleet in Kibana
[36mfleet-server_1               |[0m 
[36mfleet-server_1               |[0m {"log.level":"info","@timestamp":"2022-02-09T18:30:20.813Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":572},"message":"Spawning Elastic Agent daemon as a subprocess to complete bootstrap process.","ecs.version":"1.6.0"}
[36mfleet-server_1               |[0m {"log.level":"info","@timestamp":"2022-02-09T18:30:20.999Z","log.origin":{"file.name":"application/application.go","file.line":68},"message":"Detecting execution mode","ecs.version":"1.6.0"}
[36mfleet-server_1               |[0m {"log.level":"info","@timestamp":"2022-02-09T18:30:21.000Z","log.origin":{"file.name":"application/application.go","file.line":88},"message":"Agent is in Fleet Server bootstrap mode","ecs.version":"1.6.0"}
[36mfleet-server_1               |[0m {"log.level":"info","@timestamp":"2022-02-09T18:30:21.265Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":62},"message":"Starting stats endpoint","ecs.version":"1.6.0"}
[36mfleet-server_1               |[0m {"log.level":"info","@timestamp":"2022-02-09T18:30:21.265Z","log.origin":{"file.name":"application/fleet_server_bootstrap.go","file.line":131},"message":"Agent is starting","ecs.version":"1.6.0"}
[36mfleet-server_1               |[0m {"log.level":"info","@timestamp":"2022-02-09T18:30:21.265Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":64},"message":"Metrics endpoint listening on: /usr/share/elastic-agent/state/data/tmp/elastic-agent.sock (configured: unix:///usr/share/elastic-agent/state/data/tmp/elastic-agent.sock)","ecs.version":"1.6.0"}
[36mfleet-server_1               |[0m {"log.level":"info","@timestamp":"2022-02-09T18:30:21.269Z","log.origin":{"file.name":"application/fleet_server_bootstrap.go","file.line":141},"message":"Agent is stopped","ecs.version":"1.6.0"}
[36mfleet-server_1               |[0m panic: runtime error: invalid memory address or nil pointer dereference
[36mfleet-server_1               |[0m [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5614cc0a73c2]
[36mfleet-server_1               |[0m 
[36mfleet-server_1               |[0m goroutine 123 [running]:
[36mfleet-server_1               |[0m github.com/elastic/beats/v7/libbeat/common/transport.tlsDialWith({0x5614cd930110, 0x5614ce9a90a0}, {0x5614cd8ddd00, 0xc00043ac20}, {0x5614ccf7747d, 0xc0000c55c0}, {0xc00039cd20, 0x0}, 0x1bf08eb000, 0xc000175500, ...)
[36mfleet-server_1               |[0m 	/go/src/github.com/elastic/beats/libbeat/common/transport/tls.go:164 +0x182
[36mfleet-server_1               |[0m github.com/elastic/beats/v7/libbeat/common/transport.TestTLSDialer.func1({0x5614ccf7747d, 0x3}, {0xc00039cd20, 0x120})
[36mfleet-server_1               |[0m 	/go/src/github.com/elastic/beats/libbeat/common/transport/tls.go:72 +0x385
[36mfleet-server_1               |[0m github.com/elastic/beats/v7/libbeat/common/transport.DialerFunc.Dial(0x100000000000060, {0x5614ccf7747d, 0x118}, {0xc00039cd20, 0x7fb5a3d4d108})
[36mfleet-server_1               |[0m 	/go/src/github.com/elastic/beats/libbeat/common/transport/transport.go:38 +0x33
[36mfleet-server_1               |[0m net/http.(*Transport).customDialTLS(0xc0000c5320, {0x5614cd912958, 0xc0000c5320}, {0x5614ccf7747d, 0x0}, {0xc00039cd20, 0x0})
[36mfleet-server_1               |[0m 	/usr/local/go/src/net/http/transport.go:1316 +0x6b
[36mfleet-server_1               |[0m net/http.(*Transport).dialConn(0xc00012a500, {0x5614cd912958, 0xc0000c5320}, {{}, 0x0, {0xc0000d6d20, 0x5}, {0xc00039cd20, 0x1c}, 0x0})
[36mfleet-server_1               |[0m 	/usr/local/go/src/net/http/transport.go:1580 +0x3ff
[36mfleet-server_1               |[0m net/http.(*Transport).dialConnFor(0x0, 0xc00024b290)
[36mfleet-server_1               |[0m 	/usr/local/go/src/net/http/transport.go:1446 +0xb0
[36mfleet-server_1               |[0m created by net/http.(*Transport).queueForDial
[36mfleet-server_1               |[0m 	/usr/local/go/src/net/http/transport.go:1415 +0x3d7
[36mfleet-server_1               |[0m Error: fleet-server failed: spawned Elastic Agent exited unexpectedly: exit status 2
[36mfleet-server_1               |[0m For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.2/fleet-troubleshooting.html
[36mfleet-server_1               |[0m Error: enrollment failed: exit status 1
[36mfleet-server_1               |[0m For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.2/fleet-troubleshooting.html
```

**Comment by jlind23** [comment]
@belimawr @cmacknz let us this issue to talk about TLS testing: https://github.com/elastic/beats/issues/12601

**Comment by belimawr** [comment]
I created a draft PR with the original changes + the fix: https://github.com/elastic/beats/pull/30331

We probably should discuss some testing strategies before merging it.

**Comment by simitt** [comment]
The issue also breaks the cloud setup https://github.com/elastic/obs-dc-team/issues/708.

**Comment by ph** [comment]
Is that possible that the original PR at https://github.com/elastic/beats/pull/30063 was targetting 8.0 and 8.2 but not 8.1?

**Comment by cmacknz** [comment]
The original PR was created 2w ago (Feb 2nd) but was only merged to main yesterday (Feb 9th). The date the PR was opened was around the time the 8.1 branch was created. It isn't in the 8.0 or 8.1 branches.

**Comment by belimawr** [comment]
I merged the reverted commit + its fix on `main`, so I'm closing this issue.
