### ISSUE TITLE
Missing TLS configuration causes agent crash on Windows

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#30314]
The agent crashes at startup on the main branch when run on Windows because of a `nil` TLS configuration. The specific line of code causing the crash is:
https://github.com/elastic/beats/blob/e208c22507890eb3633d55f1ba7d388f3076b2d6/libbeat/common/transport/tls.go#L164

Known to happen on main but may affect other versions.

Stack trace:
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x14bae42]

goroutine 13 [running]:
github.com/elastic/beats/v7/libbeat/common/transport.tlsDialWith({0x2a55f20, 0x3a80e00}, {0x2a06ea0, 0xc0003b0980}, {0x278782d, 0x2030000}, {0xc0006d7aa0, 0x2030000}, 0x1bf08eb000, 0xc0000f5380, ...)
        /go/src/github.com/elastic/beats/libbeat/common/transport/tls.go:164 +0x182
github.com/elastic/beats/v7/libbeat/common/transport.TestTLSDialer.func1({0x278782d, 0x3}, {0xc0006d7aa0, 0x120})
        /go/src/github.com/elastic/beats/libbeat/common/transport/tls.go:72 +0x385
github.com/elastic/beats/v7/libbeat/common/transport.DialerFunc.Dial(0x100000000000060, {0x278782d, 0x118}, {0xc0006d7aa0, 0x14b21970108})
        /go/src/github.com/elastic/beats/libbeat/common/transport/transport.go:38 +0x33
net/http.(*Transport).customDialTLS(0xc00010d320, {0x2a38ff8, 0xc00010d320}, {0x278782d, 0x0}, {0xc0006d7aa0, 0x5})
        /usr/local/go/src/net/http/transport.go:1316 +0x6b
net/http.(*Transport).dialConn(0xc00073fa40, {0x2a38ff8, 0xc00010d320}, {{}, 0x0, {0xc0008a42d0, 0x5}, {0xc0006d7aa0, 0x1c}, 0x0})
        /usr/local/go/src/net/http/transport.go:1580 +0x3ff
net/http.(*Transport).dialConnFor(0xc0001100c0, 0xc0006506e0)
        /usr/local/go/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
        /usr/local/go/src/net/http/transport.go:1415 +0x3d7
```

**Comment by cmacknz** [comment]
Duplicates https://github.com/elastic/beats/issues/30315
