### ISSUE TITLE
[Build] The `linter:all` mage target isn't working on Apple M1

### ISSUE THREAD

**Issue by amannocci** [elastic/beats#31300]
#### Description
The `linter:all` mage target exited with an error on Apple M1.
```bash
❯ mage linter:all
golangci/golangci-lint info checking GitHub for tag 'v1.44.0'
golangci/golangci-lint info found version: 1.44.0 for v1.44.0/darwin/arm64
golangci/golangci-lint info installed build/golangci-lint
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
	github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x52c
Error: running "./build/golangci-lint run -c ./.golangci.yml ./..." failed with exit code 2
```

It seems that this is a known issue https://github.com/golangci/golangci-lint/issues/2673.
Maybe we should consider a version bump to v1.45.2 to solve it.

**Comment by amannocci** [comment]
Solved by https://github.com/elastic/beats/commit/eacde0d0f0bec60e00e8066d7076f13c9dddaf42
