### ISSUE TITLE
go-fuzz: out of memory (mongodb_parser.go)

### ISSUE THREAD

**Issue by darxriggs** [elastic/beats#315]
Using https://github.com/dvyukov/go-fuzz an error was found in `mongodb_parser.go` (packetbeat 27eb706ebb22166f50e889e4cc0de854db08afe0).

Program to reproduce
```
package main

import (
        "flag"
        "fmt"
	"os"

	"github.com/elastic/libbeat/logp"

	"github.com/elastic/packetbeat/config"
	"github.com/elastic/packetbeat/decoder"
	"github.com/elastic/packetbeat/protos"
	"github.com/elastic/packetbeat/protos/mongodb"
	"github.com/elastic/packetbeat/protos/tcp"
	"github.com/elastic/packetbeat/protos/udp"

	"github.com/tsg/gopacket"
	"github.com/tsg/gopacket/layers"
)

func main() {
    flag.Parse()

    err := logp.Init("bugs", &logp.Logging{})
    if err != nil {
        fmt.Printf("Error initializing logging: %v\n", err)
        os.Exit(1)
    }

    data := []byte(
        "0\x840000000000\b\x00E000\x01\xc0" +
        "@\x000\x06\xb6\x8b\xac\x11\x00\a\xac\x11*\x01i\x89\xdc\x15a9" +
        "\x8a\xcc\xc9\xcawA\x80\x18\x00\xf3\x82\x9f\x00\x00\x01\x01\b\n\x00I" +
        "\x92r\x00I\x92rN\x00\x00\x00|\x00\x00\x00\x16\x00\x00\x00\x01\x00" +
        "\x00\x00\b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00" +
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")

    packet := gopacket.NewPacket(data, layers.LinkTypeEthernet, gopacket.Default)
	decoder := newTestDecoder()
	decoder.DecodePacketData(packet.Data(), &packet.Metadata().CaptureInfo)
}

func newTestDecoder() *decoder.DecoderStruct {
	for proto, plugin := range EnabledProtocolPlugins {
		err := plugin.Init(false, nil)
		if err != nil {
			logp.Critical("Initializing plugin %s failed: %v", proto, err)
			os.Exit(1)
		}
		protos.Protos.Register(proto, plugin)
	}

	var err error

	tcpProc, err := tcp.NewTcp(&protos.Protos)
	if err != nil {
		logp.Critical(err.Error())
		os.Exit(1)
	}

	udpProc, err := udp.NewUdp(&protos.Protos)
	if err != nil {
		logp.Critical(err.Error())
		os.Exit(1)
	}

	decoder, err := decoder.NewDecoder(layers.LinkTypeEthernet, tcpProc, udpProc)
	if err != nil {
		logp.Critical(err.Error())
		os.Exit(1)
	}

	return decoder
}

var EnabledProtocolPlugins map[protos.Protocol]protos.ProtocolPlugin = map[protos.Protocol]protos.ProtocolPlugin{
	protos.MongodbProtocol: new(mongodb.Mongodb),
}

func init() {
	config.ConfigSingleton = config.Config{
		Protocols: config.Protocols{
			Mongodb: config.Mongodb{
				Ports: []int{27017},
			},
		},
	}
}
```

Output

```
mongodb.go:73: DBG  Init a MongoDB protocol parser
tcp.go:211: DBG  Port map: map[27017:mongodb]
udp.go:93: DBG  Port map: map[]
decoder.go:37: DBG  Layer type: Ethernet
decoder.go:89: DBG  IPv4 packet
decoder.go:103: DBG  TCP packet
tcp.go:133: DBG  Stream doesn't exist, creating new
tcp.go:148: DBG  pkt.start_seq=1631161036 pkt.last_seq=1631161114 stream.last_seq=0 (len=78)
mongodb.go:99: DBG  Parse method triggered
mongodb_parser.go:46: DBG  opCode = OP_REPLY
mongodb_parser.go:91: DBG  Prepare to read 1633746944 document from reply
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x8cf580, 0x16)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sysMap(0xc821300000, 0x616100000, 0xaf5200, 0x1028778)
	/usr/local/go/src/runtime/mem_linux.go:143 +0x9b
runtime.mHeap_SysAlloc(0xaf5240, 0x616100000, 0xad6940)
	/usr/local/go/src/runtime/malloc.go:423 +0x160
runtime.mHeap_Grow(0xaf5240, 0x30b080, 0x0)
	/usr/local/go/src/runtime/mheap.go:628 +0x63
runtime.mHeap_AllocSpanLocked(0xaf5240, 0x30b080, 0x100)
	/usr/local/go/src/runtime/mheap.go:532 +0x5f1
runtime.mHeap_Alloc_m(0xaf5240, 0x30b080, 0xffffff0100000000, 0x7ffedfe080f8)
	/usr/local/go/src/runtime/mheap.go:425 +0x1ac
runtime.mHeap_Alloc.func1()
	/usr/local/go/src/runtime/mheap.go:484 +0x41
runtime.systemstack(0x7ffedfe08110)
	/usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.mHeap_Alloc(0xaf5240, 0x30b080, 0x10100000000, 0x413c5f)
	/usr/local/go/src/runtime/mheap.go:485 +0x63
runtime.largeAlloc(0x616100000, 0x7f9800000000, 0xc800000012)
	/usr/local/go/src/runtime/malloc.go:745 +0xb3
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:634 +0x33
runtime.systemstack(0xad6980)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc8211075e0 sp=0xc8211075d8
runtime.mallocgc(0x616100000, 0x729a60, 0x8e00000000000000, 0xc81ff6e35c)
	/usr/local/go/src/runtime/malloc.go:635 +0x9c4 fp=0xc8211076b0 sp=0xc8211075e0
runtime.newarray(0x729a60, 0x61610000, 0x86a4f8)
	/usr/local/go/src/runtime/malloc.go:777 +0xc9 fp=0xc8211076f0 sp=0xc8211076b0
runtime.makeslice(0x71c620, 0x61610000, 0x61610000, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc821107740 sp=0xc8211076f0
github.com/elastic/packetbeat/protos/mongodb.opReplyParse(0xc821107958, 0xc820098240, 0x8731a0)
	gopath/src/github.com/elastic/packetbeat/protos/mongodb/mongodb_parser.go:93 +0x3fd fp=0xc821107878 sp=0xc821107740
github.com/elastic/packetbeat/protos/mongodb.mongodbMessageParser(0xc821239440, 0xc820098240)
	gopath/src/github.com/elastic/packetbeat/protos/mongodb/mongodb_parser.go:54 +0x746 fp=0xc821107980 sp=0xc821107878
github.com/elastic/packetbeat/protos/mongodb.(*Mongodb).Parse(0xc820018550, 0xc821250000, 0xc820148298, 0xc820018501, 0x0, 0x0, 0x0, 0x0)
	gopath/src/github.com/elastic/packetbeat/protos/mongodb/mongodb.go:124 +0x35d fp=0xc821107a50 sp=0xc821107980
github.com/elastic/packetbeat/protos/tcp.(*TcpStream).addPacket(0xc820148280, 0xc821250000, 0xc82124e2f8, 0x1)
	gopath/src/github.com/elastic/packetbeat/protos/tcp/tcp.go:86 +0x213 fp=0xc821107b00 sp=0xc821107a50
github.com/elastic/packetbeat/protos/tcp.(*Tcp).Process(0xc821239320, 0xc82124e2f8, 0xc821250000)
	gopath/src/github.com/elastic/packetbeat/protos/tcp/tcp.go:165 +0xdb4 fp=0xc821107dc8 sp=0xc821107b00
github.com/elastic/packetbeat/decoder.(*DecoderStruct).DecodePacketData(0xc82124e000, 0xc8200142d0, 0x90, 0x90, 0xc8212420a0)
	gopath/src/github.com/elastic/packetbeat/decoder/decoder.go:136 +0x421 fp=0xc821107eb8 sp=0xc821107dc8
main.main()
	gopath/src/github.com/elastic/packetbeat/bugs/bug_mongodb.go:30 +0x1ac fp=0xc821107f50 sp=0xc821107eb8
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc821107fa0 sp=0xc821107f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc821107fa8 sp=0xc821107fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [select]:
github.com/elastic/libbeat/common.(*Cache).StartJanitor.func1(0xc820010780, 0xc820010a80)
	gopath/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/elastic/libbeat/common/cache.go:192 +0x102
created by github.com/elastic/libbeat/common.(*Cache).StartJanitor
	gopath/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/elastic/libbeat/common/cache.go:200 +0x91

goroutine 8 [running]:
	goroutine running on other thread; stack unavailable
created by github.com/elastic/libbeat/common.(*Cache).StartJanitor
	gopath/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/elastic/libbeat/common/cache.go:200 +0x91
exit status 2
godep: go exit status 1
```

**Comment by tsg** [comment]
That's cool, thanks for running go-fuzz and reporting this.

**Comment by ruflin** [comment]
@tsg should we add this to our test suite?

**Comment by urso** [comment]
@darxriggs I can not reproduce the error from sample program. Which input have you used to run go-fuzz? Why not create a PR for testing?

**Comment by darxriggs** [comment]
I am a bit short of time a the moment. I will have look at this later this week.

The reason why I didn't yet create a PR for fuzzy-testing is that currently requires patching a file. I will create a PR for fuzzy-testing later the week for discussion. Stay tuned.

**Comment by urso** [comment]
Just a side note: As I understand when running go-fuzz will not restart the process for every single run. For this reason go-fuzz should be mostly applied to side-effect free functions. I don't know how you've generated the sample, but in case you've send it through the decoder it's definitely not side-effect free. The TCP layer and the Transaction layer do allocate and hold stream information timing out only after some seconds (I think 10s by default). If go-fuzz generates enough distinct packets via fuzzing in very short time, the test might have acculumated quite some internal state in these layers, which makes it hard for me to judge the OOM being due to the test setup or due to a bug in the parser.

**Comment by monicasarbu** [comment]
Based on the feedback provided by @urso, I am closing the issue.
