### ISSUE TITLE
filebeat for s390x

### ISSUE THREAD

**Issue by bert2002** [elastic/beats#33106]
For confirmed bugs, please report:
- Version: v8.4.1
- Operating System: Debian Linux 10 

Hi, I am trying to build filebeat on a Debian 10 with the `s390x` architecture and the `mage package` is failing with the following python problem for `grpcio`:

```
      s390x-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/root/beatssrc/beats/build/ve/linux/include -I/usr/include/python3.7m -c /tmp/tmpstos5jfj/a.c -o None/tmp/tmpstos5jfj/a.o
      Traceback (most recent call last):
        File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
          extra_postargs)
        File "/tmp/pip-install-5ggsng8o/grpcio_ffa878145e1b4b8a851e1d54be5211f0/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/usr/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
          spawn(cmd, dry_run=self.dry_run)
        File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
          _spawn_posix(cmd, search_path, dry_run=dry_run)
        File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
          % (cmd, exit_status))
      distutils.errors.DistutilsExecError: command 's390x-linux-gnu-gcc' failed with exit status 1
      
```
Any experience why this is happening? I attached the full build log as well.

[build.txt](https://github.com/elastic/beats/files/9580588/build.txt)

I can build filebeat with `make` successfully, but would be great to use a proper package.

Thanks,
bert

**Comment by pierrehilbert** [comment]
Did you install build-essential and python-dev?
