### ISSUE TITLE
Filebeat: Azure blob lease release fails while stopping azureeventhub input

### ISSUE THREAD

**Issue by zmoog** [elastic/beats#33592]
- Version: 8.4.1
- Operating System: Linux

Here is the error reported by a user:

```
Sep 20 15:55:34 azslsprd04 /opt/Elastic/Agent/data/elastic-agent-8d7885/install/filebeat-8.4.1-linux-x86_64/filebeat[30233]: 2022/09/20 15:55:34 ==> REQUEST/RESPONSE (Try=1/19.4µs, OpTime=119.602µs) -- REQUEST ERROR

PUT https://prodappsnztaelk1.blob.core.windows.net/azure-eventhub-input-securitydata-eventhub/11?comp=lease&timeout=61
   Authorization: REDACTED
   User-Agent: [Azure-Storage/0.7 (go1.17.12; linux) 
   X-Ms-Client-Request-Id: [33474f96-f80f-4f54-56ad-29ab0870931b]
   X-Ms-Lease-Action: [release]
   X-Ms-Lease-Id: [a3e4616b-5bcf-45ba-bb7c-5bb07be9a550]
   X-Ms-Version : [2018-11-09]
   x-ms-date: [Tue, 20 Sep 2022 03:55:33 GMT]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
HTTP request failed

Put "https://{{REDACTED}}.blob.core.windows.net/azure-eventhub-input-securitydata-eventhub/11?comp=lease&timeout=61": context canceled

goroutine 567 [running]:
github.com/Azure/azure-storage-blob-go/azblob.stack()
/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_policy_request_log.go:146 +0x7a
github.com/Azure/azure-storage-blob-go/azblob.NewRequestLogPolicyFactory.func1.({0x559bfeaba000, 0xc001015c80}, {0xc000afd600})
/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_policy_request_log.go:96 +0xa9d
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc002403c70, {0x559bfeaba000, 0xc001015c80}, {0xc000afd600})
/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x75
github.com/Azure/azure-storage-blob-go/azblob.(*SharedKeyCredential).New.func1({0x559bfeaba000, 0xc001015c80}, {0xc000afd600})
/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_credential_shared_key.go:66 +0x59f
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000d02600, {0x559bfeaba000, 0xc001015c80}, {0xc000afd600})
/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x75
github.com/Azure/azure-storage-blob-go/azblob.NewRetryPolicyFactory.func1.1({0x559bfeab9f90, 0xc000da9740}, {0xc000afd500})
/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_policy_retry.go:204 +0xc8e
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc002403cc0, {0x559bfeab9f90, 0xc000da9740}, {0xc000afd500})
/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x75
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.({0x559bfeab9f90, 0xc000da9740}, {0xc000afd500})
/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_policy_unique_request_id.go:19 +0x139
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00177ee10, {0x559bfeab9f90, 0xc000da9740}, {0xc000afd500})
/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x75
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1({0x559bfeab9f90, 0xc000da9740}, {0xc000afd500})
/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_policy_telemetry.go:34 +0xd5
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000d02630, {0x559bfeab9f90, 0xc000da9740}, {0xc000afd500})
/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x75
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc0000729c0, {0x559bfeab9f90, 0xc000da9740}, {0x559bfea2e5a0, 0xc00179e370}, {0xc000afd500})
/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:129 +0xc2
github.com/Azure/azure-storage-blob-go/azblob.blobClient.ReleaseLease({{{{0xc000c02090, 0x5}, {0x0, 0x0}, 0x0, {0xc000c02098,0x26}, {0xc001147e30, 0x2e}, {0x0, ...}, ...}, ...}}, ...)
/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zz_generated_blob.go:838 +0x62f
github.com/Azure/azure-storage-blob-go/azblob.BlobURL.ReleaseLease({{{{{...}, {...}, 0x0, {...}, {...}, {...}, 0x0, {...}, {...}, {...}}, ...}}}, ...)
/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/url_blob.go:166 +0x1a9
github.com/Azure/azure-event-hubs-go/v3/storage.(*LeaserCheckpointer).ReleaseLease(0xc000c12000, {0x559bfeab9f90, 0xc000da9740}, {0xc000615a78, 0x2})
/go/pkg/mod/github.com/!azure/azure-event-hubs-go/v3@v3.3.15/storage/storage.go:350 +0x425
github.com/Azure/azure-event-hubs-go/v3/eph.(*scheduler).Stop(0xc000d1eba0, {0x559bfeab9f90, 0xc000da9740})
/go/pkg/mod/github.com/!azure/azure-event-hubs-go/v3@v3.3.15/eph/scheduler.go:193 +0x3c4
github.com/Azure/azure-event-hubs-go/v3/eph.(*EventProcessorHost).Close(0xc000c040c0, {0x559bfeab9f90, 0xc000da9740})
/go/pkg/mod/github.com/!azure/azure-event-hubs-go/v3@v3.3.15/eph/eph.go:375 +0xf3
github.com/elastic/beats/v7/x-pack/filebeat/input/azureeventhub.(*azureInput).Stop(0xc000868300)
/go/src/github.com/elastic/beats/x-pack/filebeat/input/azureeventhub/input.go:162 +0x251
github.com/elastic/beats/v7/filebeat/input.(*Runner).stop(0xc000db4600)
/go/src/github.com/elastic/beats/filebeat/input/input.go:156 +0x4a
github.com/elastic/beats/v7/filebeat/input.(*Runner).Start.func1.1()
/go/src/github.com/elastic/beats/filebeat/input/input.go:113 +0x3a
github.com/elastic/beats/v7/filebeat/input.(*Runner).Start.func1()
/go/src/github.com/elastic/beats/filebeat/input/input.go:118 +0xa6
created by github.com/elastic/beats/v7/filebeat/input.(*Runner).Start
/go/src/github.com/elastic/beats/filebeat/input/input.go:110 +0x1c5
```

This error happens while the Filebeat's [azureeventhub](https://github.com/elastic/beats/tree/main/x-pack/filebeat/input/azureeventhub) input stops.

During the stopping phase, the input tries to release the lease on the Azure blob, which stores the event hub information. See https://docs.elastic.co/integrations/azure#storage-account-container for more details why it needs a blob.

**Comment by anilalukka** [comment]
Is this issue resolved? I have the same issue with Azure event hub input. Thanks!
