### ISSUE TITLE
Agent V2: Elastic package integration tests are failing using the 8.6.0 snapshot image

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#33766]
See https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/417/pipeline/2164/ for test failures.

To reproduce:

```sh
# inside apache integration 
elastic-package build -v
elastic-package stack up -v -d --version 8.6.0-SNAPSHOT
elastic-package test -v
```

Example failure for the Apache integration ([full logs](https://fleet-ci.elastic.co/job/Ingest-manager/job/integrations/job/main/417/artifact/build/elastic-stack-dump/atlassian_jira/logs/elastic-agent.log)):

```
{"log.level":"info","@timestamp":"2022-11-22T16:15:28.195Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":325},"message":"Existing component state changed","component":{"id":"log-default","state":"Healthy","message":"Healthy: communicating with pid '4331'","inputs":[{"id":"log-default-logfile-apache-d4eb577a-00ab-468a-af02-02aa3f5c97d3","state":"Starting","message":"Starting: spawned pid '4331'"},{"id":"log-default-logfile-system-default-system","state":"Starting","message":"Starting: spawned pid '4331'"}],"output":{"id":"log-default","state":"Starting","message":"Starting: spawned pid '4331'"}},"ecs.version":"1.6.0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x559b008242f5]

goroutine 162 [running]:
github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).handleInputReload(0xc000404e80, 0xc0005ef380)
	/go/src/github.com/elastic/beats/x-pack/libbeat/management/managerV2.go:351 +0x95
github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).handleUnitReload(0xc000404e80, 0xc0005ef380)
	/go/src/github.com/elastic/beats/x-pack/libbeat/management/managerV2.go:315 +0x65
created by github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).unitListen
	/go/src/github.com/elastic/beats/x-pack/libbeat/management/managerV2.go:256 +0x52b
```

**Comment by fearful-symmetry** [comment]
Fix here: https://github.com/elastic/beats/pull/33770
