### ISSUE TITLE
Filebeat extracts kafka data and panic: name bytes_read already used

### ISSUE THREAD

**Issue by squidward05** [elastic/beats#34919]
I deployed filebeat and kafka in k8s cluster，When I use filebeat to consume kafka data, restarting filebeat will cause failure
 
- kafka version: 3.3.2
- k8s version: 
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2+rke2r1", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-17T16:04:41Z", GoVersion:"go1.18.3b7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2+rke2r1", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-17T16:04:41Z", GoVersion:"go1.18.3b7", Compiler:"gc", Platform:"linux/amd64"}
```
- filebeat  Version:  ```7.16.2```
- Operating System:  ```Ubuntu 22.04.2 LTS```
- Steps to Reproduce: 

`filebeat-pod.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: filebeat
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-03-23T08:35:26Z"
  generation: 4
  labels:
    app: filebeat-filebeat
    app.kubernetes.io/managed-by: Helm
    chart: filebeat-7.16.2
    heritage: Helm
    release: filebeat
  name: filebeat-filebeat
  namespace: default
  resourceVersion: "22903969"
  uid: a9df2b8d-08f9-47ad-899a-3749310ac701
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: filebeat-filebeat
      release: filebeat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        configChecksum: 0baa2e29798dd26cb9dedd433a161fd9db2613fbe9ca2365076576150aaee22
      creationTimestamp: null
      labels:
        app: filebeat-filebeat
        chart: filebeat-7.16.2
        release: filebeat
    spec:
      affinity: {}
      containers:
      - args:
        - -e
        - -E
        - http.enabled=true
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: elastic/filebeat:7.16.2
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 7s
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              curl --fail 127.0.0.1:5066
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: filebeat
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              filebeat test output
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "4"
            memory: 3000Mi
          requests:
            cpu: 100m
            memory: 2000Mi
        securityContext:
          privileged: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-config
          readOnly: true
          subPath: filebeat.yml
        - mountPath: /usr/share/filebeat/data
          name: data
        - mountPath: /etc/timezone
          name: timezone
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: filebeat-filebeat
      serviceAccountName: filebeat-filebeat
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: filebeat-filebeat
      - configMap:
          defaultMode: 384
          name: filebeat-filebeat-deployment-config
        name: filebeat-config
      - hostPath:
          path: /etc/timezone
          type: ""
        name: timezone
```

`filebeat-cm.yaml`
```
apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: kafka
      hosts:
        - my-cluster-kafka-bootstrap.kafka:9092
      topics: ["test"]
      group_id: "test"
      tags: ["test"]
      processors:
      - decode_json_fields:
          fields: ["message"]
          process_array: false
          max_depth: 1
          target: ""
          overwrite_keys: true
          add_error_key: true
    - type: kafka
      hosts:
        - my-cluster-kafka-bootstrap.kafka:9092
      topics: ["Operations.AuditLog.uat"]
      group_id: "Operations.AuditLog.uat.filebeat"
      tags: ["Operations.AuditLog.uat"]
      #parsers:
      #- ndjson:
      processors:
      - decode_json_fields:
          fields: ["message"]
          process_array: false
          max_depth: 1
          target: ""
          overwrite_keys: true
          add_error_key: true
      - drop_fields:
          fields: ["message"]
    processors:
    - add_id: ~
    - drop_fields:
        fields: ["kafka","kafka.topic","kafka.partition","input.type","agent.ephemeral_id","agent.hostname","agent.id","agent.name","agent.type","agent.version","ecs.version","ecs","host","agent","host.name","kafka.key","kafka.offset"]
    output.elasticsearch:
      hosts: 'http://10.43.217.123:9200'
      username: "elastic"
      password: "elastic"
      indices:
        - index: "operations.auditlog.uat-%{+yyyy.MM.dd}"
          when.contains:
            tags: "Operations.AuditLog.uat"
        - index: "test-tlog-%{+yyyy.MM.dd}"
          when.and:
            - equals:
                fields.Tags.LoggerType: "TLog"
            - contains:
                tags: "test"
        - index: "test-tlogd-%{+yyyy.MM.dd}"
          when.and:
            - equals:
                fields.Tags.LoggerType: "TLogd"
            - contains:
                tags: "test"
    setup.template.enabled: false
    setup.ilm.enabled: false
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: filebeat
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-03-23T08:35:26Z"
  labels:
    app: filebeat-filebeat
    app.kubernetes.io/managed-by: Helm
    chart: filebeat-7.16.2
    heritage: Helm
    release: filebeat
  name: filebeat-filebeat-deployment-config
  namespace: default
```
`kubectl delete pod filebeat-filebeat-bdb8bf678-f8s25`  delete pods

Here is the full error log
```
2023-03-24T07:19:01.955Z        INFO    instance/beat.go:686    Home path: [/usr/share/filebeat] Config path: [/usr/share/filebeat] Data path: [/usr/share/filebeat/data] Logs path: [/usr/share/filebeat/logs] Hostfs Path: [/]
2023-03-24T07:19:01.955Z        INFO    instance/beat.go:694    Beat ID: 3624cab8-c762-4731-978a-9fcec84cf0e2
2023-03-24T07:19:01.956Z        INFO    [api]   api/server.go:62        Starting stats endpoint
2023-03-24T07:19:01.956Z        INFO    [api]   api/server.go:64        Metrics endpoint listening on: 127.0.0.1:5066 (configured: localhost)
2023-03-24T07:19:01.956Z        INFO    [seccomp]       seccomp/seccomp.go:124  Syscall filter successfully installed
2023-03-24T07:19:01.956Z        INFO    [beat]  instance/beat.go:1040   Beat info       {"system_info": {"beat": {"path": {"config": "/usr/share/filebeat", "data": "/usr/share/filebeat/data", "home": "/usr/share/filebeat", "logs": "/usr/share/filebeat/logs"}, "type": "filebeat", "uuid": "3624cab8-c762-4731-978a-9fcec84cf0e2"}}}
2023-03-24T07:19:01.956Z        INFO    [beat]  instance/beat.go:1049   Build info      {"system_info": {"build": {"commit": "3c518f4d17a15dc85bdd68a5a03d5af51d9edd8e", "libbeat": "7.16.2", "time": "2021-12-18T21:04:19.000Z", "version": "7.16.2"}}}
2023-03-24T07:19:01.956Z        INFO    [beat]  instance/beat.go:1052   Go runtime info {"system_info": {"go": {"os":"linux","arch":"amd64","max_procs":10,"version":"go1.17.5"}}}
2023-03-24T07:19:01.957Z        INFO    [beat]  instance/beat.go:1056   Host info       {"system_info": {"host": {"architecture":"x86_64","boot_time":"2023-03-21T03:28:55Z","containerized":false,"name":"filebeat-filebeat-bdb8bf678-vrvkx","ip":["127.0.0.1/8","::1/128","10.42.3.252/32","fe80::d083:31ff:fec7:7668/64"],"kernel_version":"5.15.0-46-generic","mac":["d2:83:31:c7:76:68"],"os":{"type":"linux","family":"redhat","platform":"centos","name":"CentOS Linux","version":"7 (Core)","major":7,"minor":9,"patch":2009,"codename":"Core"},"timezone":"UTC","timezone_offset_sec":0,"id":"3f32d840a842c18987b8981697cea358"}}}
2023-03-24T07:19:01.957Z        INFO    [beat]  instance/beat.go:1085   Process info    {"system_info": {"process": {"capabilities": {"inheritable":null,"permitted":["chown","dac_override","fowner","fsetid","kill","setgid","setuid","setpcap","net_bind_service","net_raw","sys_chroot","mknod","audit_write","setfcap"],"effective":["chown","dac_override","fowner","fsetid","kill","setgid","setuid","setpcap","net_bind_service","net_raw","sys_chroot","mknod","audit_write","setfcap"],"bounding":["chown","dac_override","fowner","fsetid","kill","setgid","setuid","setpcap","net_bind_service","net_raw","sys_chroot","mknod","audit_write","setfcap"],"ambient":null}, "cwd": "/usr/share/filebeat", "exe": "/usr/share/filebeat/filebeat", "name": "filebeat", "pid": 7, "ppid": 1, "seccomp": {"mode":"filter","no_new_privs":true}, "start_time": "2023-03-24T07:19:01.620Z"}}}
2023-03-24T07:19:01.957Z        INFO    instance/beat.go:328    Setup Beat: filebeat; Version: 7.16.2
2023-03-24T07:19:01.957Z        INFO    [esclientleg]   eslegclient/connection.go:102   elasticsearch url: http://10.43.217.123:9200
2023-03-24T07:19:01.958Z        INFO    [publisher]     pipeline/module.go:113  Beat name: filebeat-filebeat-bdb8bf678-vrvkx
2023-03-24T07:19:01.958Z        INFO    [monitoring]    log/log.go:142  Starting metrics logging every 30s
2023-03-24T07:19:01.958Z        INFO    instance/beat.go:492    filebeat start running.
2023-03-24T07:19:01.959Z        INFO    memlog/store.go:119     Loading data file of '/usr/share/filebeat/data/registry/filebeat' succeeded. Active transaction id=0
2023-03-24T07:19:01.959Z        INFO    memlog/store.go:124     Finished loading transaction log file for '/usr/share/filebeat/data/registry/filebeat'. Active transaction id=0
2023-03-24T07:19:01.959Z        INFO    [registrar]     registrar/registrar.go:109      States Loaded from registrar: 0
2023-03-24T07:19:01.959Z        INFO    [crawler]       beater/crawler.go:71    Loading Inputs: 2
2023-03-24T07:19:01.960Z        INFO    [crawler]       beater/crawler.go:141   Starting input (ID: 9516490119737331637)
2023-03-24T07:19:01.960Z        INFO    [input.kafka]   compat/compat.go:111    Input kafka starting    {"id": "84115D57E7754FB5"}
2023-03-24T07:19:01.961Z        INFO    [input.kafka.kafka input]       kafka/input.go:129      Starting Kafka input    {"id": "84115D57E7754FB5", "hosts": ["my-cluster-kafka-bootstrap.kafka:9092"]}
2023-03-24T07:19:01.961Z        INFO    [crawler]       beater/crawler.go:141   Starting input (ID: 9147990967454083181)
2023-03-24T07:19:01.961Z        INFO    [crawler]       beater/crawler.go:108   Loading and starting Inputs completed. Enabled inputs: 2
2023-03-24T07:19:01.961Z        INFO    [input.kafka]   compat/compat.go:111    Input kafka starting    {"id": "7EF431511795286D"}
2023-03-24T07:19:01.961Z        INFO    [input.kafka.kafka input]       kafka/input.go:129      Starting Kafka input    {"id": "7EF431511795286D", "hosts": ["my-cluster-kafka-bootstrap.kafka:9092"]}
panic: name bytes_read already used

goroutine 22 [running]:
github.com/elastic/beats/v7/libbeat/monitoring.panicErr(...)
        /go/src/github.com/elastic/beats/libbeat/monitoring/registry.go:257
github.com/elastic/beats/v7/libbeat/monitoring.(*Registry).Add(0xc0009881c0, {0x55e9f6c344cb, 0x0}, {0x55e9f7d46fc0, 0xc000388070}, 0x0)
        /go/src/github.com/elastic/beats/libbeat/monitoring/registry.go:155 +0xda
github.com/elastic/beats/v7/libbeat/monitoring/adapter.(*GoMetricsRegistry).doRegister(0xc0007f0cf0, {0x55e9f6c4b536, 0x12}, {0x55e9f761efe0, 0x55e9f7cef680})
        /go/src/github.com/elastic/beats/libbeat/monitoring/adapter/go-metrics.go:168 +0x467
github.com/elastic/beats/v7/libbeat/monitoring/adapter.(*GoMetricsRegistry).GetOrRegister(0xc0007f0cf0, {0x55e9f6c4b536, 0x12}, {0x55e9f761efe0, 0x55e9f7cef680})
        /go/src/github.com/elastic/beats/libbeat/monitoring/adapter/go-metrics.go:138 +0x105
github.com/rcrowley/go-metrics.GetOrRegisterMeter(...)
        /go/pkg/mod/github.com/rcrowley/go-metrics@v0.0.0-20201227073835-cf1acfcdf475/meter.go:31
github.com/Shopify/sarama.(*Broker).Open.func1()
        /go/pkg/mod/github.com/elastic/sarama@v1.19.1-0.20210823122811-11c3ef800752/broker.go:173 +0x49c
github.com/Shopify/sarama.withRecover(0xc0007f97b8)
        /go/pkg/mod/github.com/elastic/sarama@v1.19.1-0.20210823122811-11c3ef800752/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*Broker).Open
        /go/pkg/mod/github.com/elastic/sarama@v1.19.1-0.20210823122811-11c3ef800752/broker.go:154 +0x167
```
I need to wait about 3 minutes for filebeat to work normally

**Comment by qshuai** [comment]
How to resolve this problem?

**Comment by huangyutongs** [comment]
> How to resolve this problem?
It's been a while, so I don't remember it clearly. It's probably because filebeat restarted quickly, and the previously registered consumer group was still active, causing the name duplication.
