### ISSUE TITLE
[Flaky test] TestMonitoringNameFromConfig is failing

### ISSUE THREAD

**Issue by AndersonQ** [elastic/beats#37689]
## Flaky Test

* **Test Name:** TestKeystoreRemoveMultipleExistingKeys.
* **Link:** [cmd_keystore_test.go](https://github.com/elastic/beats/blob/ca036402c80cf71c86fbfa9e72a6b3dc42c594bf/libbeat/tests/integration/cmd_keystore_test.go#L94).
* **Branch:** [AndersonQ:beats-report-package-version](https://github.com/AndersonQ/beats/tree/beats-report-package-version)
* **Artifact Link:**
  - https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-37553/27/pipeline/2984
* **Notes:** Additional details about the test. e.g. theory as to failure cause
   - I believe the new beat is getting stuck and that's the reason the test times out
   - The culprit is the change from `os.StartProcess` to `exec.Cmd`

### Stack Trace

```
[2024-01-22T12:18:37.932Z] === Failed

[2024-01-22T12:18:37.932Z] === FAIL: libbeat/tests/integration TestKeystoreRemoveMultipleExistingKeys (unknown)

[2024-01-22T12:18:37.932Z] coverage: 44.8% of statements

[2024-01-22T12:18:37.932Z] panic: test timed out after 10m0s

[2024-01-22T12:18:37.932Z] running tests:

[2024-01-22T12:18:37.932Z] 	TestKeystoreRemoveMultipleExistingKeys (9m51s)

[2024-01-22T12:18:37.932Z] 

[2024-01-22T12:18:37.932Z] goroutine 111 [running]:

[2024-01-22T12:18:37.932Z] testing.(*M).startAlarm.func1()

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/testing/testing.go:2259 +0x3b9

[2024-01-22T12:18:37.932Z] created by time.goFunc

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/time/sleep.go:176 +0x2d

[2024-01-22T12:18:37.932Z] 

[2024-01-22T12:18:37.932Z] goroutine 1 [chan receive]:

[2024-01-22T12:18:37.932Z] testing.(*T).Run(0xc0001bcea0, {0xab3733?, 0x578edc?}, 0xae25d0)

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/testing/testing.go:1649 +0x3c8

[2024-01-22T12:18:37.932Z] testing.runTests.func1(0xf96ac0?)

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/testing/testing.go:2054 +0x3e

[2024-01-22T12:18:37.932Z] testing.tRunner(0xc0001bcea0, 0xc0001ebc38)

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/testing/testing.go:1595 +0xff

[2024-01-22T12:18:37.932Z] testing.runTests(0xc0001fe320?, {0xf8c800, 0x3a, 0x3a}, {0x418a9f?, 0xc0001ebcf8?, 0xf95fc0?})

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/testing/testing.go:2052 +0x445

[2024-01-22T12:18:37.932Z] testing.(*M).Run(0xc0001fe320)

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/testing/testing.go:1925 +0x636

[2024-01-22T12:18:37.932Z] main.main()

[2024-01-22T12:18:37.932Z] 	_testmain.go:195 +0x1bf

[2024-01-22T12:18:37.932Z] 

[2024-01-22T12:18:37.932Z] goroutine 109 [syscall]:

[2024-01-22T12:18:37.932Z] syscall.Syscall6(0x412b45?, 0x30?, 0xa23c60?, 0x1?, 0xc000183d98?, 0x4ea5ce?, 0xf4e908?)

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/syscall/syscall_linux.go:91 +0x30

[2024-01-22T12:18:37.932Z] os.(*Process).blockUntilWaitable(0xc000162150)

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/os/wait_waitid.go:32 +0x76

[2024-01-22T12:18:37.932Z] os.(*Process).wait(0xc000162150)

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/os/exec_unix.go:22 +0x25

[2024-01-22T12:18:37.932Z] os.(*Process).Wait(...)

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/os/exec.go:134

[2024-01-22T12:18:37.932Z] github.com/elastic/beats/v7/libbeat/tests/integration.TestKeystoreRemoveMultipleExistingKeys(0xc0003cfd40?)

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/src/github.com/elastic/beats/libbeat/tests/integration/cmd_keystore_test.go:104 +0x2f7

[2024-01-22T12:18:37.932Z] testing.tRunner(0xc0001029c0, 0xae25d0)

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/testing/testing.go:1595 +0xff

[2024-01-22T12:18:37.932Z] created by testing.(*T).Run in goroutine 1

[2024-01-22T12:18:37.932Z] 	/var/lib/jenkins/workspace/PR-37553-27-67e9f907-f31c-4293-b44e-f9c9a59c4839/.gvm/versions/go1.21.6.linux.amd64/src/testing/testing.go:1648 +0x3ad

[2024-01-22T12:18:37.932Z] 

[2024-01-22T12:18:37.932Z] DONE 2541 tests, 6 skipped, 1 failure in 673.430s

[2024-01-22T12:18:53.481Z] Error: failed to execute go: exit status 1
```

**Comment by AndersonQ** [comment]
closing as it was happening only on [AndersonQ:beats-report-package-version](https://github.com/AndersonQ/beats/tree/beats-report-package-version)
