### ISSUE TITLE
Dropped events in filestream / kubernetes autodiscover

### ISSUE THREAD

**Issue by faec** [elastic/beats#38095]
A [recent panic in Filebeat](https://github.com/elastic/beats/issues/37702) was tracked down to a race condition where a Beats pipeline client was closed while it was still waiting on a response from the queue for an event's publication. The most common cause of closed pipeline clients is a Harvester shutting down.

One of the implications of this panic, though, is that there are cases where a client is shut down while it still has pending events that haven't entered the queue (possibly because the underlying file is deleted or renamed while some of its data is still being processed). We can prevent this from crashing Filebeat, but the "correct" behavior then is to drop any events that haven't yet entered the queue when the client is closed, which is probably not the intended behavior for callers of this API like the Filebeat harvesters.

It's not clear how common this issue is. Anecdotally, users who were seeing the panic issue saw it a few times a day, however only one rare branch of the cancellation would lead to an actual panic, and the number of pending events that are dropped on cancellation may be higher.

This issue would arise most often with a full or mostly-full queue, and with inputs that go through many pipeline clients, such as a Filestream input with a lot of file churn, or a Kubernetes autodiscover input with a lot of ephemeral pods.

**Comment by sasikiranvaddi** [comment]
+1
We could see go panic error during filebeat process reload due to heavily loaded/ busy environments.
Filebeat version: 9.4.3
Filebeat Autodiscover with input type as filestream.

Stack Trace pasted below:
-----------------------------
2026-08-17T09:50:45.275+02:00  panic: retaining released ref count
2026-08-17T09:50:45.276+02:00  goroutine 75 [running]:
2026-08-17T09:50:45.276+02:00  github.com/elastic/go-concert.(*RefCount).Retain(...)
2026-08-17T09:50:45.276+02:00  github.com/elastic/go-concert@v0.3.0/refcount.go:50
2026-08-17T09:50:45.277+02:00  github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*store).Retain(...)
2026-08-17T09:50:45.277+02:00  github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/store.go:518
2026-08-17T09:50:45.277+02:00  github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).getRetainedStore(...)
2026-08-17T09:50:45.277+02:00  github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/manager.go:313
2026-08-17T09:50:45.278+02:00  github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).Create(0x2d9633179e80, 0x2d9634d74a20)
2026-08-17T09:50:45.278+02:00  github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/manager.go:261 +0xc96
2026-08-17T09:50:45.278+02:00  github.com/elastic/beats/v7/filebeat/input/v2.(*Loader).Configure(0x2d96337c10e0, 0x2d9634d74a20)
2026-08-17T09:50:45.278+02:00  github.com/elastic/beats/v7/filebeat/input/v2/loader.go:108 +0x4f9
2026-08-17T09:50:45.369+02:00  github.com/elastic/beats/v7/filebeat/input/v2/compat.(*factory).Create(0x2d96338586c0, {0x557bb4fe4340, 0x2d963716f848}, 0x2d9634d74a20)
2026-08-17T09:50:45.370+02:00  github.com/elastic/beats/v7/filebeat/input/v2/compat/compat.go:107 +0x49
2026-08-17T09:50:45.370+02:00  github.com/elastic/beats/v7/filebeat/input/v2/compat.composeFactory.Create({{0x557bb4fe4688?, 0x2d96338586c0?}, {0x557bb4fe45e8?, 0x2d96334520e0?}}, {0x557bb4fe4340, 0x2d963716f848}, 0x2d9634d74a20)
2026-08-17T09:50:45.370+02:00  github.com/elastic/beats/v7/filebeat/input/v2/compat/composed.go:62 +0x5a
2026-08-17T09:50:45.371+02:00  github.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Run.RunnerFactoryWithCommonInputSettings.func14({0x557bb4fe46b0, 0x2d9633452120}, {0x557bb4fe4340?, 0x2d963716f7e8?}, 0x2d9634d74a20)
2026-08-17T09:50:45.371+02:00  github.com/elastic/beats/v7/filebeat/channel/runner.go:100 +0xd6
2026-08-17T09:50:45.371+02:00  github.com/elastic/beats/v7/filebeat/channel.(*onCreateFactory).Create(0x2d96338fe008?, {0x557bb4fe4340?, 0x2d963716f7e8?}, 0x557bae7d48a5?)
2026-08-17T09:50:45.371+02:00  github.com/elastic/beats/v7/filebeat/channel/runner.go:69 +0x38
2026-08-17T09:50:45.372+02:00  github.com/elastic/beats/v7/libbeat/cfgfile.multiplexedFactory.Create({0x2d9633030e90, 0x2, 0x557bae76ae05?}, {0x557bb4fe4340, 0x2d963716f7e8}, 0x2d9634d74a20)
2026-08-17T09:50:45.372+02:00  github.com/elastic/beats/v7/libbeat/cfgfile/factories.go:75 +0xbb
2026-08-17T09:50:45.372+02:00  github.com/elastic/beats/v7/libbeat/cfgfile.createRunner({0x557bb4fe42f0, 0x2d9632fbf038}, {0x557bb4fe4340, 0x2d9633266600}, 0x2d9635744e00)
2026-08-17T09:50:45.373+02:00  github.com/elastic/beats/v7/libbeat/cfgfile/list.go:244 +0x253
2026-08-17T09:50:45.373+02:00  github.com/elastic/beats/v7/libbeat/cfgfile.(*RunnerList).Reload(0x2d96333a6280, {0x2d96362aec00, 0x3b, 0x2d9632fae258?})
2026-08-17T09:50:45.373+02:00  github.com/elastic/beats/v7/libbeat/cfgfile/list.go:130 +0xa05
2026-08-17T09:50:45.373+02:00  github.com/elastic/beats/v7/libbeat/autodiscover.(*Autodiscover).worker(0x2d963324f050)
2026-08-17T09:50:45.373+02:00  github.com/elastic/beats/v7/libbeat/autodiscover/autodiscover.go:161 +0x518
2026-08-17T09:50:45.374+02:00  created by github.com/elastic/beats/v7/libbeat/autodiscover.(*Autodiscover).Start in goroutine 1
2026-08-17T09:50:45.374+02:00  github.com/elastic/beats/v7/libbeat/autodiscover/autodiscover.go:117 +0x112
