### ISSUE TITLE
Filebeat - panic while using multiline but give certain configure error

### ISSUE THREAD

**Issue by dove-young** [elastic/beats#4165]
My OS version is CentOS Linux release 7.2.1511 (Core)
My Filebeat version is  filebeat version 5.2.1 (amd64), libbeat 5.2.1

I can produce a kernel panic for Filebeat when I specific a multiline setting like this

```
  ### Multiline options

  # Mutiline can be used for log messages spanning multiple lines. This is common
  # for Java Stack Traces or C-Line Continuation

  # The regexp Pattern that has to be matched. The example pattern matches all lines starting with [
#  multiline.pattern: ^\[
#  multiline.pattern: ^[^\[]|^\[.* SystemErr[\s\t]+R[\s\t]+at
  # Defines if the pattern set under pattern should be negated or not. Default is false.
#  multiline.negate: true
#  multiline.negate: false

  # Match can be set to "after" or "before". It is used to define if lines should be append to a pattern
  # that was (not) matched before or after or as long as a pattern is not matched based on negate.
  # Note: After is the equivalent to previous and before is the equivalent to to next in Logstash
  multiline.match: after

```

```
[kube@tivsun15 10.134.7.236]$ /usr/share/filebeat/bin/filebeat -path.home /usr/share/filebeat -path.config /home/kube/Softlayer_Logs/10.134.7.236/etc_logstash_agent/filebeat -path.data /home/kube/Softlayer_Logs/10.134.7.236/etc_logstash_agent/lib/filebeat -path.logs /home/kube/Softlayer_Logs/10.134.7.236/etc_logstash_agent/log/filebeat etc_logstash_agent -e start
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5df0c6]

goroutine 45 [running]:
panic(0x8f44a0, 0xc420010090)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
regexp.(*Regexp).get(0x0, 0xc42034b528)
        /usr/local/go/src/regexp/regexp.go:208 +0x26
regexp.(*Regexp).doExecute(0x0, 0x0, 0x0, 0xc42032ea80, 0x5a, 0x5b, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/regexp/exec.go:416 +0x40
regexp.(*Regexp).Match(0x0, 0xc42032ea80, 0x5a, 0x5b, 0x5a)
        /usr/local/go/src/regexp/regexp.go:421 +0x8c
github.com/elastic/beats/filebeat/harvester/reader.genPatternMatcher.func1(0xc4200532d0, 0x68, 0x69, 0xc42032ea80, 0x5a, 0x5b, 0x5b)
        /go/src/github.com/elastic/beats/filebeat/harvester/reader/multiline.go:307 +0xa3
github.com/elastic/beats/filebeat/harvester/reader.(*Multiline).readNext(0xc42000a300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/elastic/beats/filebeat/harvester/reader/multiline.go:189 +0x8b7
github.com/elastic/beats/filebeat/harvester/reader.(*Multiline).readFirst(0xc42000a300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42032d468, ...)
        /go/src/github.com/elastic/beats/filebeat/harvester/reader/multiline.go:132 +0x167
github.com/elastic/beats/filebeat/harvester/reader.(*Multiline).Next(0xc42000a300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420044cb0, ...)
        /go/src/github.com/elastic/beats/filebeat/harvester/reader/multiline.go:108 +0x62
github.com/elastic/beats/filebeat/harvester/reader.(*Limit).Next(0xc42036a7a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/elastic/beats/filebeat/harvester/reader/limit.go:17 +0x66
github.com/elastic/beats/filebeat/harvester.(*Harvester).Harvest(0xc420334b60, 0xc07180, 0xc42036a7a0)
        /go/src/github.com/elastic/beats/filebeat/harvester/log.go:93 +0x24d
github.com/elastic/beats/filebeat/prospector.(*Prospector).startHarvester.func1(0xc420336000, 0xc420334b60, 0xc07180, 0xc42036a7a0)
        /go/src/github.com/elastic/beats/filebeat/prospector/prospector.go:248 +0x65
created by github.com/elastic/beats/filebeat/prospector.(*Prospector).startHarvester
        /go/src/github.com/elastic/beats/filebeat/prospector/prospector.go:249 +0x2e4
[kube@tivsun15 10.134.7.236]$
```

I agree the above setting is incorrect. But the expected behavior is exit with an error message, like below. A kernel panic due to an incorrect configuration must be a problem.

```
/usr/share/filebeat/bin/filebeat -path.home /usr/share/filebeat -path.config /home/kube/Softlayer_Logs/10.134.7.236/etc_logstash_agent/filebeat -path.data /home/kube/Softlayer_Logs/10.134.7.236/etc_logstash_agent/lib/filebeat -path.logs /home/kube/Softlayer_Logs/10.134.7.236/etc_logstash_agent/log/filebeat etc_logstash_agent -e start
Exiting: Error in initing prospector: missing required field accessing 'filebeat.prospectors.0.multiline.match' (source:'/home/kube/Softlayer_Logs/10.134.7.236/etc_logstash_agent/filebeat/filebeat.yml')
```

You can produce above error message by change filebeat.yml in this way. This time, the application exited as expected with an error message

```
  ### Multiline options

  # Mutiline can be used for log messages spanning multiple lines. This is common
  # for Java Stack Traces or C-Line Continuation

  # The regexp Pattern that has to be matched. The example pattern matches all lines starting with [
#  multiline.pattern: ^\[
#  multiline.pattern: ^[^\[]|^\[.* SystemErr[\s\t]+R[\s\t]+at
  # Defines if the pattern set under pattern should be negated or not. Default is false.
  multiline.negate: true
#  multiline.negate: false

  # Match can be set to "after" or "before". It is used to define if lines should be append to a pattern
  # that was (not) matched before or after or as long as a pattern is not matched based on negate.
  # Note: After is the equivalent to previous and before is the equivalent to to next in Logstash
#  multiline.match: after

```

**Comment by ruflin** [comment]
@dove-young Thanks for the report. I also managed to reproduce this in master. Fully agree that on wrong config filebeat should not panic.

**Comment by ruflin** [comment]
Here is a fix for this panic: https://github.com/elastic/beats/pull/4377
