### ISSUE TITLE
Panic interface conversion: interface {} is string, not common.Time

### ISSUE THREAD

**Issue by nrvnrvn** [elastic/beats#5156]
Libbeat version used: v5.5.2
Seen only when elasticsearch is used as an output. 
More examples here - https://github.com/mheese/journalbeat/issues/72

```
Sep 11 21:19:05 host-1 journalbeat[23008]: panic: interface conversion: interface {} is string, not common.Time
Sep 11 21:19:05 host-1 journalbeat[23008]: goroutine 36 [running]:
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch.getIndex(0xc42033f950, 0x117dca0, 0xc4
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:372 +0x3f7
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch.createEventBulkMeta(0x117dca0, 0xc4200
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:327 +0x10d
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch.bulkEncodePublishRequest(0x7fbbd3d990d
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:294 +0xba
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch.(*Client).PublishEvents(0xc4200d4500,
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:246 +0x13b
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/mode/single.(*Mode).PublishEvents.func1(0xc4202635f0
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/mode/single/single.go:89 +0x7b
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/mode/single.(*Mode).publish(0xc4202635f0, 0x1184460,
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/mode/single/single.go:144 +0x290
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/mode/single.(*Mode).PublishEvents(0xc4202635f0, 0x11
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/mode/single/single.go:99 +0x7d
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch.(*elasticsearchOutput).BulkPublish(0xc
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/output.go:415 +0x79
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher.(*outputWorker).sendBulk(0xc420050d70, 0xc42002fd3
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher/output.go:112 +0x123
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher.(*outputWorker).onBulk(0xc420050d70, 0xc42002fd38,
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher/output.go:88 +0x281
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher.(*outputWorker).onMessage(0xc420050d70, 0x0, 0x1,
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher/output.go:70 +0x9a
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher.(*messageWorker).onEvent(0xc420050d70, 0x0, 0x1, 0
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher/worker.go:83 +0x74
Sep 11 21:19:05 host-1 journalbeat[23008]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher.(*messageWorker).run(0xc420050d70)
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher/worker.go:69 +0x290
Sep 11 21:19:05 host-1 journalbeat[23008]: created by github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher.(*messageWorker).init
Sep 11 21:19:05 host-1 journalbeat[23008]: /go/src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/publisher/worker.go:57 +0x107
```

**Comment by andrewkroh** [comment]
I didn't see any obvious way for the `@timestamp` value to be anything other than a `common.Time` in the event. If you can reproduce it can you add some additional debug into your copy of libbeat to see what is actually in the event being published. In `getIndex` I think something like this would be useful.

```
func getIndex(event common.MapStr, index outil.Selector) string {
	var ts time.Time
	if timestamp, ok := event["@timestamp"].(common.Time); ok {
		ts = time.Time(timestamp).UTC()
	} else {
		ts = time.Now().UTC()
		logp.Err("@timestamp is not a common.Time but is %T in event %#v", event["@timestamp"], event)
	}
```

https://github.com/elastic/beats/blob/v5.5.2/libbeat/outputs/elasticsearch/client.go#L372

**Comment by urso** [comment]
Issues seems to be very old and there have been significient changes in this code path since 5.x. If the problem persists with recent releases, please reopen.
