### ISSUE TITLE
filebeat: few system test fail locally (config file: wrong permission)

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#6296]
For confirmed bugs, please report:
- Version: master branch (d1b53f433424ccd51f957cbe61e31ec6567cc25c)
- Operating System: Ubuntu
- Steps to Reproduce: 

1. git clone git@github.com:elastic/beats.git
2. cd github.com/elastic/beats/filebeat
3. make system-tests

```
➜  filebeat git:(master) make system-tests
mkdir -p /home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/coverage
# gotestcover is needed to fetch coverage for multiple packages
go get github.com/elastic/beats/vendor/github.com/pierrre/gotestcover
# testify is needed for unit and integration tests
go get github.com/elastic/beats/vendor/github.com/stretchr/testify/assert
# libcompose is needed for integration tests
go get github.com/docker/libcompose
warning: ignoring symlink /home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/python-env/include/python2.7
warning: ignoring symlink /home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/python-env/lib/python2.7/encodings
warning: ignoring symlink /home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/python-env/lib/python2.7/lib-dynload
warning: ignoring symlink /home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/python-env/local/bin
warning: ignoring symlink /home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/python-env/local/include
warning: ignoring symlink /home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/python-env/local/lib
warning: ignoring symlink /home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/system-tests/last_run
warning: no packages being tested depend on github.com/elastic/beats/filebeat/scripts/generator/fields
warning: no packages being tested depend on github.com/elastic/beats/filebeat/scripts/generator/fileset
. /home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/python-env/bin/activate; INTEGRATION_TESTS= TESTING_ENVIRONMENT=snapshot DOCKER_COMPOSE_PROJECT_NAME=filebeatsnapshot7.0.0-alpha1d1b53f433424ccd51f957cbe61e31ec6567cc25c  nosetests -w tests/system --process-timeout=90 --with-timer -v --with-xunit --xunit-file=/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/TEST-system.xml
Test docker autodiscover starts input ... SKIP: integration test not available on 2.x
Test if the basic fields exist. ... ok (0.2662s)
Checks if filebeat fails to load if removed settings have been used: ... ok (0.0552s)
Test that the template can be loaded with `setup --template` ... SKIP: integration test
Test modules disable command ... ok (0.0954s)
Test modules enable command ... ok (0.0976s)
Test modules list command ... ok (0.0911s)
Checks if all the log lines are exported by default ... ok (0.2710s)
Tests that several common encodings work. ... ok (4.1586s)
Checks if the lines matching exclude_lines regexp are dropped ... ok (0.1699s)
Checks if all lines are read from the log file. ... ok (0.1681s)
Checks that filebeat keeps running in case a log files is deleted ... ok (0.4715s)
Checks that filebeat keeps running in case a log files is deleted ... ok (0.5716s)
Checks that filebeat handles files without reading permission well ... ok (0.1649s)
Makes sure that when a file is renamed, the content is not read again. ... ok (0.4629s)
Checks if all the log lines are exported by default ... ok (0.2735s)
Checks if only the log lines defined by include_lines are exported ... ok (0.1668s)
Test that filebeat keeps picking up new lines ... ok (0.8695s)
Checks that filebeat follows future writes to the same ... ok (0.4685s)
Checks that filebeat follows future writes to the same ... ok (0.4747s)
Checks that partial lines are read as intended ... ok (1.6637s)
Tests that every new file discovered is started ... ok (1.3685s)
Checks that if a line does not have a line ending, is is not read yet. ... ok (1.5847s)
Tests that UTF-8 chars don't break our log tailing. ... ok (0.5632s)
Checks that harvesting works with deprecated input_type but message is outputted ... ok (0.2732s)
Checks that harvesting works with deprecated prospectors but a deprecation warning is printed. ... ok (0.2697s)
Checks that it's possible to set a custom shipper name. Also ... ok (0.2704s)
Tests that custom fields show up in the output dict. ... ok (0.2631s)
Tests that custom fields show up in the output dict under ... ok (0.2690s)
Test utf8 log file with bom ... ok (0.2735s)
Test bom log files if bom is removed properly ... ok (0.7247s)
Checks that a file is closed if eof is reached ... ok (0.2684s)
Checks that a file is closed if removed ... ok (0.3696s)
Checks that a file is closed when its renamed / rotated ... ok (0.4705s)
Checks that a file is closed after close_timeout ... ok (4.8551s)
Tests that in case of a decoding error it is handled gracefully ... ok (0.2724s)
Checks that no empty events are sent for an empty line but state is still updated ... ok (0.5779s)
Checks that no empty events are sent for a file with only empty lines ... ok (0.2732s)
Checks that also full line is sent if lines exceeds buffer ... ok (0.2777s)
Test that symlinks are ignored ... ok (0.1699s)
Tests that if symlink and original file are read, that only events from one are added ... ok (0.2754s)
Tests that if a symlink to a file is removed, further data is read which is added to the original file ... ok (1.2643s)
Test what happens if symlink removed and points to a new file ... ok (0.4671s)
Test if symlinks are harvested ... ok (0.2694s)
Tests what happens if file is truncated and symlink recreated ... ok (0.4694s)
Checks if it is correctly detected if a closed file is truncated ... ok (1.3761s)
Checks if it is correctly detected if an open file is truncated ... ok (0.5829s)
Should raise an error if line filtering and JSON are defined, ... ok (0.0579s)
Should raise an error if line filtering and JSON are defined, ... ok (0.0607s)
Should be able to interpret docker logs. ... ok (0.2773s)
Should be able to do line filtering on docker logs. ... ok (0.2626s)
Should be able to do multiline on docker logs. ... ok (1.2668s)
It should work to drop JSON event based on an integer ... ok (0.2749s)
test_json_add_tags (test_json.Test) ... ok (0.2714s)
Should be able to overwrite keys when requested. ... ok (0.2644s)
Should be able to make use of a `@timestamp` field if it exists in the ... ok (0.2704s)
If overwrite_keys is true and type is in the message, we have to ... ok (0.2744s)
It should work fine to combine JSON decoding with ... ok (0.2718s)
It should work fine to combine JSON decoding with ... ok (0.2670s)
Test that we return the template key when the key doesn't exist ... ok (0.0541s)
Test that we correctly do string replacement with values from the keystore ... ok (0.2464s)
Test large number of files on startup if harvester overlap happens and would create too many events ... SKIP: load test
Tests the number of files filebeat can open on startup ... SKIP: load test
Test that filebeat does not loose any events under heavy file rotation and load ... ok (0.6012s)
Test ML are installed in all possible ways ... SKIP: integration test not available on 2.x
Tests all filebeat modules ... SKIP: integration test not available on 2.x
Tests that the pipeline configured in the prospector overwrites ... SKIP: integration test not available on 2.x
Test that multi lines for c style log works ... ok (1.2776s)
Test if multiline events are split up with close_timeout ... ok (3.3735s)
Test if consecutive multilines have an affect on multiline ... ok (1.2740s)
Test that filebeat errors if pattern is missing config ... ok (0.1375s)
Test that multi lines for java logs works. ... ok (1.2668s)
Test the maximum number of bytes that is sent ... ok (1.2813s)
Test the maximum number of lines that is sent by multiline ... ok (1.2661s)
Test rabbitmq multiline log ... ok (1.2856s)
Test that data is sent after timeout ... ok (2.4767s)
Check condition in processors ... ok (0.2725s)
Check drop_event filtering action ... ok (0.2721s)
Check drop_fields filtering action ... ok (0.2622s)
Check drop_fields filtering action ... ok (0.2673s)
Test that close_inactive closes the file but reading ... ok (1.4797s)
Test that close_inactive still applies also if the file to close was removed ... ok (0.4675s)
Test that close_inactive still applies also if the file to close was removed ... ok (0.4707s)
Test that close_inactive still applies also if file was rotated, ... ok (3.4845s)
Check that the recursive glob can be disabled from the config. ... ok (0.1629s)
test_exclude_files (test_prospector.Test) ... ok (0.2726s)
Tests that prospectors stay running even though no harvesters are started yet ... ok (0.6758s)
Test if harvester_limit applies ... ok (4.2865s)
Should ignore files there were not modified for longer then ... ok (2.1743s)
In case a prospector is defined but doesn't contain any paths, prospector must return error which ... ok (0.1402s)
Should not ignore files there were modified more recent than ... ok (0.2629s)
Check drop_fields filtering action at a prospector level ... ok (0.2682s)
Check include_fields filtering action at a prospector level ... ok (0.2736s)
Check that file reading via recursive glob patterns continues after restart ... ok (0.4986s)
test_rotating_close_inactive_larger_write_rate (test_prospector.Test) ... ok (1.7724s)
test_rotating_close_inactive_low_write_rate (test_prospector.Test) ... ok (3.4835s)
In case no prospectors are defined, filebeat must shut down and report an error ... ok (0.1419s)
Test that symlinks are skipped ... ok (0.2634s)
Test stdin input. Checks if reading is continued after the first read. ... ok (0.5731s)
Test that Filebeat works when stdin is closed. ... ok (0.4743s)
Check if registrar file is created correctly and content is as expected ... ok (0.2742s)
test_prospector (test_redis.Test) ... SKIP: integration test
Checks that states are properly removed after clean_inactive ... ok (4.5921s)
Checks that files which were removed, the state is removed ... ok (0.5637s)
Checks that files which were removed, the state is removed ... ok (3.5781s)
Check that when a custom registry file is used, the path ... ok (0.2720s)
Checks that the registry file is written in a custom data path. ... ok (0.2630s)
Test that filebeat does not start if a directory is set as registry file ... ok (0.1425s)
Check that state is also persisted for files falling under ignore_older on startup ... ok (1.1716s)
Check that state for ignore_older is not persisted when falling under clean_inactive ... ok (2.1758s)
Test that filebeat fails starting if invalid state in registry ... ok (0.1386s)
Check if registrar file is created correctly and content is as expected ... ok (0.2771s)
Check that multiple files are put into registrar file ... ok (0.2676s)
Check that multiple files are put into registrar file with drop event processor ... ok (2.1825s)
Check that file reading continues after restart ... ok (1.5098s)
Make sure that states are rewritten correctly on restart and cleaned ... ok (9.4528s)
Test that ttl is set to -1 after restart and no prospector covering it ... ok (0.4118s)
Test that ttl is reset after restart if clean_inactive changes ... ok (0.3928s)
Test that ttl is reset after restart if clean_inactive is disabled ... ok (0.4047s)
Test that ttl is reset after restart if clean_inactive changes ... ok (0.4084s)
Checks that the registry is properly updated after a file is rotated ... ok (2.1795s)
Check that inodes are properly written during file rotation ... ok (4.2843s)
Check that inodes are properly written during file rotation and restart ... ok (3.5144s)
Checks that the state is written correctly after rotation ... ok (3.1699s)
Checks that the state is written correctly after rotation and ignore older ... ok (3.1779s)
Test that filebeat does not start if a symlink is set as registry file ... ok (0.1385s)
Test loading separate module configs ... ERROR
Test pipeline loading failures don't crash filebeat ... ERROR
Test modules basic reload ... ERROR
Test modules reload brings pipelines ... SKIP: integration test
Test basic modules start and stop ... ERROR
Test beat errors when reload is disabled and some module config is wrong ... ERROR
Test loading separate prospectors configs ... ERROR
Test basic prospectors reload ... ERROR
Test adding a prospector and makes sure both are still running ... ERROR
Test reload same config with same file but different config. Makes sure reloading also works on conflicts. ... ERROR
Test reloading same prospector ... ERROR
Test basic prospectors start and stop ... ERROR
Test basic start and replace with another prospector ... ERROR
Test filebeat running with the once flag. ... ok (0.2435s)
Test starting and stopping Filebeat under load. ... ok (2.2083s)
Test stopping filebeat under load: wait for all events being published. ... ok (0.3638s)
Test stopping filebeat under load: allow early shutdown. ... ok (2.3139s)
Test filebeat stops properly when 1 prospector has an invalid config. ... ok (2.0394s)
test_udp (test_udp.Test) ... ok (0.3699s)

======================================================================
ERROR: Test loading separate module configs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_modules.py", line 195, in test_load_configs
    self.wait_until(lambda: self.output_lines() == 1)
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

======================================================================
ERROR: Test pipeline loading failures don't crash filebeat
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_modules.py", line 118, in test_no_es_connection
    self.wait_until(lambda: self.log_contains("Error loading pipeline: Error creating Elasticsearch client"))
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

======================================================================
ERROR: Test modules basic reload
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_modules.py", line 62, in test_reload
    self.wait_until(lambda: self.output_lines() > 0)
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

======================================================================
ERROR: Test basic modules start and stop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_modules.py", line 146, in test_start_stop
    self.wait_until(lambda: self.output_lines() == 1, max_timeout=10)
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

======================================================================
ERROR: Test beat errors when reload is disabled and some module config is wrong
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_modules.py", line 243, in test_wrong_module_no_reload
    max_timeout=10)
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

======================================================================
ERROR: Test loading separate prospectors configs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_prospectors.py", line 233, in test_load_configs
    self.wait_until(lambda: self.output_lines() == 1)
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

======================================================================
ERROR: Test basic prospectors reload
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_prospectors.py", line 41, in test_reload
    self.wait_until(lambda: self.output_lines() > 0)
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

======================================================================
ERROR: Test adding a prospector and makes sure both are still running
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_prospectors.py", line 325, in test_reload_add
    self.wait_until(lambda: self.output_lines() > 0)
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

======================================================================
ERROR: Test reload same config with same file but different config. Makes sure reloading also works on conflicts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_prospectors.py", line 277, in test_reload_same_config
    self.wait_until(lambda: self.output_lines() > 0)
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

======================================================================
ERROR: Test reloading same prospector
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_prospectors.py", line 171, in test_reload_same_prospector
    self.wait_until(lambda: self.output_lines() == 1)
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

======================================================================
ERROR: Test basic prospectors start and stop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_prospectors.py", line 66, in test_start_stop
    self.wait_until(lambda: self.output_lines() == 1)
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

======================================================================
ERROR: Test basic start and replace with another prospector
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_prospectors.py", line 112, in test_start_stop_replace
    self.wait_until(lambda: self.output_lines() == 1)
  File "/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 319, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

----------------------------------------------------------------------
XML: /home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/TEST-system.xml
[error] 4.15% test_reload_modules.Test.test_wrong_module_no_reload: 10.0948s
[error] 4.14% test_reload_modules.Test.test_no_es_connection: 10.0753s
[error] 4.14% test_reload_prospectors.Test.test_reload_add: 10.0725s
[error] 4.14% test_reload_prospectors.Test.test_load_configs: 10.0718s
[error] 4.14% test_reload_prospectors.Test.test_reload_same_prospector: 10.0705s
[error] 4.14% test_reload_prospectors.Test.test_start_stop_replace: 10.0705s
[error] 4.14% test_reload_modules.Test.test_load_configs: 10.0703s
[error] 4.14% test_reload_modules.Test.test_start_stop: 10.0700s
[error] 4.14% test_reload_prospectors.Test.test_reload: 10.0694s
[error] 4.14% test_reload_prospectors.Test.test_reload_same_config: 10.0679s
[error] 4.14% test_reload_prospectors.Test.test_start_stop: 10.0676s
[error] 4.14% test_reload_modules.Test.test_reload: 10.0676s
[success] 3.88% test_registrar.Test.test_restart_state: 9.4528s
[success] 1.99% test_harvester.Test.test_close_timeout: 4.8551s
[success] 1.89% test_registrar.Test.test_clean_inactive: 4.5921s
[success] 1.76% test_prospector.Test.test_harvester_limit: 4.2865s
[success] 1.76% test_registrar.Test.test_rotating_file_inode: 4.2843s
[success] 1.71% test_crawler.Test.test_encodings: 4.1586s
[success] 1.47% test_registrar.Test.test_clean_removed_with_clean_inactive: 3.5781s
[success] 1.44% test_registrar.Test.test_rotating_file_with_restart: 3.5144s
[success] 1.43% test_prospector.Test.test_close_inactive_file_rotation_and_removal2: 3.4845s
[success] 1.43% test_prospector.Test.test_rotating_close_inactive_low_write_rate: 3.4835s
[success] 1.39% test_multiline.Test.test_close_timeout_with_multiline: 3.3735s
[success] 1.31% test_registrar.Test.test_state_after_rotation_ignore_older: 3.1779s
[success] 1.30% test_registrar.Test.test_state_after_rotation: 3.1699s
[success] 1.02% test_multiline.Test.test_timeout: 2.4767s
[success] 0.95% test_shutdown.Test.test_shutdown_wait_timeout: 2.3139s
[success] 0.91% test_shutdown.Test.test_shutdown: 2.2083s
[success] 0.90% test_registrar.Test.test_registrar_files_with_prospector_level_processors: 2.1825s
[success] 0.90% test_registrar.Test.test_rotating_file: 2.1795s
[success] 0.89% test_registrar.Test.test_ignore_older_state_clean_inactive: 2.1758s
[success] 0.89% test_prospector.Test.test_ignore_older_files: 2.1743s
[success] 0.84% test_shutdown.Test.test_stopping_empty_path: 2.0394s
[success] 0.73% test_prospector.Test.test_rotating_close_inactive_larger_write_rate: 1.7724s
[success] 0.68% test_crawler.Test.test_partial_line: 1.6637s
[success] 0.65% test_crawler.Test.test_unfinished_line_and_continue: 1.5847s
[success] 0.62% test_registrar.Test.test_restart_continue: 1.5098s
[success] 0.61% test_prospector.Test.test_close_inactive: 1.4797s
[success] 0.57% test_harvester.Test.test_truncated_file_closed: 1.3761s
[success] 0.56% test_crawler.Test.test_tail_files: 1.3685s
[success] 0.53% test_multiline.Test.test_rabbitmq_multiline_log: 1.2856s
[success] 0.53% test_multiline.Test.test_max_bytes: 1.2813s
[success] 0.52% test_multiline.Test.test_c_style_log: 1.2776s
[success] 0.52% test_multiline.Test.test_consecutive_newline: 1.2740s
[success] 0.52% test_multiline.Test.test_java_elasticsearch_log: 1.2668s
[success] 0.52% test_json.Test.test_docker_logs_multiline: 1.2668s
[success] 0.52% test_multiline.Test.test_max_lines: 1.2661s
[success] 0.52% test_harvester.Test.test_symlink_removed: 1.2643s
[success] 0.48% test_registrar.Test.test_ignore_older_state: 1.1716s
[success] 0.36% test_crawler.Test.test_multiple_appends: 0.8695s
[success] 0.30% test_harvester.Test.test_boms: 0.7247s
[success] 0.28% test_prospector.Test.test_files_added_late: 0.6758s
[success] 0.25% test_load.Test.test_no_missing_events: 0.6012s
[success] 0.24% test_harvester.Test.test_truncated_file_open: 0.5829s
[success] 0.24% test_harvester.Test.test_empty_line: 0.5779s
[success] 0.24% test_prospector.Test.test_stdin: 0.5731s
[success] 0.23% test_crawler.Test.test_file_disappear_appear: 0.5716s
[success] 0.23% test_registrar.Test.test_clean_removed: 0.5637s
[success] 0.23% test_crawler.Test.test_utf8: 0.5632s
[success] 0.20% test_prospector.Test.test_restart_recursive_glob: 0.4986s
[success] 0.19% test_crawler.Test.test_new_line_on_open_file: 0.4747s
[success] 0.19% test_prospector.Test.test_stdin_eof: 0.4743s
[success] 0.19% test_crawler.Test.test_file_disappear: 0.4715s
[success] 0.19% test_prospector.Test.test_close_inactive_file_rotation_and_removal: 0.4707s
[success] 0.19% test_harvester.Test.test_close_renamed: 0.4705s
[success] 0.19% test_harvester.Test.test_truncate: 0.4694s
[success] 0.19% test_crawler.Test.test_new_line_on_existing_file: 0.4685s
[success] 0.19% test_prospector.Test.test_close_inactive_file_removal: 0.4675s
[success] 0.19% test_harvester.Test.test_symlink_rotated: 0.4671s
[success] 0.19% test_crawler.Test.test_file_renaming: 0.4629s
[success] 0.17% test_registrar.Test.test_restart_state_reset: 0.4118s
[success] 0.17% test_registrar.Test.test_restart_state_reset_ttl_with_space: 0.4084s
[success] 0.17% test_registrar.Test.test_restart_state_reset_ttl_no_clean_inactive: 0.4047s
[success] 0.16% test_registrar.Test.test_restart_state_reset_ttl: 0.3928s
[success] 0.15% test_udp.Test.test_udp: 0.3699s
[success] 0.15% test_harvester.Test.test_close_removed: 0.3696s
[success] 0.15% test_shutdown.Test.test_shutdown_wait_ok: 0.3638s
[success] 0.11% test_harvester.Test.test_exceed_buffer: 0.2777s
[success] 0.11% test_json.Test.test_docker_logs: 0.2773s
[success] 0.11% test_registrar.Test.test_registrar_file_content: 0.2771s
[success] 0.11% test_harvester.Test.test_symlink_and_file: 0.2754s
[success] 0.11% test_json.Test.test_integer_condition: 0.2749s
[success] 0.11% test_json.Test.test_type_in_message: 0.2744s
[success] 0.11% test_publisher.Test.test_registrar_file_content: 0.2742s
[success] 0.11% test_prospector.Test.test_prospector_filter_includefields: 0.2736s
[success] 0.11% test_crawler.Test.test_include_exclude_lines: 0.2735s
[success] 0.11% test_harvester.Test.test_bom_utf8: 0.2735s
[success] 0.11% test_deprecated.Test.test_input_type_deprecated: 0.2732s
[success] 0.11% test_harvester.Test.test_empty_lines_only: 0.2732s
[success] 0.11% test_prospector.Test.test_exclude_files: 0.2726s
[success] 0.11% test_processors.Test.test_condition: 0.2725s
[success] 0.11% test_harvester.Test.test_decode_error: 0.2724s
[success] 0.11% test_processors.Test.test_drop_event: 0.2721s
[success] 0.11% test_registrar.Test.test_custom_registry_file_location: 0.2720s
[success] 0.11% test_json.Test.test_with_generic_filtering: 0.2718s
[success] 0.11% test_json.Test.test_json_add_tags: 0.2714s
[success] 0.11% test_crawler.Test.test_default_include_exclude_lines: 0.2710s
[success] 0.11% test_json.Test.test_timestamp_in_message: 0.2704s
[success] 0.11% test_fields.Test.test_beat_fields: 0.2704s
[success] 0.11% test_deprecated.Test.test_prospectors_deprecated: 0.2697s
[success] 0.11% test_harvester.Test.test_symlinks_enabled: 0.2694s
[success] 0.11% test_fields.Test.test_custom_fields_under_root: 0.2690s
[success] 0.11% test_harvester.Test.test_close_eof: 0.2684s
[success] 0.11% test_prospector.Test.test_prospector_filter_dropfields: 0.2682s
[success] 0.11% test_registrar.Test.test_registrar_files: 0.2676s
[success] 0.11% test_processors.Test.test_include_fields: 0.2673s
[success] 0.11% test_json.Test.test_with_generic_filtering_remove_headers: 0.2670s
[success] 0.11% test_base.Test.test_base: 0.2662s
[success] 0.11% test_json.Test.test_simple_json_overwrite: 0.2644s
[success] 0.11% test_prospector.Test.test_skip_symlinks: 0.2634s
[success] 0.11% test_fields.Test.test_custom_fields: 0.2631s
[success] 0.11% test_registrar.Test.test_data_path: 0.2630s
[success] 0.11% test_prospector.Test.test_not_ignore_old_files: 0.2629s
[success] 0.11% test_json.Test.test_docker_logs_filtering: 0.2626s
[success] 0.11% test_processors.Test.test_dropfields: 0.2622s
[success] 0.10% test_keystore.TestKeystore.test_keystore_with_present_key: 0.2464s
[success] 0.10% test_shutdown.Test.test_once: 0.2435s
[success] 0.07% test_harvester.Test.test_ignore_symlink: 0.1699s
[success] 0.07% test_crawler.Test.test_exclude_lines: 0.1699s
[success] 0.07% test_crawler.Test.test_fetched_lines: 0.1681s
[success] 0.07% test_crawler.Test.test_include_lines: 0.1668s
[success] 0.07% test_crawler.Test.test_file_no_permission: 0.1649s
[success] 0.07% test_prospector.Test.test_disable_recursive_glob: 0.1629s
[success] 0.06% test_registrar.Test.test_directory_failure: 0.1425s
[success] 0.06% test_prospector.Test.test_shutdown_no_prospectors: 0.1419s
[success] 0.06% test_prospector.Test.test_no_paths_defined: 0.1402s
[success] 0.06% test_registrar.Test.test_invalid_state: 0.1386s
[success] 0.06% test_registrar.Test.test_symlink_failure: 0.1385s
[success] 0.06% test_multiline.Test.test_invalid_config: 0.1375s
[success] 0.04% test_cmd.TestCommands.test_modules_enable: 0.0976s
[success] 0.04% test_cmd.TestCommands.test_modules_disable: 0.0954s
[success] 0.04% test_cmd.TestCommands.test_modules_list: 0.0911s
[success] 0.02% test_json.Test.test_config_no_msg_key_multiline: 0.0607s
[success] 0.02% test_json.Test.test_config_no_msg_key_filtering: 0.0579s
[success] 0.02% test_base.Test.test_invalid_config_with_removed_settings: 0.0552s
[success] 0.02% test_keystore.TestKeystore.test_keystore_with_key_not_present: 0.0541s
----------------------------------------------------------------------
Ran 145 tests in 243.746s

FAILED (SKIP=9, errors=12)
../libbeat/scripts/Makefile:187: recipe for target 'system-tests' failed
make: *** [system-tests] Error 1
```

in file `/go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_reload_modules.Test.test_reload/filebeat.log`:

`2018-02-06T10:13:48.198+0100	ERROR	cfgfile/reload.go:237	Error loading config: invalid config: config file ("/home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_reload_modules.Test.test_reload/configs/system.yml") can only be writable by the owner but the permissions are "-rw-rw-r--" (to fix the permissions use: 'chmod go-w /home/cyrille/code/go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_reload_modules.Test.test_reload/configs/system.yml')
`

**Comment by cyrilleverrier** [comment]
1. Why does it fail locally and not on the build server?
2. Shall the command line `"-strict.perms=false"` be added when to `run_beat` and `start_beat` ?

**Comment by exekias** [comment]
I think tests rely on `umask 022`, which is set when running `make`, perhaps we can update them to ensure the permissions are correct regardless `umask`

**Comment by ruflin** [comment]
I remember we had some discussions around this in the past as others were hitting this issue on Linux machines (if I remember correctly) but I don't remember what our fix was. @andrewkroh Do you remember?

Note: I removed the `bug` label as this is not a bug in our "product" but more a problem in our test suite.

**Comment by andrewkroh** [comment]
> Why does it fail locally and not on the build server?

The build servers have `umask 022` so the files are created with acceptable permissions.

I agree with exekias, I think the tests should be corrected by ensuring that they write these files with the proper permissions. A [change](https://github.com/elastic/beats/pull/5820) was made not too long ago to chmod the main config file (I'd prefer to create the file with the proper permissions from the start rather than chmod'ing).
