### ISSUE TITLE
Cross Compiling beats for Solaris on MAC OSX results in errors while running testsuite

### ISSUE THREAD

**Issue by pramodupamanyu** [elastic/beats#656]
======================================================================
ERROR: Checks if all lines are read from the log file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/prao/projects/go/src/github.com/elastic/beats/libbeat/tests/system/test_base.py", line 30, in test_base
    mockbeat = self.run_mockbeat()
  File "/Users/prao/projects/go/src/github.com/elastic/beats/libbeat/tests/system/mockbeat.py", line 82, in run_mockbeat
    stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

test_base.Test.test_base: 0.2046s
----------------------------------------------------------------------
Ran 1 test in 0.263s

FAILED (errors=1)
make[2]: *** [system-tests] Error 1
make[1]: *** [testsuite] Error 2
make: *** [testsuite] Error 1

Upon checking the executable, it seems to be Solaris 64 Bit Binary file and testsuite may be failing because it is trying to execute a Solaris(CC TARGET) binary on MAC OSX.

**Comment by pramodupamanyu** [comment]
Test file being executed when make fails is:
file /Users/prao/projects/go/src/github.com/elastic/beats/libbeat/tests/system/../../libbeat.test
/Users/prao/projects/go/src/github.com/elastic/beats/libbeat/tests/system/../../libbeat.test: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), not stripped

**Comment by andrewkroh** [comment]
What commands are running?

`make crosscompile` puts the cross-compiled binaries in to `beats/{beat}/build/bin/`. None of the tests should ever try to execute the cross-compile binary.
