### ISSUE TITLE
create-fields fails when trying to create a module

### ISSUE THREAD

**Issue by danielkasen** [elastic/beats#6970]
When I try to run the ```make create-fields MODULE=curator FILESET=log``` command I get this error:

```
panic: interface conversion: interface {} is []interface {}, not string

goroutine 1 [running]:
main.accumulateRemoveFields(0x1109640, 0xc4200867e0, 0x0, 0x0, 0x0, 0x1, 0x1, 0x1)
	/Users/dante/go/src/github.com/elastic/beats/filebeat/scripts/generator/fields/main.go:158 +0x205
main.getProcessors(0xc42000a1e0, 0x4, 0x4, 0x7ffeefbffade, 0x35, 0x10ffea0)
	/Users/dante/go/src/github.com/elastic/beats/filebeat/scripts/generator/fields/main.go:220 +0x24e
main.(*pipeline).toFieldsYml(0xc42000e380, 0x0, 0x7ffeefbffb1d, 0x7, 0x7ffeefbffb2f, 0x3, 0xc42000e380)
	/Users/dante/go/src/github.com/elastic/beats/filebeat/scripts/generator/fields/main.go:291 +0x45
main.main()
	/Users/dante/go/src/github.com/elastic/beats/filebeat/scripts/generator/fields/main.go:342 +0x246
exit status 2
make: *** [create-fields] Error 1



I think it has something to do with the pipeline, but it appears correct:

{
  "description": "Pipeline for parsing curator log logs",
  "processors": [
    {
      "json": {
        "field": "message"
      }
    },
    {
      "grok": {
        "field": "message",
        "patterns": [
            "Action ID: %{INT:action_id}"
        ],
        "ignore_missing": true
      }
    },
    {
      "rename": {
        "field": "loglevel",
        "target_field": "level"
      }
    },
    {
      "remove": {
        "field": [
            "prospector.type"
        ]
      }
    }
    ],
  "on_failure" : [{
    "set" : {
      "field" : "error.message",
      "value" : "{{ _ingest.on_failure_message }}"
    }
  }]
}

**Comment by danielkasen** [comment]
Looks like the issue is it doesn't accept an array for remove_field: https://www.elastic.co/guide/en/elasticsearch/reference/current/remove-processor.html If I switch that to a single KV then it runs just fine.
