### ISSUE TITLE
Test event_logging fields under root flaky

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#7711]
* Version: Master
* Link: https://beats-ci.elastic.co/job/elastic+beats+master+multijob-windows/beat=winlogbeat,label=windows/1267/console

Error:
```
18:10:27 System testing winlogbeat
18:11:52 ....E...........................
18:11:52 ======================================================================
18:11:52 ERROR: eventlogging - Add custom fields (not under root)
18:11:52 ----------------------------------------------------------------------
18:11:52 Traceback (most recent call last):
18:11:52   File "C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\tests\system\test_eventlogging.py", line 123, in test_fields_not_under_root
18:11:52     "fields": {"local": "field", "env": "dev", "num": 1}
18:11:52   File "C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\tests\system\winlogbeat.py", line 94, in read_events
18:11:52     self.wait_until(lambda: self.output_has(expected_events))
18:11:52   File "C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\tests\system\../../../libbeat/tests/system\beat\beat.py", line 325, in wait_until
18:11:52     "Waited {} seconds.".format(max_timeout))
18:11:52 TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
18:11:52 
18:11:52 [error] 12.91% test_eventlogging.Test.test_fields_not_under_root: 10.0719s
```

Log
```
2018-07-24T18:10:36.097Z	INFO	instance/beat.go:544	Home path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root] Config path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root] Data path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root\data] Logs path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root\logs]
2018-07-24T18:10:36.128Z	DEBUG	[beat]	instance/beat.go:571	Beat metadata path: C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root\data\meta.json
2018-07-24T18:10:36.129Z	INFO	instance/beat.go:551	Beat UUID: a6282658-826a-48d7-be00-d4acf7425700
2018-07-24T18:10:36.129Z	DEBUG	[seccomp]	seccomp/seccomp.go:88	Syscall filtering is only supported on Linux
2018-07-24T18:10:36.129Z	INFO	[beat]	instance/beat.go:768	Beat info	{"system_info": {"beat": {"path": {"config": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\winlogbeat\\label\\windows\\src\\github.com\\elastic\\beats\\winlogbeat\\build\\system-tests\\run\\test_eventlogging.Test.test_fields_not_under_root", "data": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\winlogbeat\\label\\windows\\src\\github.com\\elastic\\beats\\winlogbeat\\build\\system-tests\\run\\test_eventlogging.Test.test_fields_not_under_root\\data", "home": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\winlogbeat\\label\\windows\\src\\github.com\\elastic\\beats\\winlogbeat\\build\\system-tests\\run\\test_eventlogging.Test.test_fields_not_under_root", "logs": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\winlogbeat\\label\\windows\\src\\github.com\\elastic\\beats\\winlogbeat\\build\\system-tests\\run\\test_eventlogging.Test.test_fields_not_under_root\\logs"}, "type": "winlogbeat", "uuid": "a6282658-826a-48d7-be00-d4acf7425700"}}}
2018-07-24T18:10:36.130Z	INFO	[beat]	instance/beat.go:777	Build info	{"system_info": {"build": {"commit": "unknown", "libbeat": "7.0.0-alpha1", "time": "1754-08-30T22:43:41.128Z", "version": "7.0.0-alpha1"}}}
2018-07-24T18:10:36.130Z	INFO	[beat]	instance/beat.go:780	Go runtime info	{"system_info": {"go": {"os":"windows","arch":"amd64","max_procs":4,"version":"go1.10.3"}}}
2018-07-24T18:10:36.136Z	INFO	[beat]	instance/beat.go:784	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2018-07-14T14:24:49.8Z","hostname":"WORKER-0CC433DC","ips":["fe80::5468:dc20:18ed:9012/64","10.34.171.149/20","::1/128","127.0.0.1/8","2001:0:9d38:953c:30a6:323b:c945:2095/64","fe80::30a6:323b:c945:2095/64","fe80::5efe:a22:ab95/128"],"kernel_version":"10.0.14393.1715 (rs1_release_inmarket.170906-1810)","mac_addresses":["0a:bc:80:20:69:68","00:00:00:00:00:00:00:e0","00:00:00:00:00:00:00:e0"],"os":{"family":"windows","platform":"windows","name":"Windows Server 2016 Datacenter","version":"10.0","major":10,"minor":0,"patch":0,"build":"14393.1715"},"timezone":"GMT","timezone_offset_sec":0,"id":"31e2265d-393d-4e51-bffb-e2e2e71580a3"}}}
2018-07-24T18:10:36.136Z	INFO	instance/beat.go:273	Setup Beat: winlogbeat; Version: 7.0.0-alpha1
2018-07-24T18:10:36.136Z	DEBUG	[beat]	instance/beat.go:290	Initializing output plugins
2018-07-24T18:10:36.136Z	DEBUG	[processors]	processors/processor.go:66	Processors: 
2018-07-24T18:10:36.137Z	DEBUG	[rotator]	file/rotator.go:135	Initialized file rotator	{"rotator": {"filename": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\winlogbeat\\label\\windows\\src\\github.com\\elastic\\beats\\winlogbeat\\build\\system-tests\\run\\test_eventlogging.Test.test_fields_not_under_root\\output\\winlogbeat", "max_size_bytes": 1024000, "max_backups": 7, "permissions": "-rw-------"}}
2018-07-24T18:10:36.137Z	INFO	fileout/file.go:94	Initialized file output. path=C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root\output\winlogbeat max_size_bytes=1024000 max_backups=7 permissions=-rw-------
2018-07-24T18:10:36.138Z	DEBUG	[publish]	pipeline/consumer.go:137	start pipeline event consumer
2018-07-24T18:10:36.138Z	INFO	pipeline/module.go:98	Beat name: WORKER-0CC433DC
2018-07-24T18:10:36.138Z	INFO	beater/winlogbeat.go:68	State will be read from and persisted to C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root\data\.winlogbeat.yml
2018-07-24T18:10:36.138Z	DEBUG	[eventlog]	eventlog/factory.go:128	Checking eventlogging
2018-07-24T18:10:36.138Z	DEBUG	[eventlog]	eventlog/factory.go:130	Using eventlogging API for event log WinlogbeatTestPython
2018-07-24T18:10:36.139Z	DEBUG	[winlogbeat]	beater/winlogbeat.go:95	Initialized EventLog[WinlogbeatTestPython]
2018-07-24T18:10:36.139Z	DEBUG	[processors]	processors/processor.go:66	Processors: 
2018-07-24T18:10:36.140Z	INFO	[monitoring]	log/log.go:114	Starting metrics logging every 30s
2018-07-24T18:10:36.140Z	INFO	instance/beat.go:367	winlogbeat start running.
2018-07-24T18:10:36.140Z	DEBUG	[service]	service/service_windows.go:68	Windows is interactive: false
2018-07-24T18:10:36.141Z	ERROR	service/service_windows.go:76	Error: The service process could not connect to the service controller.
2018-07-24T18:10:36.146Z	DEBUG	[eventlog_detail]	eventlog/eventlogging.go:99	EventLogging[WinlogbeatTestPython] Open(recordNumber=0) calling OpenEventLog(uncServerPath=, providerName=WinlogbeatTestPython)
2018-07-24T18:10:36.146Z	INFO	eventlog/eventlogging.go:133	EventLogging[WinlogbeatTestPython] contains 2 records. Record number range [23523, 23524]. Starting at 23523 (ignoringFirst=false)
2018-07-24T18:10:36.146Z	DEBUG	[winlogbeat]	beater/eventlogger.go:117	EventLog[WinlogbeatTestPython] opened successfully
2018-07-24T18:10:36.147Z	DEBUG	[eventlog_detail]	eventlog/eventlogging.go:166	EventLogging[WinlogbeatTestPython] ReadEventLog read 412 bytes
2018-07-24T18:10:36.148Z	DEBUG	[eventlog]	eventlogging/eventlogging_windows.go:503	RegOpenKey opened handle to HKLM\SYSTEM\CurrentControlSet\Services\EventLog\WinlogbeatTestPython\SystemTest, key=588
2018-07-24T18:10:36.148Z	DEBUG	[eventlog]	eventlogging/eventlogging_windows.go:521	RegQueryValueEx queried EventMessageFile from HKLM\SYSTEM\CurrentControlSet\Services\EventLog\WinlogbeatTestPython\SystemTest and got [C:\Windows\system32\EventCreate.exe]
2018-07-24T18:10:36.148Z	DEBUG	[eventlog]	eventlogging/eventlogging_windows.go:545	Returning message files [{File:C:\Windows\system32\EventCreate.exe Handle:88670209 Err:<nil>}] for sourceName SystemTest
2018-07-24T18:10:36.148Z	DEBUG	[eventlog]	eventlog/cache.go:86	messageFilesCache[WinlogbeatTestPython] size=1
2018-07-24T18:10:36.148Z	DEBUG	[eventlog_detail]	eventlog/eventlogging.go:174	EventLogging[WinlogbeatTestPython] RenderEvents returned 2 events
2018-07-24T18:10:36.149Z	DEBUG	[eventlog]	eventlog/eventlogging.go:207	EventLogging[WinlogbeatTestPython] Read() is returning 2 records
2018-07-24T18:10:36.149Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 2 records
2018-07-24T18:10:36.150Z	DEBUG	[publish]	pipeline/processor.go:308	Publish event: {
  "@timestamp": "2018-07-24T17:53:52.000Z",
  "@metadata": {
    "beat": "winlogbeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "source_name": "SystemTest",
  "computer_name": "WORKER-0CC433DC",
  "event_id": 10,
  "record_number": "23523",
  "user": {
    "domain": "WORKER-0CC433DC",
    "type": "User",
    "identifier": "S-1-5-21-2485467087-2958747450-187013876-1004",
    "name": "jenkins"
  },
  "fields": {
    "env": "dev",
    "num": 1,
    "local": "field",
    "level": "overwrite",
    "global": "field"
  },
  "host": {
    "name": "WORKER-0CC433DC"
  },
  "type": "eventlogging",
  "event_data": {
    "param1": "Add tags and fields under root"
  },
  "log_name": "WinlogbeatTestPython",
  "message": "Add tags and fields under root",
  "beat": {
    "name": "WORKER-0CC433DC",
    "hostname": "WORKER-0CC433DC",
    "version": "7.0.0-alpha1"
  },
  "level": "Information"
}
2018-07-24T18:10:36.150Z	DEBUG	[publish]	pipeline/processor.go:308	Publish event: {
  "@timestamp": "2018-07-24T18:10:36.000Z",
  "@metadata": {
    "beat": "winlogbeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "event_id": 10,
  "fields": {
    "global": "field",
    "env": "dev",
    "num": 1,
    "local": "field",
    "level": "overwrite"
  },
  "beat": {
    "name": "WORKER-0CC433DC",
    "hostname": "WORKER-0CC433DC",
    "version": "7.0.0-alpha1"
  },
  "event_data": {
    "param1": "Add fields (not under root)"
  },
  "log_name": "WinlogbeatTestPython",
  "source_name": "SystemTest",
  "record_number": "23524",
  "type": "eventlogging",
  "computer_name": "WORKER-0CC433DC",
  "level": "Information",
  "user": {
    "identifier": "S-1-5-21-2485467087-2958747450-187013876-1004",
    "name": "jenkins",
    "domain": "WORKER-0CC433DC",
    "type": "User"
  },
  "message": "Add fields (not under root)",
  "host": {
    "name": "WORKER-0CC433DC"
  }
}
2018-07-24T18:10:36.151Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-07-24T18:10:36.151Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-07-24T18:10:36.251Z	DEBUG	[memqueue]	memqueue/ackloop.go:160	ackloop: receive ack [0: 0, 2]
2018-07-24T18:10:36.251Z	DEBUG	[memqueue]	memqueue/eventloop.go:535	broker ACK events: count=2, start-seq=1, end-seq=2

2018-07-24T18:10:36.251Z	DEBUG	[memqueue]	memqueue/ackloop.go:128	ackloop: return ack to broker loop:2
2018-07-24T18:10:36.251Z	DEBUG	[memqueue]	memqueue/ackloop.go:131	ackloop:  done send ack
2018-07-24T18:10:36.252Z	INFO	beater/eventlogger.go:73	EventLog[WinlogbeatTestPython] successfully published 2 events
2018-07-24T18:10:37.153Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-07-24T18:10:37.153Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-07-24T18:10:38.155Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-07-24T18:10:38.155Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-07-24T18:10:39.157Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-07-24T18:10:39.157Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-07-24T18:10:40.158Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-07-24T18:10:40.158Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-07-24T18:10:41.149Z	DEBUG	[checkpoint]	checkpoint/checkpoint.go:203	Checkpoint saved to disk. numUpdates=1
2018-07-24T18:10:41.159Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-07-24T18:10:41.159Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-07-24T18:10:42.161Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-07-24T18:10:42.161Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-07-24T18:10:43.163Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-07-24T18:10:43.163Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-07-24T18:10:44.165Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-07-24T18:10:44.165Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-07-24T18:10:45.167Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-07-24T18:10:45.167Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
```

**Comment by andrewkroh** [comment]
The cause of the failure is that there are 2 events in the output file but only one is expected.

The first event in the output is not expected. It was written by the previous test case.

This should never happen because there is a `tearDown` method is clearing the event log. But `tearDown` looks like it makes registry changes to remove the event log **before** clearing it. So perhaps we should try changing the order of those operations.
