### ISSUE TITLE
Auditbeat concurrent map write panic

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#7896]
Auditbeat crashes after running the auditd module for sufficient time in a multiprocessor system:

```
Aug 07 12:32:14 hostname auditbeat[10686]: fatal error: concurrent map writes
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 82 [running]:
Aug 07 12:32:14 hostname auditbeat[10686]: runtime.throw(0x15dbf66, 0x15)
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc420e4b8b0 sp=0xc420e4b890 pc=0x9afaf1
Aug 07 12:32:14 hostname auditbeat[10686]: runtime.mapassign_faststr(0x1445800, 0xc42015a4b0, 0xc420935363, 0x1, 0xbed277b695681b63)
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/runtime/hashmap_fast.go:779 +0x3ce fp=0xc420e4b920 sp=0xc420e4b8b0 pc=0x99090e
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/vendor/github.com/elastic/go-libaudit/aucoalesce.UserCache.LookupUID(0xdf8475800, 0xc42015a4b0, 0xc420935363, 0x1, 0x0, 0x0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-libaudit/aucoalesce/id_lookup.go:78 +0x316 fp=0xc420e4ba10 sp=0xc420e4b920 pc=0x12b6f06
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/vendor/github.com/elastic/go-libaudit/aucoalesce.ResolveIDsFromCaches(0xc420db8a80, 0xdf8475800, 0xc42015a4b0, 0xdf8475800, 0xc42015a4e0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-libaudit/aucoalesce/id_lookup.go:135 +0xc8 fp=0xc420e4baf8 sp=0xc420e4ba10 pc=0x12b7668
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/vendor/github.com/elastic/go-libaudit/aucoalesce.ResolveIDs(0xc420db8a80)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-libaudit/aucoalesce/id_lookup.go:125 +0x5b fp=0xc420e4bb30 sp=0xc420e4baf8 pc=0x12b758b
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/auditbeat/module/auditd.buildMetricbeatEvent(0xc420542dc0, 0x6, 0x8, 0x1, 0x15cdb22, 0x6, 0x2000, 0x0, 0xc420568000, 0x317, ...)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:467 +0xf3f fp=0xc420e4bd58 sp=0xc420e4bb30 pc=0x12cc7bf
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/auditbeat/module/auditd.(*MetricSet).Run.func2(0xc42029e990, 0x16aa7c0, 0xc4204f8150, 0xc4203381e0, 0xc4200b7ba0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:202 +0xc2 fp=0xc420e4bfb8 sp=0xc420e4bd58 pc=0x12d2aa2
Aug 07 12:32:14 hostname auditbeat[10686]: runtime.goexit()
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420e4bfc0 sp=0xc420e4bfb8 pc=0x9df8d1
Aug 07 12:32:14 hostname auditbeat[10686]: created by github.com/elastic/beats/auditbeat/module/auditd.(*MetricSet).Run
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:195 +0x288
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 1 [semacquire, 5 minutes]:
Aug 07 12:32:14 hostname auditbeat[10686]: sync.runtime_Semacquire(0xc42003408c)
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/runtime/sema.go:56 +0x39
Aug 07 12:32:14 hostname auditbeat[10686]: sync.(*WaitGroup).Wait(0xc420034080)
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/sync/waitgroup.go:129 +0x72
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/metricbeat/beater.(*Metricbeat).Run(0xc42023d490, 0xc42008c3c0, 0xc4204f5b30, 0x1)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/metricbeat/beater/metricbeat.go:233 +0x26c
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/cmd/instance.(*Beat).launch(0xc42008c3c0, 0xc42045d8c0, 0x0, 0x0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/cmd/instance/beat.go:373 +0x466
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/cmd/instance.Run.func1(0x15d0c4b, 0x9, 0x15d0c4b, 0x9, 0x0, 0x0, 0xc42045d8c0, 0x0, 0x0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/cmd/instance/beat.go:188 +0x588
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/cmd/instance.Run(0x15d0c4b, 0x9, 0x15d0c4b, 0x9, 0x0, 0x0, 0xc42045d8c0, 0x0, 0x0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/cmd/instance/beat.go:189 +0x71
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/cmd.genRunCmd.func1(0xc420476c80, 0xc42021cd20, 0x0, 0xa)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/cmd/run.go:36 +0x60
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).execute(0xc420476c80, 0xc4200300c0, 0xa, 0xa, 0xc420476c80, 0xc4200300c0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:704 +0x2c6
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420476c80, 0x0, 0x161fbd0, 0x0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:785 +0x2e4
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420476c80, 0xc4204f5f78, 0xc420098058)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:738 +0x2b
Aug 07 12:32:14 hostname auditbeat[10686]: main.main()
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/auditbeat/main.go:34 +0x2f
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 20 [syscall, 5 minutes]:
Aug 07 12:32:14 hostname auditbeat[10686]: os/signal.signal_recv(0x16216e8)
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/runtime/sigqueue.go:139 +0xa6
Aug 07 12:32:14 hostname auditbeat[10686]: os/signal.loop()
Aug 07 12:32:14 hostname systemd[1]: auditbeat.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
Aug 07 12:32:14 hostname auditbeat[10686]: created by os/signal.init.0
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 52 [select]:
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/publisher/queue/memqueue.(*bufferingEventLoop).run(0xc4202568c0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/queue/memqueue/eventloop.go:316 +0x288
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/publisher/queue/memqueue.NewBroker.func1(0xc42023d420, 0x169b300, 0xc4202568c0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/queue/memqueue/broker.go:166 +0x5d
Aug 07 12:32:14 hostname auditbeat[10686]: created by github.com/elastic/beats/libbeat/publisher/queue/memqueue.NewBroker
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/queue/memqueue/broker.go:164 +0x3a6
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 53 [select]:
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/publisher/queue/memqueue.(*ackLoop).run(0xc42021bbd0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/queue/memqueue/ackloop.go:60 +0x164
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/publisher/queue/memqueue.NewBroker.func2(0xc42023d420, 0xc42021bbd0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/queue/memqueue/broker.go:170 +0x57
Aug 07 12:32:14 hostname auditbeat[10686]: created by github.com/elastic/beats/libbeat/publisher/queue/memqueue.NewBroker
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/queue/memqueue/broker.go:168 +0x3d2
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 54 [select]:
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/publisher/queue/memqueue.(*consumer).Get(0xc4203a5d60, 0x32, 0xc420070e68, 0x0, 0xc420f1bac0, 0x0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/queue/memqueue/consume.go:67 +0x11f
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/publisher/pipeline.(*eventConsumer).loop(0xc42021bcc0, 0x169b340, 0xc4203a5d60)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/consumer.go:167 +0x408
Aug 07 12:32:14 hostname auditbeat[10686]: created by github.com/elastic/beats/libbeat/publisher/pipeline.newEventConsumer
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/consumer.go:77 +0x16d
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 55 [select, 4 minutes]:
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/publisher/pipeline.(*retryer).loop(0xc4203aac40)
Aug 07 12:32:14 hostname systemd[1]: auditbeat.service: Unit entered failed state.
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/retry.go:131 +0x216
Aug 07 12:32:14 hostname auditbeat[10686]: created by github.com/elastic/beats/libbeat/publisher/pipeline.newRetryer
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/retry.go:86 +0x138
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 56 [chan receive]:
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/publisher/pipeline.(*netClientWorker).run(0xc4203aac80)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/output.go:99 +0x157
Aug 07 12:32:14 hostname auditbeat[10686]: created by github.com/elastic/beats/libbeat/publisher/pipeline.makeClientWorker
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/output.go:48 +0xf0
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 57 [chan receive]:
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/publisher/pipeline.(*netClientWorker).run(0xc4203aacc0)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/output.go:99 +0x157
Aug 07 12:32:14 hostname auditbeat[10686]: created by github.com/elastic/beats/libbeat/publisher/pipeline.makeClientWorker
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/output.go:48 +0xf0
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 58 [select]:
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/monitoring/report/log.(*reporter).snapshotLoop(0xc420380b70)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/monitoring/report/log/log.go:125 +0x3c9
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/monitoring/report/log.MakeReporter.func1(0xc420380b70)
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/monitoring/report/log/log.go:103 +0x53
Aug 07 12:32:14 hostname auditbeat[10686]: created by github.com/elastic/beats/libbeat/monitoring/report/log.MakeReporter
Aug 07 12:32:14 hostname auditbeat[10686]:         /go/src/github.com/elastic/beats/libbeat/monitoring/report/log/log.go:101 +0x156
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 59 [select, 5 minutes, locked to thread]:
Aug 07 12:32:14 hostname auditbeat[10686]: runtime.gopark(0x1621850, 0x0, 0x15cdaaa, 0x6, 0x18, 0x1)
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/runtime/proc.go:291 +0x11a
Aug 07 12:32:14 hostname auditbeat[10686]: runtime.selectgo(0xc420491f50, 0xc420200b40)
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/runtime/select.go:392 +0xe50
Aug 07 12:32:14 hostname auditbeat[10686]: runtime.ensureSigM.func1()
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/runtime/signal_unix.go:549 +0x1f4
Aug 07 12:32:14 hostname auditbeat[10686]: runtime.goexit()
Aug 07 12:32:14 hostname auditbeat[10686]:         /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1
Aug 07 12:32:14 hostname auditbeat[10686]: goroutine 38 [chan receive, 5 minutes]:
Aug 07 12:32:14 hostname auditbeat[10686]: github.com/elastic/beats/libbeat/service.HandleSignals.func1(0xc420341800, 0xc42037f100, 0xc42016b5f0, 0xc4203a5e20)
```

For confirmed bugs, please report:
- Version: master
- Operating System: Linux
- Discuss Forum URL: https://discuss.elastic.co/t/auditbeat-fatal-error-crash/143300
- Steps to Reproduce: Run auditbeat's auditd module for enough time

**Comment by tsg** [comment]
@adriansr Can you check if this is a regression or if you can reproduce with 6.3 as well?
