### ISSUE TITLE
[Winlogbeat] Flaky test_fields_not_under_root test

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#7902]
* Build: https://beats-ci.elastic.co/job/elastic+beats+master+multijob-windows/beat=winlogbeat,label=windows/1323/console
* Platform: Windows

Error
```
13:19:38 System testing winlogbeat
13:21:04 ....E...........................
13:21:04 ======================================================================
13:21:04 ERROR: eventlogging - Add custom fields (not under root)
13:21:04 ----------------------------------------------------------------------
13:21:04 Traceback (most recent call last):
13:21:04   File "C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\tests\system\test_eventlogging.py", line 123, in test_fields_not_under_root
13:21:04     "fields": {"local": "field", "env": "dev", "num": 1}
13:21:04   File "C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\tests\system\winlogbeat.py", line 94, in read_events
13:21:04     self.wait_until(lambda: self.output_has(expected_events))
13:21:04   File "C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\tests\system\../../../libbeat/tests/system\beat\beat.py", line 325, in wait_until
13:21:04     "Waited {} seconds.".format(max_timeout))
13:21:04 TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
13:21:04 
13:21:04 [error] 12.84% test_eventlogging.Test.test_fields_not_under_root: 10.0638s
```

Log
```
2018-08-06T13:19:47.511Z	INFO	instance/beat.go:544	Home path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root] Config path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root] Data path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root\data] Logs path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root\logs]
2018-08-06T13:19:47.544Z	DEBUG	[beat]	instance/beat.go:571	Beat metadata path: C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root\data\meta.json
2018-08-06T13:19:47.545Z	INFO	instance/beat.go:551	Beat UUID: e18c20bb-1509-4fdf-b5ff-df0ee9ecd811
2018-08-06T13:19:47.545Z	DEBUG	[seccomp]	seccomp/seccomp.go:88	Syscall filtering is only supported on Linux
2018-08-06T13:19:47.545Z	INFO	[beat]	instance/beat.go:768	Beat info	{"system_info": {"beat": {"path": {"config": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\winlogbeat\\label\\windows\\src\\github.com\\elastic\\beats\\winlogbeat\\build\\system-tests\\run\\test_eventlogging.Test.test_fields_not_under_root", "data": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\winlogbeat\\label\\windows\\src\\github.com\\elastic\\beats\\winlogbeat\\build\\system-tests\\run\\test_eventlogging.Test.test_fields_not_under_root\\data", "home": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\winlogbeat\\label\\windows\\src\\github.com\\elastic\\beats\\winlogbeat\\build\\system-tests\\run\\test_eventlogging.Test.test_fields_not_under_root", "logs": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\winlogbeat\\label\\windows\\src\\github.com\\elastic\\beats\\winlogbeat\\build\\system-tests\\run\\test_eventlogging.Test.test_fields_not_under_root\\logs"}, "type": "winlogbeat", "uuid": "e18c20bb-1509-4fdf-b5ff-df0ee9ecd811"}}}
2018-08-06T13:19:47.546Z	INFO	[beat]	instance/beat.go:777	Build info	{"system_info": {"build": {"commit": "unknown", "libbeat": "7.0.0-alpha1", "time": "1754-08-30T22:43:41.128Z", "version": "7.0.0-alpha1"}}}
2018-08-06T13:19:47.546Z	INFO	[beat]	instance/beat.go:780	Go runtime info	{"system_info": {"go": {"os":"windows","arch":"amd64","max_procs":4,"version":"go1.10.3"}}}
2018-08-06T13:19:47.552Z	INFO	[beat]	instance/beat.go:784	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2018-04-06T07:13:23.39Z","hostname":"WORKER-08BCCEE0","ips":["fe80::8c9a:f40:d82c:73fb/64","10.34.138.15/20","::1/128","127.0.0.1/8","2001:0:9d38:953c:3033:2a5c:dd2e:c92d/64","fe80::3033:2a5c:dd2e:c92d/64","fe80::5efe:a22:8a0f/128"],"kernel_version":"10.0.14393.1715 (rs1_release_inmarket.170906-1810)","mac_addresses":["02:d9:53:4f:42:d8","00:00:00:00:00:00:00:e0","00:00:00:00:00:00:00:e0"],"os":{"family":"windows","platform":"windows","name":"Windows Server 2016 Datacenter","version":"10.0","major":10,"minor":0,"patch":0,"build":"14393.1715"},"timezone":"GMT","timezone_offset_sec":0,"id":"31e2265d-393d-4e51-bffb-e2e2e71580a3"}}}
2018-08-06T13:19:47.552Z	INFO	instance/beat.go:273	Setup Beat: winlogbeat; Version: 7.0.0-alpha1
2018-08-06T13:19:47.552Z	DEBUG	[beat]	instance/beat.go:290	Initializing output plugins
2018-08-06T13:19:47.552Z	DEBUG	[processors]	processors/processor.go:66	Processors: 
2018-08-06T13:19:47.553Z	DEBUG	[rotator]	file/rotator.go:135	Initialized file rotator	{"rotator": {"filename": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\winlogbeat\\label\\windows\\src\\github.com\\elastic\\beats\\winlogbeat\\build\\system-tests\\run\\test_eventlogging.Test.test_fields_not_under_root\\output\\winlogbeat", "max_size_bytes": 1024000, "max_backups": 7, "permissions": "-rw-------"}}
2018-08-06T13:19:47.553Z	INFO	fileout/file.go:94	Initialized file output. path=C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root\output\winlogbeat max_size_bytes=1024000 max_backups=7 permissions=-rw-------
2018-08-06T13:19:47.554Z	DEBUG	[publish]	pipeline/consumer.go:137	start pipeline event consumer
2018-08-06T13:19:47.554Z	INFO	pipeline/module.go:98	Beat name: WORKER-08BCCEE0
2018-08-06T13:19:47.554Z	INFO	beater/winlogbeat.go:68	State will be read from and persisted to C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\winlogbeat\label\windows\src\github.com\elastic\beats\winlogbeat\build\system-tests\run\test_eventlogging.Test.test_fields_not_under_root\data\.winlogbeat.yml
2018-08-06T13:19:47.554Z	DEBUG	[eventlog]	eventlog/factory.go:128	Checking eventlogging
2018-08-06T13:19:47.554Z	DEBUG	[eventlog]	eventlog/factory.go:130	Using eventlogging API for event log WinlogbeatTestPython
2018-08-06T13:19:47.555Z	DEBUG	[winlogbeat]	beater/winlogbeat.go:95	Initialized EventLog[WinlogbeatTestPython]
2018-08-06T13:19:47.555Z	DEBUG	[processors]	processors/processor.go:66	Processors: 
2018-08-06T13:19:47.556Z	INFO	[monitoring]	log/log.go:114	Starting metrics logging every 30s
2018-08-06T13:19:47.556Z	INFO	instance/beat.go:367	winlogbeat start running.
2018-08-06T13:19:47.556Z	DEBUG	[service]	service/service_windows.go:68	Windows is interactive: false
2018-08-06T13:19:47.557Z	ERROR	service/service_windows.go:76	Error: The service process could not connect to the service controller.
2018-08-06T13:19:47.562Z	DEBUG	[eventlog_detail]	eventlog/eventlogging.go:99	EventLogging[WinlogbeatTestPython] Open(recordNumber=0) calling OpenEventLog(uncServerPath=, providerName=WinlogbeatTestPython)
2018-08-06T13:19:47.562Z	INFO	eventlog/eventlogging.go:133	EventLogging[WinlogbeatTestPython] contains 2 records. Record number range [29629, 29630]. Starting at 29629 (ignoringFirst=false)
2018-08-06T13:19:47.562Z	DEBUG	[winlogbeat]	beater/eventlogger.go:117	EventLog[WinlogbeatTestPython] opened successfully
2018-08-06T13:19:47.563Z	DEBUG	[eventlog_detail]	eventlog/eventlogging.go:166	EventLogging[WinlogbeatTestPython] ReadEventLog read 412 bytes
2018-08-06T13:19:47.564Z	DEBUG	[eventlog]	eventlogging/eventlogging_windows.go:503	RegOpenKey opened handle to HKLM\SYSTEM\CurrentControlSet\Services\EventLog\WinlogbeatTestPython\SystemTest, key=604
2018-08-06T13:19:47.564Z	DEBUG	[eventlog]	eventlogging/eventlogging_windows.go:521	RegQueryValueEx queried EventMessageFile from HKLM\SYSTEM\CurrentControlSet\Services\EventLog\WinlogbeatTestPython\SystemTest and got [C:\Windows\system32\EventCreate.exe]
2018-08-06T13:19:47.564Z	DEBUG	[eventlog]	eventlogging/eventlogging_windows.go:545	Returning message files [{File:C:\Windows\system32\EventCreate.exe Handle:84606977 Err:<nil>}] for sourceName SystemTest
2018-08-06T13:19:47.564Z	DEBUG	[eventlog]	eventlog/cache.go:86	messageFilesCache[WinlogbeatTestPython] size=1
2018-08-06T13:19:47.565Z	DEBUG	[eventlog_detail]	eventlog/eventlogging.go:174	EventLogging[WinlogbeatTestPython] RenderEvents returned 2 events
2018-08-06T13:19:47.565Z	DEBUG	[eventlog]	eventlog/eventlogging.go:207	EventLogging[WinlogbeatTestPython] Read() is returning 2 records
2018-08-06T13:19:47.565Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 2 records
2018-08-06T13:19:47.566Z	DEBUG	[publish]	pipeline/processor.go:308	Publish event: {
  "@timestamp": "2018-08-06T10:56:25.000Z",
  "@metadata": {
    "beat": "winlogbeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "level": "Information",
  "beat": {
    "name": "WORKER-08BCCEE0",
    "hostname": "WORKER-08BCCEE0",
    "version": "7.0.0-alpha1"
  },
  "log_name": "WinlogbeatTestPython",
  "source_name": "SystemTest",
  "event_id": 10,
  "type": "eventlogging",
  "event_data": {
    "param1": "Add tags and fields under root"
  },
  "fields": {
    "global": "field",
    "env": "dev",
    "num": 1,
    "local": "field",
    "level": "overwrite"
  },
  "host": {
    "name": "WORKER-08BCCEE0"
  },
  "computer_name": "WORKER-08BCCEE0",
  "record_number": "29629",
  "message": "Add tags and fields under root",
  "user": {
    "identifier": "S-1-5-21-2485467087-2958747450-187013876-1004",
    "name": "jenkins",
    "domain": "WORKER-08BCCEE0",
    "type": "User"
  }
}
2018-08-06T13:19:47.567Z	DEBUG	[publish]	pipeline/processor.go:308	Publish event: {
  "@timestamp": "2018-08-06T13:19:47.000Z",
  "@metadata": {
    "beat": "winlogbeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "type": "eventlogging",
  "message": "Add fields (not under root)",
  "fields": {
    "env": "dev",
    "num": 1,
    "local": "field",
    "level": "overwrite",
    "global": "field"
  },
  "host": {
    "name": "WORKER-08BCCEE0"
  },
  "computer_name": "WORKER-08BCCEE0",
  "record_number": "29630",
  "user": {
    "type": "User",
    "identifier": "S-1-5-21-2485467087-2958747450-187013876-1004",
    "name": "jenkins",
    "domain": "WORKER-08BCCEE0"
  },
  "event_data": {
    "param1": "Add fields (not under root)"
  },
  "source_name": "SystemTest",
  "level": "Information",
  "log_name": "WinlogbeatTestPython",
  "event_id": 10,
  "beat": {
    "name": "WORKER-08BCCEE0",
    "hostname": "WORKER-08BCCEE0",
    "version": "7.0.0-alpha1"
  }
}
2018-08-06T13:19:47.568Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-08-06T13:19:47.568Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-08-06T13:19:47.668Z	DEBUG	[memqueue]	memqueue/ackloop.go:160	ackloop: receive ack [0: 0, 2]
2018-08-06T13:19:47.668Z	DEBUG	[memqueue]	memqueue/eventloop.go:535	broker ACK events: count=2, start-seq=1, end-seq=2

2018-08-06T13:19:47.668Z	DEBUG	[memqueue]	memqueue/ackloop.go:128	ackloop: return ack to broker loop:2
2018-08-06T13:19:47.668Z	DEBUG	[memqueue]	memqueue/ackloop.go:131	ackloop:  done send ack
2018-08-06T13:19:47.668Z	INFO	beater/eventlogger.go:73	EventLog[WinlogbeatTestPython] successfully published 2 events
2018-08-06T13:19:48.570Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-08-06T13:19:48.570Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-08-06T13:19:49.571Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-08-06T13:19:49.571Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-08-06T13:19:50.573Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-08-06T13:19:50.573Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-08-06T13:19:51.575Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-08-06T13:19:51.575Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-08-06T13:19:52.565Z	DEBUG	[checkpoint]	checkpoint/checkpoint.go:203	Checkpoint saved to disk. numUpdates=1
2018-08-06T13:19:52.577Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-08-06T13:19:52.577Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-08-06T13:19:53.579Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-08-06T13:19:53.579Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-08-06T13:19:54.581Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-08-06T13:19:54.581Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-08-06T13:19:55.583Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-08-06T13:19:55.583Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
2018-08-06T13:19:56.585Z	DEBUG	[eventlog]	eventlog/eventlogging.go:163	EventLogging[WinlogbeatTestPython] ReadEventLog returned error Reached the end of the file.
2018-08-06T13:19:56.585Z	DEBUG	[winlogbeat]	beater/eventlogger.go:133	EventLog[WinlogbeatTestPython] Read() returned 0 records
```

**Comment by andrewkroh** [comment]
The timeout occurred because there were two events in the output and the test expected only one.

You can see from the Winlogbeat output that it received an event from the previous test case. I made a change in https://github.com/elastic/beats/commit/477bc50bd116f5e0c1372f7a04e5a79829cb13b3 to ensure that the previous logs were cleared but that appears to not be effective.

So I'm thinking to use a unique event log name for each test case and see if this improves the situation.
