### ISSUE TITLE
Master "packetbeat -version" crashes

### ISSUE THREAD

**Issue by McStork** [elastic/beats#804]
Hi,
here is what happened when I ran ```packetbeat -version``` with master:
```
packetbeat version 1.2.0-SNAPSHOT (amd64)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x465140]

goroutine 1 [running]:
github.com/elastic/beats/packetbeat/beat.(*Packetbeat).Stop(0xc82056f200)
	/root/workspace/src/github.com/elastic/beats/packetbeat/beat/packetbeat.go:257 +0x20
github.com/elastic/beats/libbeat/beat.(*Beat).Stop(0xc8200a6360)
	/root/workspace/src/github.com/elastic/beats/libbeat/beat/beat.go:262 +0x77
github.com/elastic/beats/libbeat/beat.Run(0xb2beb0, 0xa, 0x0, 0x0, 0x7fede0125348, 0xc82056f200, 0x0, 0x0)
	/root/workspace/src/github.com/elastic/beats/libbeat/beat/beat.go:127 +0xd0
main.main()
	/root/workspace/src/github.com/elastic/beats/packetbeat/main.go:13 +0xd5

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/root/go-1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/root/go-1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/root/go-1.5/src/os/signal/signal_unix.go:28 +0x37
zsh: exit 2     ./packetbeat -version
```

**Comment by ruflin** [comment]
This should be fixed as soon as https://github.com/elastic/beats/pull/798 is merged.

**Comment by McStork** [comment]
I should have seen that PR, my bad

**Comment by ruflin** [comment]
@McStork No worries, I only fixed it today

**Comment by andrewkroh** [comment]
We should add a test case for running `-version` to our system tests. Just as a sanity check to make sure we don't regress.
