### ISSUE TITLE
[Filebeat] Flaky test_clean_inactive test

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#8102]
Seen in https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-darwin/3672/beat=filebeat,label=macosx/testReport/junit/test_registrar/Test/test_clean_inactive/ (darwin build)

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/tests/system/test_registrar.py", line 817, in test_clean_inactive
    assert len(data) == 2
AssertionError
```

**Comment by kvch** [comment]
The test failed again on Windows:
Job: https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-windows/5947/beat=filebeat,label=windows/

This seems like a new error, as we are getting permission denied.

```
  File "c:\python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\tests\system\test_registrar.py", line 801, in test_clean_inactive
    assert self.registry.count() == 2
```

Logs
```
2019-03-13T09:50:04.494Z	INFO	instance/beat.go:567	Home path: [C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive] Config path: [C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive] Data path: [C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\data] Logs path: [C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\logs]
2019-03-13T09:50:04.495Z	DEBUG	[beat]	instance/beat.go:619	Beat metadata path: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\data\meta.json
2019-03-13T09:50:04.498Z	INFO	instance/beat.go:574	Beat ID: bfe72295-d6fb-47c3-86f5-86402153c3cb
2019-03-13T09:50:04.499Z	INFO	[index-management.ilm]	ilm/ilm.go:123	Policy name: filebeat-8.0.0
2019-03-13T09:50:04.499Z	DEBUG	[seccomp]	seccomp/seccomp.go:88	Syscall filtering is only supported on Linux
2019-03-13T09:50:04.499Z	INFO	[beat]	instance/beat.go:822	Beat info	{"system_info": {"beat": {"path": {"config": "C:\\Users\\jenkins\\workspace\\elastic+beats+pull-request+multijob-windows\\beat\\filebeat\\label\\windows\\src\\github.com\\elastic\\beats\\filebeat\\build\\system-tests\\run\\test_registrar.Test.test_clean_inactive", "data": "C:\\Users\\jenkins\\workspace\\elastic+beats+pull-request+multijob-windows\\beat\\filebeat\\label\\windows\\src\\github.com\\elastic\\beats\\filebeat\\build\\system-tests\\run\\test_registrar.Test.test_clean_inactive\\data", "home": "C:\\Users\\jenkins\\workspace\\elastic+beats+pull-request+multijob-windows\\beat\\filebeat\\label\\windows\\src\\github.com\\elastic\\beats\\filebeat\\build\\system-tests\\run\\test_registrar.Test.test_clean_inactive", "logs": "C:\\Users\\jenkins\\workspace\\elastic+beats+pull-request+multijob-windows\\beat\\filebeat\\label\\windows\\src\\github.com\\elastic\\beats\\filebeat\\build\\system-tests\\run\\test_registrar.Test.test_clean_inactive\\logs"}, "type": "filebeat", "uuid": "bfe72295-d6fb-47c3-86f5-86402153c3cb"}}}
2019-03-13T09:50:04.500Z	INFO	[beat]	instance/beat.go:831	Build info	{"system_info": {"build": {"commit": "unknown", "libbeat": "8.0.0", "time": "1754-08-30T22:43:41.128Z", "version": "8.0.0"}}}
2019-03-13T09:50:04.500Z	INFO	[beat]	instance/beat.go:834	Go runtime info	{"system_info": {"go": {"os":"windows","arch":"amd64","max_procs":4,"version":"go1.11.5"}}}
2019-03-13T09:50:04.506Z	INFO	[beat]	instance/beat.go:838	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2019-02-15T04:09:37.01Z","name":"beats-ci-windows-2016-worker-x404","ip":["10.224.0.58/20","::1/128","127.0.0.1/8"],"kernel_version":"10.0.14393.2791 (rs1_release.190205-1511)","mac":["42:01:0a:e0:00:3a"],"os":{"family":"windows","platform":"windows","name":"Windows Server 2016 Datacenter","version":"10.0","major":10,"minor":0,"patch":0,"build":"14393.2791"},"timezone":"GMT","timezone_offset_sec":0,"id":"6842dd29-0e3c-4995-8486-4fa7fee5897f"}}}
2019-03-13T09:50:04.509Z	INFO	[beat]	instance/beat.go:867	Process info	{"system_info": {"process": {"cwd": "C:\\Users\\jenkins\\workspace\\elastic+beats+pull-request+multijob-windows\\beat\\filebeat\\label\\windows\\src\\github.com\\elastic\\beats\\filebeat\\tests\\system", "exe": "C:\\Users\\jenkins\\workspace\\elastic+beats+pull-request+multijob-windows\\beat\\filebeat\\label\\windows\\src\\github.com\\elastic\\beats\\filebeat\\filebeat.test.exe", "name": "filebeat.test.exe", "pid": 2388, "ppid": 4972, "start_time": "2019-03-13T09:50:04.350Z"}}}
2019-03-13T09:50:04.509Z	INFO	instance/beat.go:276	Setup Beat: filebeat; Version: 8.0.0
2019-03-13T09:50:04.510Z	DEBUG	[beat]	instance/beat.go:297	Initializing output plugins
2019-03-13T09:50:04.510Z	DEBUG	[rotator]	file/rotator.go:165	Initialized file rotator	{"rotator": {"filename": "C:\\Users\\jenkins\\workspace\\elastic+beats+pull-request+multijob-windows\\beat\\filebeat\\label\\windows\\src\\github.com\\elastic\\beats\\filebeat\\build\\system-tests\\run\\test_registrar.Test.test_clean_inactive\\output\\filebeat", "max_size_bytes": 1024000, "max_backups": 7, "permissions": "-rw-------", "interval": 0}}
2019-03-13T09:50:04.511Z	INFO	fileout/file.go:98	Initialized file output. path=C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\output\filebeat max_size_bytes=1024000 max_backups=7 permissions=-rw-------
2019-03-13T09:50:04.512Z	DEBUG	[publisher]	pipeline/consumer.go:137	start pipeline event consumer
2019-03-13T09:50:04.512Z	INFO	[publisher]	pipeline/module.go:97	Beat name: beats-ci-windows-2016-worker-x404
2019-03-13T09:50:04.513Z	ERROR	fileset/modules.go:125	Not loading modules. Module directory not found: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\module
2019-03-13T09:50:04.514Z	INFO	[monitoring]	log/log.go:117	Starting metrics logging every 30s
2019-03-13T09:50:04.514Z	INFO	instance/beat.go:387	filebeat start running.
2019-03-13T09:50:04.515Z	DEBUG	[service]	service/service_windows.go:72	Windows is interactive: false
2019-03-13T09:50:04.516Z	DEBUG	[test]	registrar/migrate.go:159	isFile(C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive/registry) -> false
2019-03-13T09:50:04.516Z	DEBUG	[test]	registrar/migrate.go:159	isFile() -> false
2019-03-13T09:50:04.516Z	INFO	service/service_windows.go:101	Attempted to register Windows service handlers, but this is not a service. No action necessary
2019-03-13T09:50:04.516Z	DEBUG	[test]	registrar/migrate.go:152	isDir(C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\registry\filebeat) -> false
2019-03-13T09:50:04.517Z	DEBUG	[registrar]	registrar/migrate.go:51	Registry type '' found
2019-03-13T09:50:04.517Z	DEBUG	[test]	registrar/migrate.go:159	isFile(.bak) -> false
2019-03-13T09:50:04.517Z	DEBUG	[test]	registrar/migrate.go:152	isDir(C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\registry\filebeat) -> false
2019-03-13T09:50:04.518Z	INFO	registrar/migrate.go:104	No registry home found. Create: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\registry\filebeat
2019-03-13T09:50:04.519Z	DEBUG	[test]	registrar/migrate.go:159	isFile(C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\registry\filebeat\meta.json) -> false
2019-03-13T09:50:04.519Z	INFO	registrar/migrate.go:112	Initialize registry meta file
2019-03-13T09:50:04.525Z	INFO	registrar/registrar.go:108	No registry file found under: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\registry\filebeat\data.json. Creating a new registry file.
2019-03-13T09:50:04.525Z	DEBUG	[registrar]	registrar/registrar.go:411	Write registry file: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\registry\filebeat\data.json (0)
2019-03-13T09:50:04.530Z	DEBUG	[registrar]	registrar/registrar.go:404	Registry file updated. 0 states written.
2019-03-13T09:50:04.531Z	INFO	registrar/registrar.go:145	Loading registrar data from C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\registry\filebeat\data.json
2019-03-13T09:50:04.531Z	INFO	registrar/registrar.go:152	States Loaded from registrar: 0
2019-03-13T09:50:04.531Z	WARN	beater/filebeat.go:357	Filebeat is unable to load the Ingest Node pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the Ingest Node pipelines or are using Logstash pipelines, you can ignore this warning.
2019-03-13T09:50:04.531Z	INFO	crawler/crawler.go:72	Loading Inputs: 1
2019-03-13T09:50:04.531Z	DEBUG	[registrar]	registrar/registrar.go:278	Starting Registrar
2019-03-13T09:50:04.534Z	DEBUG	[input]	log/config.go:201	recursive glob enabled
2019-03-13T09:50:04.536Z	DEBUG	[input]	log/input.go:147	exclude_files: []. Number of stats: 0
2019-03-13T09:50:04.536Z	DEBUG	[input]	log/input.go:168	input with previous states loaded: 0
2019-03-13T09:50:04.536Z	INFO	log/input.go:138	Configured paths: [C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input*]
2019-03-13T09:50:04.536Z	INFO	input/input.go:114	Starting input of type: log; ID: 12892374043777181742 
2019-03-13T09:50:04.536Z	INFO	crawler/crawler.go:106	Loading and starting Inputs completed. Enabled inputs: 1
2019-03-13T09:50:04.536Z	DEBUG	[input]	log/input.go:174	Start next scan
2019-03-13T09:50:04.538Z	DEBUG	[input]	log/input.go:404	Check file for harvesting: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1
2019-03-13T09:50:04.538Z	DEBUG	[input]	log/input.go:477	Start harvester for new file: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1
2019-03-13T09:50:04.539Z	DEBUG	[harvester]	log/harvester.go:493	Setting offset for file based on seek: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1
2019-03-13T09:50:04.540Z	DEBUG	[harvester]	log/harvester.go:479	Setting offset for file: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1. Offset: 0 
2019-03-13T09:50:04.540Z	DEBUG	[acker]	beater/acker.go:64	stateful ack	{"count": 1}
2019-03-13T09:50:04.540Z	DEBUG	[publisher]	pipeline/client.go:200	Pipeline client receives callback 'onFilteredOut' for event: %+v{0001-01-01 00:00:00 +0000 UTC null null { false 0xc0000f02a0 C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1 0 2019-03-13 09:50:04.5380574 +0000 GMT m=+0.171810601 3s log map[] 7012352-1526584-3634495929}}
2019-03-13T09:50:04.540Z	DEBUG	[harvester]	log/harvester.go:398	Update state: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1, offset: 0
2019-03-13T09:50:04.540Z	DEBUG	[registrar]	registrar/registrar.go:356	Processing 1 events
2019-03-13T09:50:04.540Z	DEBUG	[input]	file/states.go:68	New state added for C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1
2019-03-13T09:50:04.540Z	DEBUG	[input]	file/states.go:68	New state added for C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1
2019-03-13T09:50:04.540Z	DEBUG	[registrar]	registrar/registrar.go:326	Registrar state updates processed. Count: 1
2019-03-13T09:50:04.540Z	DEBUG	[registrar]	registrar/registrar.go:346	Registrar states cleaned up. Before: 1, After: 1, Pending: 1
2019-03-13T09:50:04.540Z	DEBUG	[registrar]	registrar/registrar.go:411	Write registry file: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\registry\filebeat\data.json (1)
2019-03-13T09:50:04.540Z	DEBUG	[input]	log/input.go:404	Check file for harvesting: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2
2019-03-13T09:50:04.541Z	DEBUG	[input]	log/input.go:477	Start harvester for new file: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2
2019-03-13T09:50:04.541Z	INFO	log/harvester.go:254	Harvester started for file: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1
2019-03-13T09:50:04.541Z	INFO	[detect_null_bytes]	debug/debug.go:95	Starting debug reader with a buffer size of 16384 and max failures of 100
2019-03-13T09:50:04.543Z	DEBUG	[harvester]	log/harvester.go:493	Setting offset for file based on seek: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2
2019-03-13T09:50:04.543Z	DEBUG	[harvester]	log/harvester.go:479	Setting offset for file: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2. Offset: 0 
2019-03-13T09:50:04.543Z	DEBUG	[processors]	processing/processors.go:183	Publish event: {
  "@timestamp": "2019-03-13T09:50:04.541Z",
  "@metadata": {
    "beat": "",
    "type": "_doc",
    "version": ""
  },
  "log": {
    "offset": 0,
    "file": {
      "path": "C:\\Users\\jenkins\\workspace\\elastic+beats+pull-request+multijob-windows\\beat\\filebeat\\label\\windows\\src\\github.com\\elastic\\beats\\filebeat\\build\\system-tests\\run\\test_registrar.Test.test_clean_inactive\\log\\input1"
    }
  },
  "message": "first file",
  "input": {
    "type": "log"
  },
  "ecs": {
    "version": "1.0.0-beta2"
  },
  "host": {
    "name": "beats-ci-windows-2016-worker-x404"
  },
  "agent": {
    "version": "8.0.0",
    "type": "filebeat",
    "ephemeral_id": "d1beadf4-2531-4aa6-b144-8d8013b3abde",
    "hostname": "beats-ci-windows-2016-worker-x404",
    "id": "bfe72295-d6fb-47c3-86f5-86402153c3cb"
  }
}
2019-03-13T09:50:04.543Z	DEBUG	[harvester]	log/log.go:102	End of file reached: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1; Backoff now.
2019-03-13T09:50:04.543Z	DEBUG	[publisher]	pipeline/client.go:200	Pipeline client receives callback 'onFilteredOut' for event: %+v{0001-01-01 00:00:00 +0000 UTC null null { false 0xc0000f04d0 C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2 0 2019-03-13 09:50:04.5419674 +0000 GMT m=+0.175720601 3s log map[] 3932160-1526585-3634495929}}
2019-03-13T09:50:04.543Z	DEBUG	[harvester]	log/harvester.go:398	Update state: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2, offset: 0
2019-03-13T09:50:04.543Z	DEBUG	[input]	file/states.go:68	New state added for C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2
2019-03-13T09:50:04.543Z	DEBUG	[input]	log/input.go:195	input states cleaned up. Before: 2, After: 2, Pending: 2
2019-03-13T09:50:04.544Z	INFO	log/harvester.go:254	Harvester started for file: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2
2019-03-13T09:50:04.545Z	INFO	[detect_null_bytes]	debug/debug.go:95	Starting debug reader with a buffer size of 16384 and max failures of 100
2019-03-13T09:50:04.546Z	DEBUG	[processors]	processing/processors.go:183	Publish event: {
  "@timestamp": "2019-03-13T09:50:04.545Z",
  "@metadata": {
    "beat": "",
    "type": "_doc",
    "version": ""
  },
  "agent": {
    "type": "filebeat",
    "ephemeral_id": "d1beadf4-2531-4aa6-b144-8d8013b3abde",
    "hostname": "beats-ci-windows-2016-worker-x404",
    "id": "bfe72295-d6fb-47c3-86f5-86402153c3cb",
    "version": "8.0.0"
  },
  "ecs": {
    "version": "1.0.0-beta2"
  },
  "log": {
    "offset": 0,
    "file": {
      "path": "C:\\Users\\jenkins\\workspace\\elastic+beats+pull-request+multijob-windows\\beat\\filebeat\\label\\windows\\src\\github.com\\elastic\\beats\\filebeat\\build\\system-tests\\run\\test_registrar.Test.test_clean_inactive\\log\\input2"
    }
  },
  "message": "second file",
  "input": {
    "type": "log"
  },
  "host": {
    "name": "beats-ci-windows-2016-worker-x404"
  }
}
2019-03-13T09:50:04.546Z	DEBUG	[harvester]	log/log.go:102	End of file reached: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2; Backoff now.
2019-03-13T09:50:04.547Z	DEBUG	[registrar]	registrar/registrar.go:404	Registry file updated. 1 states written.
2019-03-13T09:50:04.644Z	DEBUG	[harvester]	log/log.go:102	End of file reached: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1; Backoff now.
2019-03-13T09:50:04.645Z	DEBUG	[input]	input/input.go:152	Run input
2019-03-13T09:50:04.645Z	DEBUG	[input]	log/input.go:174	Start next scan
2019-03-13T09:50:04.646Z	DEBUG	[input]	log/input.go:404	Check file for harvesting: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1
2019-03-13T09:50:04.646Z	DEBUG	[input]	log/input.go:494	Update existing file for harvesting: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1, offset: 12
2019-03-13T09:50:04.646Z	DEBUG	[input]	log/input.go:546	Harvester for file is still running: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input1
2019-03-13T09:50:04.646Z	DEBUG	[input]	log/input.go:404	Check file for harvesting: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2
2019-03-13T09:50:04.646Z	DEBUG	[input]	log/input.go:494	Update existing file for harvesting: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2, offset: 13
2019-03-13T09:50:04.646Z	DEBUG	[input]	log/input.go:546	Harvester for file is still running: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2
2019-03-13T09:50:04.647Z	DEBUG	[input]	log/input.go:195	input states cleaned up. Before: 2, After: 2, Pending: 2
2019-03-13T09:50:04.647Z	DEBUG	[harvester]	log/log.go:102	End of file reached: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2; Backoff now.
2019-03-13T09:50:04.648Z	DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [0: 0, 2]
2019-03-13T09:50:04.648Z	DEBUG	[publisher]	memqueue/eventloop.go:535	broker ACK events: count=2, start-seq=1, end-seq=2

2019-03-13T09:50:04.648Z	DEBUG	[publisher]	memqueue/ackloop.go:128	ackloop: return ack to broker loop:2
2019-03-13T09:50:04.648Z	DEBUG	[publisher]	memqueue/ackloop.go:131	ackloop:  done send ack
2019-03-13T09:50:04.648Z	DEBUG	[acker]	beater/acker.go:64	stateful ack	{"count": 3}
2019-03-13T09:50:04.649Z	DEBUG	[registrar]	registrar/registrar.go:356	Processing 3 events
2019-03-13T09:50:04.649Z	DEBUG	[input]	file/states.go:68	New state added for C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\log\input2
2019-03-13T09:50:04.649Z	DEBUG	[registrar]	registrar/registrar.go:326	Registrar state updates processed. Count: 3
2019-03-13T09:50:04.649Z	DEBUG	[registrar]	registrar/registrar.go:346	Registrar states cleaned up. Before: 2, After: 2, Pending: 2
2019-03-13T09:50:04.649Z	DEBUG	[registrar]	registrar/registrar.go:411	Write registry file: C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\registry\filebeat\data.json (2)
2019-03-13T09:50:04.658Z	ERROR	registrar/registrar.go:374	Writing of registry returned error: rename C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\registry\filebeat\data.json.new C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\build\system-tests\run\test_registrar.Test.test_clean_inactive\registry\filebeat\data.json: Access is denied.. Continuing...
```

**Comment by ruflin** [comment]
Here more recent artifacts from a build: 
[test_registrar.Test.test_clean_inactive.zip](https://github.com/elastic/beats/files/3032934/test_registrar.Test.test_clean_inactive.zip)

**Comment by rickardp** [comment]
This test failed on Macos
https://travis-ci.org/elastic/beats/jobs/562466869
