### ISSUE TITLE
cherrypick_pr script errors out when used with --continue

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#8299]
For example, running the following command:

```sh
dev-tools/cherrypick_pr --yes --create_pr --continue 6.x 8259 9383779
```

Results in the following error:

```sh
Namespace(commit_hashes=['9383779'], continue=True, create_pr=True, diff=False, from_branch='master', pr_number='8259', to_branch='6.x', yes=True)
Ready to push branch.
To which remote should I push? (your fork): origin
error: unable to delete 'backport_8259_6.x': remote ref does not exist
error: failed to push some refs to 'git@github.com:ycombinator/beats.git'
error: src refspec backport_8259_6.x does not match any.
error: failed to push some refs to 'git@github.com:ycombinator/beats.git'
Traceback (most recent call last):
  File "dev-tools/cherrypick_pr", line 171, in <module>
    sys.exit(main())
  File "dev-tools/cherrypick_pr", line 114, in main
    .format(remote, tmp_branch), shell=True)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git push --set-upstream origin backport_8259_6.x' returned non-zero exit status 1
```

However, running the same command without the `--continue` flag succeeds.

**Comment by ycombinator** [comment]
Sorry folks, PEBCAK! 

`--continue` is only meant to be used *if there are backport errors*, not pre-emptively, every time like I was trying to.
