### ISSUE TITLE
Filebeat panic with bad configuration 

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#8895]
Filebeat will panic on startup with an invalid configuration. Is it possible to exit with a nicer error under this condition?

- Version: filebeat-6.4.2
- Operating System: 
```
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75
```
- Steps to Reproduce: 
Start Filebeat with the following configuration (note `dissect` is incomplete)
```
filebeat.inputs:
- type: log
  paths:
    - /path/to/log
processors:
 - dissect:  

output.console:
  pretty: true
logging.level: info
logging.selectors: ["*"]
```

Error:
```
./filebeat -c conf/bug_panic.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x48e3a5a]

goroutine 57 [running]:
github.com/elastic/beats/libbeat/processors/dissect.(*Dissector).extract(0x0, 0xc42009e1c0, 0x6b, 0x7, 0x4a53600, 0xc4202eb3d0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/processors/dissect/dissect.go:72 +0x3a
github.com/elastic/beats/libbeat/processors/dissect.(*Dissector).Dissect(0x0, 0xc42009e1c0, 0x6b, 0x4a53600, 0xc4202eb3d0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/processors/dissect/dissect.go:52 +0x4c
github.com/elastic/beats/libbeat/processors/dissect.(*processor).Run(0xc4201594a0, 0xc4201b9cc0, 0x0, 0xffffffffffffffff, 0xc4204c8b70)
	/go/src/github.com/elastic/beats/libbeat/processors/dissect/processor.go:61 +0x9f
github.com/elastic/beats/libbeat/publisher/pipeline.(*program).Run(0xc420159a70, 0xc4201b9cc0, 0xc4201b9cc0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/publisher/pipeline/processor.go:167 +0xad
github.com/elastic/beats/libbeat/publisher/pipeline.(*program).Run(0xc420320c90, 0xc4201b9cc0, 0x0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/publisher/pipeline/processor.go:167 +0xad
github.com/elastic/beats/libbeat/publisher/pipeline.(*client).publish(0xc4203e0360, 0xbeeef36606b7af7d, 0x2f41749, 0x53bf6a0, 0x0, 0xc42046ecc0, 0x4bce560, 0xc42013e750)
	/go/src/github.com/elastic/beats/libbeat/publisher/pipeline/client.go:84 +0x474
github.com/elastic/beats/libbeat/publisher/pipeline.(*client).Publish(0xc4203e0360, 0xbeeef36606b7af7d, 0x2f41749, 0x53bf6a0, 0x0, 0xc42046ecc0, 0x4bce560, 0xc42013e750)
	/go/src/github.com/elastic/beats/libbeat/publisher/pipeline/client.go:63 +0x95
github.com/elastic/beats/filebeat/channel.(*outlet).OnEvent(0xc420320d80, 0xc4200e2300, 0x4cf8901)
	/go/src/github.com/elastic/beats/filebeat/channel/outlet.go:63 +0x1e2
github.com/elastic/beats/filebeat/channel.SubOutlet.func1(0xc42046ec90, 0x4cee800, 0xc420320d80)
	/go/src/github.com/elastic/beats/filebeat/channel/util.go:54 +0x61
created by github.com/elastic/beats/filebeat/channel.SubOutlet
	/go/src/github.com/elastic/beats/filebeat/channel/util.go:52 +0x101
```

**Comment by ruflin** [comment]
@ph Cany ou have a look?

**Comment by ph** [comment]
I will take a look, From the trace I think the config is not correctly defined to have required fields.
