### ISSUE TITLE
Panic when using central config

### ISSUE THREAD

**Issue by tsg** [elastic/beats#9000]
I somehow managed to create a panic when using central config. This happened when I tried to enable a Filebeat input.

cc @exekias @ph 

```
2018-11-08T19:25:30.143+0100	INFO	[monitoring]	log/log.go:144	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":40,"time":{"ms":1}},"total":{"ticks":135,"time":{"ms":2},"value":135},"user":{"ticks":95,"time":{"ms":1}}},"info":{"ephemeral_id":"2e516e65-7d28-4ab8-85f8-f031b465544c","uptime":{"ms":120038}},"memstats":{"gc_next":5875456,"memory_alloc":4239032,"memory_total":9838760,"rss":520192}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":0,"events":{"active":0}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":3.5381,"15":3.792,"5":3.4038,"norm":{"1":0.8845,"15":0.948,"5":0.851}}}}}}
2018-11-08T19:25:33.606+0100	INFO	[centralmgmt]	management/manager.go:176	New configurations retrieved
2018-11-08T19:25:33.606+0100	INFO	[centralmgmt]	management/manager.go:198	Applying settings for output
panic: name output already used

goroutine 40 [running]:
github.com/elastic/beats/libbeat/monitoring.panicErr(0x4dc5e00, 0xc42015d510)
	/go/src/github.com/elastic/beats/libbeat/monitoring/registry.go:257 +0x4a
github.com/elastic/beats/libbeat/monitoring.(*Registry).Add(0xc42016a080, 0x4cf4b83, 0x6, 0x4dc61c0, 0xc420248fc0, 0x101)
	/go/src/github.com/elastic/beats/libbeat/monitoring/registry.go:155 +0xd5
github.com/elastic/beats/libbeat/monitoring.(*Registry).NewRegistry(0xc42016a080, 0x4cf4b83, 0x6, 0x0, 0x0, 0x0, 0x4cf43d3)
	/go/src/github.com/elastic/beats/libbeat/monitoring/registry.go:94 +0x13f
github.com/elastic/beats/libbeat/publisher/pipeline.loadOutput(0x4cf715b, 0x8, 0x4cf715b, 0x8, 0x4cf2be5, 0x5, 0xc42038ce00, 0x13, 0xc42038ce00, 0x13, ...)
	/go/src/github.com/elastic/beats/libbeat/publisher/pipeline/module.go:137 +0x3c0
github.com/elastic/beats/libbeat/publisher/pipeline.(*outputController).Reload(0xc42017a1a0, 0xc42015d270, 0x0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/publisher/pipeline/controller.go:161 +0x140
github.com/elastic/beats/x-pack/libbeat/management.(*ConfigManager).reload(0xc4200bab90, 0xc4206c0c18, 0x6, 0xc42000e1f8, 0x1, 0x1, 0x2, 0x0)
	/go/src/github.com/elastic/beats/x-pack/libbeat/management/manager.go:213 +0x660
github.com/elastic/beats/x-pack/libbeat/management.(*ConfigManager).apply(0xc4200bab90)
	/go/src/github.com/elastic/beats/x-pack/libbeat/management/manager.go:185 +0x11f
github.com/elastic/beats/x-pack/libbeat/management.(*ConfigManager).worker(0xc4200bab90)
	/go/src/github.com/elastic/beats/x-pack/libbeat/management/manager.go:144 +0x28a
created by github.com/elastic/beats/x-pack/libbeat/management.(*ConfigManager).Start
	/go/src/github.com/elastic/beats/x-pack/libbeat/management/manager.go:104 +0xe9
```

**Comment by exekias** [comment]
This is probably a duplicate of https://github.com/elastic/beats/pull/8932, are you using a recent BC?

**Comment by ph** [comment]
This indeed look like #8932, what BC are you using?

**Comment by tsg** [comment]
I checked based on the build hash that I was running an older version than that fix. Sorry for the noise folks.
