### ISSUE TITLE
[Filebeat] Flaky test test_harvester.Test.test_close_removed

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#9214]
## Flaky Test

* **Test Name:** test_harvester.Test.test_close_removed
* **Link:** https://github.com/elastic/beats/blob/3273894/filebeat/tests/system/test_harvester.py#L78
* **Branch:** master (seen in #9194)
* **Notes:** Windows, seen along with #9213 #9215

### Stack Trace

```
Traceback (most recent call last):
  File "c:\python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\tests\system\test_harvester.py", line 118, in test_close_removed
    max_timeout=10)
  File "C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\tests\system\../../../libbeat/tests/system\beat\beat.py", line 337, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
```

**Comment by ruflin** [comment]
@urso I'm guessing https://github.com/elastic/beats/pull/10747 is going to resolve this one: https://github.com/elastic/beats/pull/10747 Will assign for now to you. If not, please push back.
