### ISSUE TITLE
[Filebeat] Flaky test test_registrar.Test.test_clean_removed_with_clean_inactive

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#9215]
## Flaky Test

* **Test Name:** test_registrar.Test.test_clean_removed_with_clean_inactive
* **Link:** https://github.com/elastic/beats/blob/be187b9/filebeat/tests/system/test_registrar.py#L915
* **Branch:** master (seen in #9194)
* **Notes:** Windows, seen along with #9213 #9214, Mac OSX, seen in #9348
### Stack Trace

```
Traceback (most recent call last):
  File "c:\python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\tests\system\test_registrar.py", line 963, in test_clean_removed_with_clean_inactive
    self.wait_until(lambda: self.log_contains_count("Before: 1, After: 1, Pending: 1") > 5)
  File "C:\Users\jenkins\workspace\elastic+beats+pull-request+multijob-windows\beat\filebeat\label\windows\src\github.com\elastic\beats\filebeat\tests\system\../../../libbeat/tests/system\beat\beat.py", line 337, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
```

**Comment by urso** [comment]
Closed in #10747
