### ISSUE TITLE
[Heartbeat][Flaky test] Panic on http active monitor test

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#9229]
## Flaky Test

* **Test Name:** github.com/elastic/beats/heartbeat/monitors/active/http
* **Branch:** master
* **Artifact Link:** https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/1899/beat=heartbeat,label=ubuntu/console
* **Notes:** Perhaps related to the update to Golang 1.11.2?

### Stack Trace

```
06:44:06 command [go test -race -cover -coverprofile /tmp/gotestcover-807724102 github.com/elastic/beats/heartbeat/monitors/active/http]: exit status 1
06:44:06 ==================
06:44:06 WARNING: DATA RACE
06:44:06 Write at 0x00c000274b80 by goroutine 19:
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.createPingFactory.func1.1()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:166 +0x92
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.call()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:221 +0x7d
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).sigStartWrite()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:216 +0x68
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).writeRequest()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:155 +0x1ca
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).RoundTrip.func1()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:106 +0x72
06:44:06 
06:44:06 Previous read at 0x00c000274b80 by goroutine 50:
06:44:06   [failed to restore the stack]
06:44:06 
06:44:06 Goroutine 19 (running) created at:
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).RoundTrip()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:105 +0x31f
06:44:06   net/http.send()
06:44:06       /var/lib/jenkins/.gvm/versions/go1.11.2.linux.amd64/src/net/http/client.go:250 +0x304
06:44:06   net/http.(*Client).send()
06:44:06       /var/lib/jenkins/.gvm/versions/go1.11.2.linux.amd64/src/net/http/client.go:174 +0x1ca
06:44:06   net/http.(*Client).do()
06:44:06       /var/lib/jenkins/.gvm/versions/go1.11.2.linux.amd64/src/net/http/client.go:641 +0x531
06:44:06   net/http.(*Client).Do()
06:44:06       /var/lib/jenkins/.gvm/versions/go1.11.2.linux.amd64/src/net/http/client.go:509 +0x42
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.execRequest()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:253 +0xdf
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.execPing()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:227 +0x160
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.createPingFactory.func1()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:172 +0x7b8
06:44:06   github.com/elastic/beats/heartbeat/monitors.MakePingIPFactory.func1.1()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/util.go:194 +0x49
06:44:06   github.com/elastic/beats/heartbeat/monitors.MakeSimpleCont.func1()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/util.go:184 +0x41
06:44:06   github.com/elastic/beats/heartbeat/monitors.funcTask.Run()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/util.go:440 +0x38
06:44:06   github.com/elastic/beats/heartbeat/monitors.WithFields.func1()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/util.go:398 +0x6a
06:44:06   github.com/elastic/beats/heartbeat/monitors.funcTask.Run()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/util.go:440 +0x38
06:44:06   github.com/elastic/beats/heartbeat/monitors.TaskRunner.Run-fm()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/util.go:168 +0x4a
06:44:06   github.com/elastic/beats/heartbeat/monitors.annotated.func1()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/util.go:140 +0xdc
06:44:06   github.com/elastic/beats/heartbeat/monitors.MakeJob.func1()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/util.go:127 +0x15b
06:44:06   github.com/elastic/beats/heartbeat/monitors.(*funcJob).Run()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/util.go:438 +0xb2
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.testTLSRequest()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/http_test.go:69 +0x46b
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.runHTTPSServerCheck()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/http_test.go:278 +0x526
06:44:06   github.com/elastic/beats/heartbeat/monitors/active/http.TestHTTPSx509Auth()
06:44:06       /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/http_test.go:326 +0x70d
06:44:06   testing.tRunner()
06:44:06       /var/lib/jenkins/.gvm/versions/go1.11.2.linux.amd64/src/testing/testing.go:827 +0x162
06:44:06 
06:44:06 Goroutine 50 (running) created at:
06:44:06   testing.(*T).Run()
06:44:06       /var/lib/jenkins/.gvm/versions/go1.11.2.linux.amd64/src/testing/testing.go:878 +0x650
06:44:06   testing.runTests.func1()
06:44:06       /var/lib/jenkins/.gvm/versions/go1.11.2.linux.amd64/src/testing/testing.go:1119 +0xa8
06:44:06   testing.tRunner()
06:44:06       /var/lib/jenkins/.gvm/versions/go1.11.2.linux.amd64/src/testing/testing.go:827 +0x162
06:44:06   testing.runTests()
06:44:06       /var/lib/jenkins/.gvm/versions/go1.11.2.linux.amd64/src/testing/testing.go:1117 +0x4ee
06:44:06   testing.(*M).Run()
06:44:06       /var/lib/jenkins/.gvm/versions/go1.11.2.linux.amd64/src/testing/testing.go:1034 +0x2ee
06:44:06   main.main()
06:44:06       _testmain.go:122 +0x332
06:44:06 ==================
06:44:06 panic: runtime error: invalid memory address or nil pointer dereference
06:44:06 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xba6445]
06:44:06 
06:44:06 goroutine 901 [running]:
06:44:06 github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).readResponse(0xc000095800, 0xd9a620, 0xc00007ae00, 0xc000148300, 0x622600, 0xbc1b90, 0x2b4db68, 0x0)
06:44:06 	/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:187 +0x235
06:44:06 github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).RoundTrip.func2(0xc000095800, 0xd9a620, 0xc00007ae00, 0xc000148300, 0xc000148300, 0xc00043e300)
06:44:06 	/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:111 +0x82
06:44:06 created by github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).RoundTrip
06:44:06 	/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/heartbeat/label/ubuntu/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:110 +0x397
06:44:06 FAIL	github.com/elastic/beats/heartbeat/monitors/active/http	3.144s
```

I did not skip this test yet as it's the first time I saw this.

**Comment by andrewvc** [comment]
This should have been fixed in #9539 closing. Thanks for the report!
