### ISSUE TITLE
Multiline not folding up :(

### ISSUE THREAD

**Issue by ajviradia** [elastic/beats#929]
## New filebeat 1.1.0 is not folding multiline in single message.....

**I downloaded installed filebeat 1.1.0 from https://download.elastic.co/beats/filebeat/filebeat_1.1.0_amd64.deb**

**Following is config YAML **
```
filebeat:
  prospectors:
    -
      paths:
        - "/home/myself/temp/*.log"
  include_lines:
    multiline:
      pattern: ^\[
      negate: true
      match: after

output:
  console:
    pretty: true
```

**Following is the log content:**
```
[beat-logstash-some-name-832-2015.11.28] IndexNotFoundException[no such index]
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:566)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:133)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:77)
    at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:75)
[sample-class] IndexNotFoundException[no such index]
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:77)
    at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:75)
   
```

(edit by akroh: I added 3 backticks around pasted content for formatting)

**Comment by ajviradia** [comment]
So it helps someone down the road....

Fix : Corrected indentation in YAML

**Updated YAML**
filebeat:
  prospectors:
    -
      paths:
        - "/home/myself/temp/*.log"
      input_type: log 
      multiline:
        pattern: ^\[
        negate: true
        match: after

output:
  console:
    pretty: true

**Comment by ruflin** [comment]
@ajviradia I'm glad you found a solution and also thanks for posting. In the future please use the discuss form for questions: https://discuss.elastic.co/c/beats/filebeat
