### ISSUE TITLE
stacktrace in heartbeat

### ISSUE THREAD

**Issue by smartrics** [elastic/beats#9556]
```
- Version:  6.5.1
- Operating System: linux centos 7 
```
For our http module configuration 

```
- type: http
  name: foo/bar
  # List or urls to query
  urls: [
    "http://localhost/analytics",
    "https://localhost/analytics"
  ]
  # Configure task schedule
  schedule: "@every 30s"
  username: yyy
  password: zzz
  ssl:
    verification_mode: none
```

We see this stack trace

```
2018-12-14T14:54:24.421Z	ERROR	scheduler/scheduler.go:355	Panic in job foo/bar@https://localhost/analytics'. Recovering, but please report this: runtime error: invalid memory address or nil pointer dereference.
2018-12-14T14:54:24.422Z	ERROR	scheduler/scheduler.go:357	Stacktrace: goroutine 17450 [running]:
runtime/debug.Stack(0x16ad273, 0x3a, 0xc42058c8b8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/elastic/beats/heartbeat/scheduler.(*Scheduler).runTask.func1.1(0xc4201aa6e0, 0xc4203a6080)
	/go/src/github.com/elastic/beats/heartbeat/scheduler/scheduler.go:357 +0xf7
panic(0x14f98a0, 0x1f689f0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/elastic/beats/heartbeat/monitors/active/dialchain.TLSLayer.func1.1(0x1757340, 0xc4201de700, 0x3, 0xc4201733c0, 0xd, 0x1757340)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/dialchain/tls.go:83 +0x45b
github.com/elastic/beats/heartbeat/monitors/active/dialchain.afterDial.func1(0x1670dc2, 0x3, 0xc4201733c0, 0xd, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/dialchain/util.go:89 +0xba
github.com/elastic/beats/libbeat/outputs/transport.DialerFunc.Dial(0xc42000d320, 0x1670dc2, 0x3, 0xc4201733c0, 0xd, 0x9bfe99, 0xc4206a5630, 0x50, 0x48)
	/go/src/github.com/elastic/beats/libbeat/outputs/transport/transport.go:40 +0x4e
github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).RoundTrip(0xc420693650, 0xc42019ee00, 0x0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:84 +0xfe
net/http.send(0xc42019ed00, 0x173b820, 0xc420693650, 0xbefd0eec14077578, 0xba8640061a, 0x1fc6900, 0xc4200bc2b0, 0xbefd0eec14077578, 0xc4205a9068, 0x1)
	/usr/local/go/src/net/http/client.go:252 +0x185
net/http.(*Client).send(0xc420693680, 0xc42019ed00, 0xbefd0eec14077578, 0xba8640061a, 0x1fc6900, 0xc4200bc2b0, 0x0, 0x1, 0x3)
	/usr/local/go/src/net/http/client.go:176 +0xfa
net/http.(*Client).Do(0xc420693680, 0xc42019ed00, 0x1fc6900, 0xc42019ed00, 0xb1597b)
	/usr/local/go/src/net/http/client.go:615 +0x28d
github.com/elastic/beats/heartbeat/monitors/active/http.execRequest(0xc420693680, 0xc42019ed00, 0x16bffd0, 0xbefd0ee814077485, 0xb6cc93652a, 0x1fc6900, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:252 +0xa6
github.com/elastic/beats/heartbeat/monitors/active/http.execPing(0xc420693680, 0xc4201bca00, 0x0, 0x0, 0x0, 0x3b9aca000, 0x16bffd0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:226 +0x13c
github.com/elastic/beats/heartbeat/monitors/active/http.createPingFactory.func1(0xc420693500, 0x9bf995, 0x7f8cec1221c8, 0x81)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:171 +0x442
github.com/elastic/beats/heartbeat/monitors.MakePingIPFactory.func1.1(0x6, 0xc4205a9778, 0x9bfe99)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:194 +0x31
github.com/elastic/beats/heartbeat/monitors.MakeSimpleCont.func1(0x10, 0x1534380, 0xc4205a97a8, 0x9bfe99, 0xc42000d060, 0x20)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:184 +0x26
github.com/elastic/beats/heartbeat/monitors.funcTask.Run(0xc4200705e0, 0x18, 0x20, 0x20, 0xc42000d060, 0x0, 0xc42008cc00)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:440 +0x27
github.com/elastic/beats/heartbeat/monitors.WithFields.func1(0xc4205a9701, 0xc42000d060, 0xc4205a97f8, 0xd62c21, 0x1566780, 0xc42000d060)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:398 +0x4a
github.com/elastic/beats/heartbeat/monitors.funcTask.Run(0xc42000d060, 0x173dee0, 0xc4200705e0, 0x173dee0, 0xc42000d060, 0x1fc6900, 0x14a912)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:440 +0x27
github.com/elastic/beats/heartbeat/monitors.makeByHostAnyIPJob.func1(0x0, 0x0, 0xc4203389b0, 0x9e43ab, 0x0, 0xc4203389c0)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:323 +0x939
github.com/elastic/beats/heartbeat/monitors.annotated.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42040e7c0, 0xa, 0xffffffffffffffff, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:140 +0xc7
github.com/elastic/beats/heartbeat/monitors.MakeJob.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420346000, 0xc420296f98, 0x0, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:127 +0xe8
github.com/elastic/beats/heartbeat/monitors.(*funcJob).Run(0xc4201cf3c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42015e388, 0xc42015e438, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:438 +0x82
github.com/elastic/beats/heartbeat/monitors.(Job).Run-fm(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420381701, 0xc4201b6020, 0xa27918, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/task.go:120 +0x86
github.com/elastic/beats/heartbeat/monitors.(*task).prepareSchedulerJob.func1(0x10, 0x16c0020, 0xc4201aa6e0)
	/go/src/github.com/elastic/beats/heartbeat/monitors/task.go:85 +0x7d
github.com/elastic/beats/heartbeat/scheduler.(*Scheduler).runTask.func1(0xc4201aa6e0, 0xc4203a6080, 0xc4201aa6e0, 0xc4201cfc40)
	/go/src/github.com/elastic/beats/heartbeat/scheduler/scheduler.go:362 +0x5b
created by github.com/elastic/beats/heartbeat/scheduler.(*Scheduler).runTask
	/go/src/github.com/elastic/beats/heartbeat/scheduler/scheduler.go:352 +0x5c



```

**Comment by andrewvc** [comment]
OK, we've got a PR in https://github.com/elastic/beats/pull/9566 

Out of curiosity @smartrics where did this cert come from? It's quite rare to find a cert with that field missing? `openssl` won't let you make a cert like that.

**Comment by tonybaines** [comment]
Yup @andrewvc, the x509 dump of the certificate on a 'real' server does include both dates (creation date and then 9999 days later)

**Comment by andrewvc** [comment]
@tonybaines that's really weird then. The way the failure happened made it seem pretty clear to me that it was missing that date, but if it's there then... weird?

Any chance that is a public endpoint or that you can share the cert?

**Comment by andrewvc** [comment]
Or, is there any chance you could build heartbeat off the branch in https://github.com/elastic/beats/pull/9566 and see if the problem still occurs?

**Comment by tonybaines** [comment]
The cert is a one-off for dev only, generated by the command above
[issue-9556-example-cert.pem.zip](https://github.com/elastic/beats/files/2693703/issue-9556-example-cert.pem.zip)

**Comment by smartrics** [comment]
Hi @andrewvc - what official version of heartbeat is this patch likely to be available in?

**Comment by andrewvc** [comment]
@smartrics I'm aiming for 6.6 with this backport in #9566, but I can't promise it'll make that. If not, we'll try for 6.6.1 or 6.7

**Comment by andrewvc** [comment]
@smartrics are you certain you're running the current version master? Which commit hash did you build?

Looking at the trace I see the line: `/home/fabrizio/Apps/go-1.11.2/src/github.com/elastic/beats/heartbeat/monitors/active/dialchain/tls.go:83 +0x455`

That line is [currently](https://github.com/elastic/beats/blob/master/heartbeat/monitors/active/dialchain/tls.go#L83) a comment. I suspect you're running an older commit

**Comment by andrewvc** [comment]
@smartrics glad to hear it :)

#9758 is the backport FYI. It will probably make it into 6.7
