### ISSUE TITLE
Central management tests are failling under 6.x / master

### ISSUE THREAD

**Issue by ph** [elastic/beats#9597]
https://travis-ci.org/elastic/beats/jobs/469089160
```
======================================================================
FAIL: Blacklist blocks bad configs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/go/src/github.com/elastic/beats/x-pack/libbeat/tests/system/test_management.py", line 188, in test_blacklist
    assert exit_code == 0
AssertionError
======================================================================
FAIL: Config cache is used if Kibana is not available
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/go/src/github.com/elastic/beats/x-pack/libbeat/tests/system/test_management.py", line 137, in test_configs_cache
    assert exit_code == 0
AssertionError
======================================================================
FAIL: Enroll the beat in Kibana Central Management
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/go/src/github.com/elastic/beats/x-pack/libbeat/tests/system/test_management.py", line 28, in test_enroll
    assert exit_code == 0
AssertionError
======================================================================
FAIL: Config is retrieved from Central Management and updates are applied
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/go/src/github.com/elastic/beats/x-pack/libbeat/tests/system/test_management.py", line 76, in test_fetch_configs
    assert exit_code == 0
AssertionError

**Comment by ph** [comment]
From what I see the tests fails for the same reasons.

```
Error creating a new enrollment token: fail to execute the HTTP POST request: Post http://kibana:5601/api/beats/enrollment_tokens: lookup kibana: no such host

**Comment by ph** [comment]
Looking at the build log we are hitting a Internal server error, this is why the tests fails on our side.


Looking at the kibana log for 6.x

````
{"type":"response","@timestamp":"2018-12-17T18:52:48Z","tags":[],"pid":1,"method":"post","statusCode":500,"req":{"url":"/api/beats/enrollment_tokens","method":"post","headers":{"host":"127.0.0.1:5601","user-agent":"Go-http-client/1.1","content-length":"4","accept":"application/json","content-type":"application/json","kbn-version":"","accept-encoding":"gzip"},"remoteAddress":"172.22.0.1","userAgent":"172.22.0.1"},"res":{"statusCode":500,"responseTime":30,"contentLength":9},"message":"POST /api/beats/enrollment_tokens 500 30ms - 9.0B"}
{"type":"response","@timestamp":"2018-12-17T18:52:48Z","tags":["api"],"pid":1,"method":"get","statusCode":200,"req":{"url":"/api/status","method":"get","headers":{"host":"localhost:5601","user-agent":"Python-urllib/1.17"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":200,"responseTime":11,"contentLength":9},"message":"GET /api/status 200 11ms - 9.0B"}
{"type":"error","@timestamp":"2018-12-17T18:52:48Z","tags":[],"pid":1,"level":"error","error":{"message":"Error parsing user info in beats_management,   Invalid value null supplied to : KibanaUser","name":"Error","stack":"Error: Error parsing user info in beats_management,   Invalid value null supplied to : KibanaUser\n    at KibanaBackendFrameworkAdapter.getUser (/usr/share/kibana/node_modules/x-pack/plugins/beats_management/server/lib/adapters/framework/kibana_framework_adapter.js:148:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/api/beats/enrollment_tokens","path":"/api/beats/enrollment_tokens","href":"/api/beats/enrollment_tokens"},"message":"Error parsing user info in beats_management,   Invalid value null supplied to : KibanaUser"}

**Comment by ph** [comment]
FYI, this is due to a change in the Management UI, we have added a few more strict validation and we effectively found a bug, this should affect master and 6.x @mattapperson is working on a fix.
