### ISSUE TITLE
[Packetbeat] Thrift Protocol Error - index out of range

### ISSUE THREAD

**Issue by zhangbo1** [elastic/beats#995]
```
2016/02/19 02:20:47.839635 log.go:113: ERR ParseThrift exception. Recovering, but please report this: runtime error: index out of range.
2016/02/19 02:20:47.840008 log.go:114: ERR Stacktrace: /go/src/github.com/elastic/beats/libbeat/logp/log.go:114 (0x4aa716)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4621ee)
/usr/local/go/src/runtime/panic.go:423 (0x4307c9)
/usr/local/go/src/runtime/panic.go:12 (0x42eca9)
/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:600 (0x517e72)
/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:674 (0x51ee7c)
/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:487 (0x5166f5)
/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:515 (0x516b71)
/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:668 (0x51eccc)
/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:619 (0x517cab)
/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:674 (0x51ee7c)
/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:708 (0x518c53)
/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:760 (0x519392)
/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:933 (0x51a879)
/go/src/github.com/elastic/beats/packetbeat/protos/tcp/tcp.go:101 (0x5114c1)
/go/src/github.com/elastic/beats/packetbeat/protos/tcp/tcp.go:164 (0x512003)
/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:183 (0x6f80a7)
/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:101 (0x6f75e1)
/go/src/github.com/elastic/beats/packetbeat/sniffer/sniffer.go:356 (0x526299)
/go/src/github.com/elastic/beats/packetbeat/beat/packetbeat.go:232 (0x4676fb)
/usr/local/go/src/runtime/asm_amd64.s:1721 (0x464561)
```

**Comment by andrewkroh** [comment]
What version are you running?

**Comment by zhangbo1** [comment]
packetbeat-1.1.1-x86_64

**Comment by zhangbo1** [comment]
@andrewkroh  packetbeat-1.1.1-x86_64

**Comment by davidbernard** [comment]
Similarly from packetbeat-5.6.1, centos 6.5

Monitoring scribe thrift RPC calls. Some of the calls could have a large number of log entries structures in an array. 

Trace:
2017-09-25T05:22:02Z INFO Non-zero metrics in the last 30s: libbeat.logstash.call_count.PublishEvents=30 libbeat.logstash.publish.read_bytes=222 libbeat.logstash.publish.write_bytes=65129 libbeat.logstash.published_and_acked_events=363 libbeat.publisher.messages_in_worker_queues=376 libbeat.publisher.published_events=376 tcp.dropped_because_of_gaps=1 thrift.unmatched_requests=1 thrift.unmatched_responses=21
2017-09-25T05:22:32Z INFO Non-zero metrics in the last 30s: libbeat.logstash.call_count.PublishEvents=30 libbeat.logstash.publish.read_bytes=588 libbeat.logstash.publish.write_bytes=114641 libbeat.logstash.published_and_acked_events=1199 libbeat.publisher.messages_in_worker_queues=1189 libbeat.publisher.published_events=1189 thrift.unmatched_requests=7 thrift.unmatched_responses=45
2017-09-25T05:23:02Z INFO Non-zero metrics in the last 30s: libbeat.logstash.call_count.PublishEvents=30 libbeat.logstash.publish.read_bytes=222 libbeat.logstash.publish.write_bytes=66187 libbeat.logstash.published_and_acked_events=382 libbeat.publisher.messages_in_worker_queues=402 libbeat.publisher.published_events=402 thrift.unmatched_responses=21
2017-09-25T05:23:32Z INFO Non-zero metrics in the last 30s: libbeat.logstash.call_count.PublishEvents=30 libbeat.logstash.publish.read_bytes=636 libbeat.logstash.publish.write_bytes=123977 libbeat.logstash.published_and_acked_events=1296 libbeat.publisher.messages_in_worker_queues=1279 libbeat.publisher.published_events=1279 thrift.unmatched_requests=2 thrift.unmatched_responses=19
2017-09-25T05:23:56Z ERR ParseThrift exception. Recovering, but please report this: runtime error: index out of range.
2017-09-25T05:23:56Z ERR Stacktrace: goroutine 10 [running]:
runtime/debug.Stack(0xbd68c4, 0x2b, 0xc4230b33c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/elastic/beats/libbeat/logp.Recover(0xbc4816, 0x15)
	/go/src/github.com/elastic/beats/libbeat/logp/log.go:145 +0x138
panic(0xada5c0, 0xc420014090)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readStruct(0xc4200da850, 0xc42181050a, 0xc6, 0x1af6, 0xc4220bcdd0, 0xc7, 0x101, 0xc7)
	/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:607 +0x57f
github.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).(github.com/elastic/beats/packetbeat/protos/thrift.readStruct)-fm(0xc42181050a, 0xc6, 0x1af6, 0xc4220bcdd0, 0xc7, 0xc421840101, 0xc7)
	/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:681 +0x48
github.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readListOrSet(0xc4200da850, 0xc42180a013, 0x65bd, 0x7fed, 0x1, 0xc421040e00, 0xc4230b3780, 0x5e8cea)
	/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:494 +0x148
github.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readList(0xc4200da850, 0xc42180a013, 0x65bd, 0x7fed, 0x20, 0xb27f60, 0xc4200a9401, 0xc421800ae0)
	/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:522 +0x50
github.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).(github.com/elastic/beats/packetbeat/protos/thrift.readList)-fm(0xc42180a013, 0x65bd, 0x7fed, 0x416c01, 0xc4230b3800, 0x4eb933, 0x3)
	/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:675 +0x48
github.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readField(0xc4200da850, 0xc423110300, 0xbd7be6, 0x2c)
	/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:715 +0x14f
github.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).messageParser(0xc4200da850, 0xc423110300, 0x1c48)
	/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:767 +0x1a4
github.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).Parse(0xc4200da850, 0xc4217fd740, 0xc4218bb878, 0xc4200da801, 0xaf1240, 0xc421040d00, 0x0, 0x0)
	/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:940 +0x1f9
github.com/elastic/beats/packetbeat/protos/tcp.(*TCPStream).addPacket(0xc4230b3b60, 0xc4217fd740, 0xc42126a5a0)
	/go/src/github.com/elastic/beats/packetbeat/protos/tcp/tcp.go:115 +0x176
github.com/elastic/beats/packetbeat/protos/tcp.(*TCP).Process(0xc4212581e0, 0x0, 0xc42126a5a0, 0xc4217fd740)
	/go/src/github.com/elastic/beats/packetbeat/protos/tcp/tcp.go:208 +0x3a2
github.com/elastic/beats/packetbeat/decoder.(*Decoder).onTCP(0xc42126a000, 0xc4217fd740)
	/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:317 +0xee
github.com/elastic/beats/packetbeat/decoder.(*Decoder).process(0xc42126a000, 0xc4217fd740, 0x2c, 0x1c48, 0x1180dc0, 0xc42126a000)
	/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:258 +0x222
github.com/elastic/beats/packetbeat/decoder.(*Decoder).OnPacket(0xc42126a000, 0xc421808044, 0x1c48, 0x1c48, 0xc42133ac90)
	/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:164 +0x343
github.com/elastic/beats/packetbeat/sniffer.(*SnifferSetup).Run(0xc42118f9e0, 0xc26fe0, 0xc421254210)
	/go/src/github.com/elastic/beats/packetbeat/sniffer/sniffer.go:381 +0x493
github.com/elastic/beats/packetbeat/beater.(*packetbeat).Run.func2(0xc421254210, 0xc420097400, 0xc421256300)
	/go/src/github.com/elastic/beats/packetbeat/beater/packetbeat.go:155 +0x6a
created by github.com/elastic/beats/packetbeat/beater.(*packetbeat).Run
	/go/src/github.com/elastic/beats/packetbeat/beater/packetbeat.go:159 +0x1b2

**Comment by npallavi1988** [comment]
Hi,
We are getting this issue in the latest version of packetbeats: 6.3.2 on centos 6.9. Not able to use packetbeats for thrift-rpc.  Any plans of fixing this in the upcoming releases?

Exception trace:

ERROR   runtime/panic.go:28     ParseThrift exception. Recovering, but please report this.{"panic": "runtime error: index out of range", "stack": "github.com/elastic/beats/libbeat/logp.Recover\n\t/go/src/github.com/elastic/beats/libbeat/logp/global.go:88\nruntime.call32\n\t/usr/local/go/src/runtime/asm_amd64.s:509\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:491\nruntime.panicindex\n\t/usr/local/go/src/runtime/panic.go:28\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readStruct\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:606\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).(github.com/elastic/beats/packetbeat/protos/thrift.readStruct)-fm\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:680\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readListOrSet\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:494\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readList\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:522\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).(github.com/elastic/beats/packetbeat/protos/thrift.readList)-fm\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:674\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readStruct\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:625\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).(github.com/elastic/beats/packetbeat/protos/thrift.readStruct)-fm\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:680\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readField\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:713\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).messageParser\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:765\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).Parse\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:938\ngithub.com/elastic/beats/packetbeat/protos/tcp.(*TCPStream).addPacket\n\t/go/src/github.com/elastic/beats/packetbeat/protos/tcp/tcp.go:127\ngithub.com/elastic/beats/packetbeat/protos/tcp.(*TCP).Process\n\t/go/src/github.com/elastic/beats/packetbeat/protos/tcp/tcp.go:222\ngithub.com/elastic/beats/packetbeat/decoder.(*Decoder).onTCP\n\t/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:317\ngithub.com/elastic/beats/packetbeat/decoder.(*Decoder).process\n\t/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:258\ngithub.com/elastic/beats/packetbeat/decoder.(*Decoder).OnPacket\n\t/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:164\ngithub.com/elastic/beats/packetbeat/sniffer.(*Sniffer).Run\n\t/go/src/github.com/elastic/beats/packetbeat/sniffer/sniffer.go:193\ngithub.com/elastic/beats/packetbeat/beater.(*packetbeat).Run.func2\n\t/go/src/github.com/elastic/beats/packetbeat/beater/packetbeat.go:202"}

**Comment by andrewkroh** [comment]
It looks like there needs to be a check against `len(data)` and the `offset` used at

https://github.com/adriansr/beats/blob/5cf200935b619c1432a04c48df4f3aba7047f23e/packetbeat/protos/thrift/thrift.go#L606

@npallavi1988 Would it be possible to share a pcap file of the traffic that's causing the failure? Then we can playback the pcap file to better understand the failure and prepare a patch. https://www.elastic.co/guide/en/beats/packetbeat/6.3/recording-trace.html

**Comment by npallavi1988** [comment]
Hi,
Please find the pcap file attached.
[trace.pcap.log](https://github.com/elastic/beats/files/2322611/trace.pcap.log)

**Mentioned below are packetbeat application logs:**

2018-08-16T02:33:57.470-0700	INFO	instance/beat.go:225	Setup Beat: packetbeat; Version: 6.3.2
2018-08-16T02:33:57.471-0700	INFO	pipeline/module.go:81	Beat name: 10.28.7.170
2018-08-16T02:33:57.471-0700	INFO	procs/procs.go:78	Process matching disabled
2018-08-16T02:33:57.471-0700	INFO	instance/beat.go:315	packetbeat start running.
2018-08-16T02:33:57.471-0700	INFO	[monitoring]	log/log.go:97	Starting metrics logging every 30s

2018-08-16T02:34:27.473-0700	INFO	[monitoring]	log/log.go:124	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":30,"time":{"ms":32}},"total":{"ticks":220,"time":{"ms":225},"value":220},"user":{"ticks":190,"time":{"ms":193}}},"info":{"ephemeral_id":"13165bf8-3842-4b24-9377-5f0f859a1e58","uptime":{"ms":30011}},"memstats":{"gc_next":22215344,"memory_alloc":20352248,"memory_total":21772016,"rss":48803840}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"logstash"},"pipeline":{"clients":1,"events":{"active":0}}},"system":{"cpu":{"cores":16},"load":{"1":0,"15":0.04,"5":0.02,"norm":{"1":0,"15":0.0025,"5":0.0013}}}}}}

2018-08-16T02:34:57.473-0700	INFO	[monitoring]	log/log.go:124	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":40,"time":{"ms":10}},"total":{"ticks":250,"time":{"ms":32},"value":250},"user":{"ticks":210,"time":{"ms":22}}},"info":{"ephemeral_id":"13165bf8-3842-4b24-9377-5f0f859a1e58","uptime":{"ms":60011}},"memstats":{"gc_next":22215344,"memory_alloc":20545064,"memory_total":21964832,"rss":204800}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":0}}},"system":{"load":{"1":0,"15":0.04,"5":0.02,"norm":{"1":0,"15":0.0025,"5":0.0013}}}}}}

2018-08-16T02:35:27.473-0700	INFO	[monitoring]	log/log.go:124	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":50,"time":{"ms":16}},"total":{"ticks":280,"time":{"ms":32},"value":280},"user":{"ticks":230,"time":{"ms":16}}},"info":{"ephemeral_id":"13165bf8-3842-4b24-9377-5f0f859a1e58","uptime":{"ms":90011}},"memstats":{"gc_next":22215344,"memory_alloc":20729416,"memory_total":22149184,"rss":192512}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":0}}},"system":{"load":{"1":0.06,"15":0.04,"5":0.03,"norm":{"1":0.0038,"15":0.0025,"5":0.0019}}}}}}
2018-08-16T02:35:57.473-0700	INFO	[monitoring]	log/log.go:124	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":70,"time":{"ms":14}},"total":{"ticks":370,"time":{"ms":85},"value":370},"user":{"ticks":300,"time":{"ms":71}}},"info":{"ephemeral_id":"13165bf8-3842-4b24-9377-5f0f859a1e58","uptime":{"ms":120011}},"memstats":{"gc_next":35608096,"memory_alloc":17809968,"memory_total":22327856,"rss":1359872}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":0}}},"system":{"load":{"1":0.03,"15":0.04,"5":0.03,"norm":{"1":0.0019,"15":0.0025,"5":0.0019}}}}}}
2018-08-16T02:35:58.743-0700	ERROR	runtime/panic.go:28	ParseThrift exception. Recovering, but please report this.	{"panic": "runtime error: index out of range", "stack": "github.com/elastic/beats/libbeat/logp.Recover\n\t/go/src/github.com/elastic/beats/libbeat/logp/global.go:88\nruntime.call32\n\t/usr/local/go/src/runtime/asm_amd64.s:509\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:491\nruntime.panicindex\n\t/usr/local/go/src/runtime/panic.go:28\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readStruct\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:606\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).(github.com/elastic/beats/packetbeat/protos/thrift.readStruct)-fm\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:680\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readListOrSet\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:494\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readList\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:522\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).(github.com/elastic/beats/packetbeat/protos/thrift.readList)-fm\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:674\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readStruct\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:625\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).(github.com/elastic/beats/packetbeat/protos/thrift.readStruct)-fm\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:680\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).readField\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:713\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).messageParser\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:765\ngithub.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).Parse\n\t/go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:938\ngithub.com/elastic/beats/packetbeat/protos/tcp.(*TCPStream).addPacket\n\t/go/src/github.com/elastic/beats/packetbeat/protos/tcp/tcp.go:127\ngithub.com/elastic/beats/packetbeat/protos/tcp.(*TCP).Process\n\t/go/src/github.com/elastic/beats/packetbeat/protos/tcp/tcp.go:222\ngithub.com/elastic/beats/packetbeat/decoder.(*Decoder).onTCP\n\t/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:317\ngithub.com/elastic/beats/packetbeat/decoder.(*Decoder).process\n\t/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:258\ngithub.com/elastic/beats/packetbeat/decoder.(*Decoder).OnPacket\n\t/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:164\ngithub.com/elastic/beats/packetbeat/sniffer.(*Sniffer).Run\n\t/go/src/github.com/elastic/beats/packetbeat/sniffer/sniffer.go:193\ngithub.com/elastic/beats/packetbeat/beater.(*packetbeat).Run.func2\n\t/go/src/github.com/elastic/beats/packetbeat/beater/packetbeat.go:202"}

2018-08-16T02:36:27.473-0700	INFO	[monitoring]	log/log.go:124	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":80,"time":{"ms":12}},"total":{"ticks":400,"time":{"ms":36},"value":400},"user":{"ticks":320,"time":{"ms":24}}},"info":{"ephemeral_id":"13165bf8-3842-4b24-9377-5f0f859a1e58","uptime":{"ms":150011}},"memstats":{"gc_next":35608096,"memory_alloc":18332904,"memory_total":22850792,"rss":135168}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":0}}},"system":{"load":{"1":0.02,"15":0.04,"5":0.02,"norm":{"1":0.0013,"15":0.0025,"5":0.0013}}}}}}
^C2018-08-16T02:36:37.605-0700	INFO	beater/packetbeat.go:221	Packetbeat send stop signal
2018-08-16T02:36:37.803-0700	INFO	[monitoring]	log/log.go:132	Total non-zero metrics	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":90,"time":{"ms":91}},"total":{"ticks":420,"time":{"ms":424},"value":420},"user":{"ticks":330,"time":{"ms":333}}},"info":{"ephemeral_id":"13165bf8-3842-4b24-9377-5f0f859a1e58","uptime":{"ms":160341}},"memstats":{"gc_next":35608096,"memory_alloc":18513656,"memory_total":23031544,"rss":46657536}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"logstash"},"pipeline":{"clients":1,"events":{"active":0}}},"system":{"cpu":{"cores":16},"load":{"1":0.02,"15":0.04,"5":0.02,"norm":{"1":0.0013,"15":0.0025,"5":0.0013}}}}}}

**Comment by npallavi1988** [comment]
Hi @andrewkroh,
Is there any fix available for this issue? 
Would like to explore Packetbeat for monitoring, but currently stuck at this problem.
