### ISSUE TITLE
[Flaky Test] Heartbeat active http monitor panics

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#9987]
## Flaky Test

* **Test Name:** github.com/elastic/beats/heartbeat/monitors/active/http
* **Link:** https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/3251/beat=heartbeat,label=ubuntu/console
* **Branch:** master

### Stack Trace

```
command [go test -race -tags integration -cover -coverprofile /tmp/gotestcover-460649162 github.com/elastic/beats/heartbeat/monitors/active/http]: exit status 1
22:10:50 panic: runtime error: invalid memory address or nil pointer dereference
22:10:50 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbaabd5]
22:10:50 
22:10:50 goroutine 429 [running]:
22:10:50 github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).readResponse(0xc000457380, 0xd9d460, 0xc000142088, 0xc0004e3100, 0xc000457300, 0xd9d460, 0xc000142080, 0xc0004e2d00)
22:10:50 	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:187 +0x235
22:10:50 github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).RoundTrip.func2(0xc000457380, 0xd9d460, 0xc000142088, 0xc0004e3100, 0xc0004e3100, 0xc000358720)
22:10:50 	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:111 +0x82
22:10:50 created by github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).RoundTrip
22:10:50 	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:110 +0x397
22:10:50 FAIL	github.com/elastic/beats/heartbeat/monitors/active/http	18.447s
```

**Comment by andrewvc** [comment]
This was fixed in https://github.com/elastic/beats/pull/10082
